### ISSUE TITLE
[1.10.2] ArmorPlus: 1.10.2-8.4.0.1's file name mistake

### ISSUE THREAD

**Issue by Iteries** [sokratis12GR/ArmorPlus#102]
**ArmorPlus Version**:  	armorplus-1.10.2-8.3.0.1   =   Armorplus: 1.10.2-8.4.0.1        

**TheDragonLib Version**: TheDragonLib-1.10.2-1.0.3.0

**MinecraftForge Version**: 2221

**Minecraft Version**: 1.10.2

**Client or Server?**:   

- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:  n/a

**What happens / happened?**:    When downloading Newest:  Armorplus: 1.10.2-8.4.0.1   on Curse it's downloading as armorplus-1.10.2-8.3.0.1

**How can I reproduce it?**:  download on curse

**Comment by sokratis12GR** [comment]
It downloads the correct one, just a derp of me forgetting to update the file name version in-game it should be showing "1.10.2-8.4.0.1"
