### ISSUE TITLE
[1.10.2] Superstar Armor/weapon Recipe not working

### ISSUE THREAD

**Issue by Iteries** [sokratis12GR/ArmorPlus#103]
**ArmorPlus Version**:  	 armorplus-1.10.2-8.3.0.1

**TheDragonLib Version**:  thedragonlib-1.10.2-1.0.3.0

**MinecraftForge Version**: 2221

**Minecraft Version**: 1.10.2

**Client or Server?**:  Client

**Crash Report (via. [Pastebin](http://pastebin.com/))**: n/a

**What happens / happened?**: When trying to create Superstar Armor not just producing.

**How can I reproduce it?**:  unknown, but using above version and when goto craft just not producing said armor as based up FTB wiki for how to do.   Only suggestion is please update wiki (I did try on lava sword but it looks cheesy on site)

**Comment by KewaiiGamer** [comment]
Did you try to use JEI to look up recipes?

**Comment by sokratis12GR** [comment]
@Iteries like KewaiiGamer recommended, try to use JEI the wiki recipes aren't really up to date
