### ISSUE TITLE
No recipe for high tech bench!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [sokratis12GR/ArmorPlus#107]
**ArmorPlus Version**: armorplus-1.10.2-8.5.0.1

**TheDragonLib Version**: thedragonlib-1.10.2-1.0.3.1

**MinecraftForge Version**: 1.10.2-forge1.10.2-12.18.3.2234

**Minecraft Version**: 1.10.2

There's no high-terch bench recipe (in JEI) to craft the next bench. But there's a recipe for the ulti-bench in high-tech bench.

**Comment by Moritz30** [comment]
Thank you for opening the issue. We will look at it.
