### ISSUE TITLE
[Feature Request] Config value for mob drops from A+

### ISSUE THREAD

**Issue by Boolyman** [sokratis12GR/ArmorPlus#108]
Can you please put an option in the config files to remove Wither Bone drops from Wither Skeletons?  
They are an Ultimate Armor ingredient, and should not be so easily available... at least not in my modpack.  

You have the option to control the number that drop from the Wither Boss... but whats the point, when you can just farm Wither Skeletons for hundreds of them?

**Comment by sokratis12GR** [comment]
Alright, going to add a config to disable the individual mobs :)

**Comment by sokratis12GR** [comment]
Added  in **1.10.2** **[armorplus-1.10.2-8.5.2.3](https://minecraft.curseforge.com/projects/armorplus/files/2385714)**
Coming soon to **1.11.2**

**Comment by sokratis12GR** [comment]
Added in **1.11.2** [armorplus-1.11.2-10.0.3.4](https://minecraft.curseforge.com/projects/armorplus/files/2386699) :)
