### ISSUE TITLE
[1.11.2] Crash (without forgelin)

### ISSUE THREAD

**Issue by ghost** [sokratis12GR/ArmorPlus#110]
after the latest updates of armorplus and dragonlib...
[crash-2017-02-26_20.57.49-client.txt](https://github.com/TheDragonTeam/ArmorPlus/files/802178/crash-2017-02-26_20.57.49-client.txt)

**Comment by sokratis12GR** [comment]
Looks like TheDragonLib 3.0.0 has some issues, going to fix it asap

**Comment by ghost** [comment]
ok waiting thx

**Comment by sokratis12GR** [comment]
actually nvm, you forgot to add Forgelin (the 1.11.2+ required dependency)
[Shadwofacts-forgelin](https://minecraft.curseforge.com/projects/shadowfacts-forgelin) 1.3.1+

**Comment by ghost** [comment]
ah, sorry.
