### ISSUE TITLE
kotlin.TypeCastException: null cannot be cast to non-null type net.minecraft.util.EnumFacing(1.11.2)

### ISSUE THREAD

**Issue by SDUBZ** [sokratis12GR/ArmorPlus#111]
**ArmorPlus Version**:
armorplus-1.11.2-10.0.3.4
**TheDragonLib Version**:
thedragonlib-1.11.2-3.0.0
**MinecraftForge Version**:
1.11.2-2252
**Minecraft Version**:
1.11.2
**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
[crash-2017-02-28_01.06.09-server.txt](https://github.com/TheDragonTeam/ArmorPlus/files/803855/crash-2017-02-28_01.06.09-server.txt)

**What happens / happened?**:
placed altar and it crashed me back to desktop
**How can I reproduce it?**:
get a altar and place it down and crash
**(Optional) Mod List**:
[print.txt](https://github.com/TheDragonTeam/ArmorPlus/files/803859/print.txt)

a little side note your lava infuser doesnt have textures thought id let you know if you were unaware
also its not accepting liquids

**Comment by sokratis12GR** [comment]
the altar is an experimental block which you aren't supposed to have... (I should have hidden it from JEI)
The lava infuser textures are still in the TODO list. It doesn't accept fuilds, but can be automated with lava buckets, because it only accepts them
