### ISSUE TITLE
Ender Dragon Zombie

### ISSUE THREAD

**Issue by Boolyman** [sokratis12GR/ArmorPlus#112]
The Ender Dragon Zombie seems to take drastically less damage than any other mob, for no apparent reason.  I am really hoping some silly damage per hit cap wasn't coded in to artificially increase the mobs difficulty.  I didnt see this in the configs to disable either.  Can you please let me know if there is in fact a damage per hit cap on the zombies?

**Comment by sokratis12GR** [comment]
the zombie it self is equiped with ender dragon armor

**Comment by Boolyman** [comment]
Ok, thats reasonable... thanks!  I hate when authors push artificial caps onto mobs.  Extra armor is more realistic.
