### ISSUE TITLE
crash server side(1.11.2)

### ISSUE THREAD

**Issue by SDUBZ** [sokratis12GR/ArmorPlus#113]
**ArmorPlus Version**:
armorplus-1.11.2-10.1.0.1
**TheDragonLib Version**:
thedragonlib-1.11.2-3.0.0
**MinecraftForge Version**:
1.11.2-2252
**Minecraft Version**:
1.11.2
**Client or Server?**:
- [ ] Client
- [x] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
[crash-2017-03-03_16.19.40-server.txt](https://github.com/TheDragonTeam/ArmorPlus/files/817963/crash-2017-03-03_16.19.40-server.txt)

**What happens / happened?**:
updated armor plaus and loaded up server and crash and now im here
**How can I reproduce it?**:
As above
**(Optional) Mod List**:

**Comment by SDUBZ** [comment]
also happens client side 
crash:
[crash-2017-03-04_08.42.51-client.txt](https://github.com/TheDragonTeam/ArmorPlus/files/817995/crash-2017-03-04_08.42.51-client.txt)

**Comment by sokratis12GR** [comment]
uhm... my bad the update isn't finished yet... (removing build from curse) please re-use the older version.

**Comment by SDUBZ** [comment]
okay
