### ISSUE TITLE
[Enhancement] Increase time on Night Vision enchantment - 1.10

### ISSUE THREAD

**Issue by ghost** [sokratis12GR/ArmorPlus#114]
**ArmorPlus Version**:
8.5.2.3
**TheDragonLib Version**:
1.0.3.1
**MinecraftForge Version**:
2221
**Minecraft Version**:
1.10.2
**Client or Server?**:
- [ ] Client
- [x] Server

**What happens / happened?**:
Night vision blinks for the last 10 seconds, and is only given for 12, also isn't refreshed until 1 second or less, thus it tends to make the screen blink most of the time. This effect would be much nicer if given for 24 seconds and refreshed at 12 or so.
**How can I reproduce it?**:
Wear any piece of coal helmet with default settings.

**Comment by sokratis12GR** [comment]
Going back to implement a way around it

**Comment by sokratis12GR** [comment]
Implemented in [armorplus-1.10.2-8.5.3.4](https://minecraft.curseforge.com/projects/armorplus/files/2389968) & [armorplus-1.11.2-10.1.0.1](https://minecraft.curseforge.com/projects/armorplus/files/2389976)
