### ISSUE TITLE
forgelin error causing game crash due to Workbench

### ISSUE THREAD

**Issue by Mulvaaken** [sokratis12GR/ArmorPlus#115]
ArmorPlus Version: armorplus-1.11.2-10.1.0.1.jar
TheDragonLib Version: thedragonlib-1.11.2-3.1.1.jar
MinecraftForge Version: forge-1.11.2-13.20.0.2255-installer.jar
Minecraft Version: 1.11.2
Client or Server?:
 Server
Crash Report (via. Pastebin): ---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.4.0.jar)
  FarseekCoreMod (Farseek-1.11-2.1.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.2.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 3/8/17 11:02 PM
Description: Unexpected error

kotlin.TypeCastException: null cannot be cast to non-null type net.minecraft.util.EnumFacing
	at net.thedragonteam.armorplus.tileentity.base.TileEntityBase.hasCapability(TileEntityBase.kt:29)
	at com.pau101.fairylights.client.ClientEventHandler.collectFasteners(ClientEventHandler.java:212)
	at com.pau101.fairylights.client.ClientEventHandler.collectFasteners(ClientEventHandler.java:191)
	at com.pau101.fairylights.client.ClientEventHandler.getHitConnection(ClientEventHandler.java:163)
	at com.pau101.fairylights.client.ClientEventHandler.updateHitConnection(ClientEventHandler.java:144)
	at com.pau101.fairylights.client.ClientProxy$1.func_110550_d(ClientProxy.java:169)
	at net.minecraft.client.renderer.texture.TextureManager.func_110550_d(TextureManager.java:141)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1667)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.thedragonteam.armorplus.tileentity.base.TileEntityBase.hasCapability(TileEntityBase.kt:29)
	at com.pau101.fairylights.client.ClientEventHandler.collectFasteners(ClientEventHandler.java:212)
	at com.pau101.fairylights.client.ClientEventHandler.collectFasteners(ClientEventHandler.java:191)
	at com.pau101.fairylights.client.ClientEventHandler.getHitConnection(ClientEventHandler.java:163)
	at com.pau101.fairylights.client.ClientEventHandler.updateHitConnection(ClientEventHandler.java:144)
	at com.pau101.fairylights.client.ClientProxy$1.func_110550_d(ClientProxy.java:169)
	at net.minecraft.client.renderer.texture.TextureManager.func_110550_d(TextureManager.java:141)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Mulvaaken'/282, l='MpServer', x=-17.87, y=5.00, z=-1209.70]]
	Chunk stats: MultiplayerChunkCache: 621, 621
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (180,64,236), Chunk: (at 4,4,12 in 11,14; contains blocks 176,0,224 to 191,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 12420896 game time, 13601673 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 92 total; [EntityPig['Pig'/515, l='MpServer', x=26.83, y=64.00, z=-1254.05], EntitySkeleton['Skeleton'/388, l='MpServer', x=-96.50, y=28.00, z=-1238.50], EntityChicken['Chicken'/516, l='MpServer', x=36.66, y=64.00, z=-1264.05], EntityHusk['Husk'/390, l='MpServer', x=-96.50, y=67.00, z=-1222.50], EntityChicken['Chicken'/518, l='MpServer', x=58.17, y=65.00, z=-1280.60], EntityWitch['Witch'/392, l='MpServer', x=-96.62, y=66.00, z=-1141.77], EntitySkeleton['Skeleton'/522, l='MpServer', x=54.51, y=65.00, z=-1207.22], EntityCreeper['Creeper'/524, l='MpServer', x=51.39, y=21.00, z=-1192.17], EntityPig['Pig'/525, l='MpServer', x=27.28, y=67.00, z=-1154.63], EntitySpider['Spider'/526, l='MpServer', x=21.97, y=67.00, z=-1159.01], EntitySkeleton['Skeleton'/405, l='MpServer', x=-94.50, y=28.00, z=-1235.50], EntityPig['Pig'/533, l='MpServer', x=-12.32, y=67.00, z=-1130.50], EntityRabbit['Rabbit'/406, l='MpServer', x=-83.75, y=64.00, z=-1235.94], EntityChicken['Chicken'/534, l='MpServer', x=-7.13, y=67.00, z=-1130.64], EntitySkeleton['Skeleton'/283, l='MpServer', x=-25.20, y=64.00, z=-1207.99], EntityCreeper['Creeper'/411, l='MpServer', x=-85.50, y=67.00, z=-1214.50], EntitySkeleton['Skeleton'/284, l='MpServer', x=-21.79, y=64.00, z=-1206.56], EntitySkeleton['Skeleton'/285, l='MpServer', x=-28.17, y=64.00, z=-1204.52], EntitySpider['Spider'/542, l='MpServer', x=39.49, y=15.00, z=-1177.05], EntitySpider['Spider'/543, l='MpServer', x=41.28, y=28.69, z=-1166.29], EntityBat['Bat'/544, l='MpServer', x=44.68, y=14.88, z=-1151.52], EntityPig['Pig'/545, l='MpServer', x=34.25, y=67.00, z=-1158.38], EntityPig['Pig'/546, l='MpServer', x=41.23, y=66.00, z=-1154.48], EntityPig['Pig'/547, l='MpServer', x=36.07, y=67.00, z=-1156.43], EntitySkeleton['Skeleton'/548, l='MpServer', x=49.50, y=22.00, z=-1171.22], EntityBat['Bat'/549, l='MpServer', x=46.96, y=34.06, z=-1154.47], EntityPig['Pig'/550, l='MpServer', x=57.54, y=66.00, z=-1168.55], EntitySpider['Spider'/552, l='MpServer', x=24.50, y=66.00, z=-1144.50], EntitySkeleton['Skeleton'/553, l='MpServer', x=20.72, y=66.00, z=-1144.82], EntityPig['Pig'/554, l='MpServer', x=30.68, y=65.00, z=-1136.58], EntitySkeleton['Skeleton'/558, l='MpServer', x=21.50, y=44.00, z=-1203.50], EntityPig['Pig'/559, l='MpServer', x=-16.21, y=64.00, z=-1147.67], EntityCreeper['Creeper'/560, l='MpServer', x=22.86, y=69.00, z=-1172.68], EntitySkeleton['Skeleton'/433, l='MpServer', x=-4.50, y=64.00, z=-1230.50], EntityZombie['Zombie'/561, l='MpServer', x=31.41, y=69.00, z=-1177.72], EntityCreeper['Creeper'/562, l='MpServer', x=31.93, y=69.00, z=-1182.57], EntitySkeleton['Skeleton'/563, l='MpServer', x=38.75, y=66.00, z=-1197.55], EntityChicken['Chicken'/564, l='MpServer', x=-12.86, y=66.00, z=-1136.50], EntitySpider['Spider'/566, l='MpServer', x=-1.87, y=64.00, z=-1145.30], EntitySpider['Spider'/567, l='MpServer', x=-3.21, y=64.00, z=-1151.04], EntityBat['Bat'/440, l='MpServer', x=-55.11, y=14.10, z=-1147.49], EntitySkeleton['Skeleton'/568, l='MpServer', x=1.50, y=64.00, z=-1155.50], EntitySkeleton['Skeleton'/569, l='MpServer', x=13.23, y=66.00, z=-1156.17], EntityZombie['Zombie'/443, l='MpServer', x=-42.72, y=63.00, z=-1211.54], EntitySkeleton['Skeleton'/444, l='MpServer', x=-25.74, y=64.00, z=-1205.48], EntityBat['Bat'/445, l='MpServer', x=-81.03, y=27.65, z=-1155.26], EntitySkeleton['Skeleton'/446, l='MpServer', x=-78.50, y=47.00, z=-1180.69], EntitySkeleton['Skeleton'/447, l='MpServer', x=-72.28, y=17.00, z=-1161.47], EntitySkeleton['Skeleton'/448, l='MpServer', x=-68.50, y=16.00, z=-1163.50], EntitySkeleton['Skeleton'/449, l='MpServer', x=-68.50, y=63.00, z=-1159.50], EntityCreeper['Creeper'/450, l='MpServer', x=-68.50, y=63.00, z=-1161.50], EntityPig['Pig'/578, l='MpServer', x=-2.29, y=65.00, z=-1265.54], EntitySkeleton['Skeleton'/451, l='MpServer', x=-55.76, y=64.00, z=-1180.65], EntityChicken['Chicken'/579, l='MpServer', x=13.78, y=68.00, z=-1280.49], EntitySkeleton['Skeleton'/452, l='MpServer', x=-63.50, y=63.00, z=-1158.50], EntityZombie['Zombie'/581, l='MpServer', x=-27.51, y=38.00, z=-1235.20], EntityBat['Bat'/456, l='MpServer', x=-46.21, y=18.77, z=-1130.51], EntityPig['Pig'/584, l='MpServer', x=9.35, y=65.00, z=-1269.73], EntityPig['Pig'/457, l='MpServer', x=-37.45, y=63.00, z=-1129.68], EntitySkeleton['Skeleton'/586, l='MpServer', x=-27.50, y=71.00, z=-1281.50], EntityPig['Pig'/587, l='MpServer', x=-5.87, y=66.00, z=-1287.77], EntityPig['Pig'/460, l='MpServer', x=-61.78, y=66.00, z=-1280.71], EntityCreeper['Creeper'/588, l='MpServer', x=-15.50, y=67.00, z=-1284.50], EntityRabbit['Rabbit'/462, l='MpServer', x=-73.61, y=65.88, z=-1249.69], EntityRabbit['Rabbit'/463, l='MpServer', x=-69.41, y=65.88, z=-1251.78], EntityCreeper['Creeper'/464, l='MpServer', x=-73.79, y=68.00, z=-1260.52], EntityCreeper['Creeper'/465, l='MpServer', x=-77.50, y=68.00, z=-1261.50], EntityZombie['Zombie'/466, l='MpServer', x=-62.50, y=63.00, z=-1222.50], EntitySpider['Spider'/467, l='MpServer', x=-57.23, y=63.00, z=-1217.05], EntityBat['Bat'/468, l='MpServer', x=-80.60, y=26.84, z=-1165.06], EntityZombieVillager['Zombie Villager'/469, l='MpServer', x=-63.48, y=65.00, z=-1264.28], EntitySkeleton['Skeleton'/470, l='MpServer', x=-44.50, y=65.00, z=-1265.27], EntityPlayerSP['Mulvaaken'/282, l='MpServer', x=-17.87, y=5.00, z=-1209.70], EntityBat['Bat'/349, l='MpServer', x=-18.52, y=40.45, z=-1222.61], EntityZombie['Zombie'/350, l='MpServer', x=-17.79, y=64.00, z=-1225.76], EntityEnderman['Enderman'/351, l='MpServer', x=-18.33, y=35.00, z=-1215.43], EntityChicken['Chicken'/740, l='MpServer', x=16.21, y=64.00, z=-1132.89], EntityCreeper['Creeper'/742, l='MpServer', x=45.50, y=22.00, z=-1140.50], EntityPig['Pig'/743, l='MpServer', x=35.28, y=66.00, z=-1151.45], EntityChicken['Chicken'/492, l='MpServer', x=56.36, y=65.00, z=-1266.15], EntitySkeleton['Skeleton'/493, l='MpServer', x=22.75, y=64.00, z=-1240.72], EntityChicken['Chicken'/495, l='MpServer', x=55.82, y=64.00, z=-1256.43], EntityZombie['Zombie'/751, l='MpServer', x=56.63, y=65.00, z=-1138.24], EntityCreeper['Creeper'/496, l='MpServer', x=-5.84, y=21.00, z=-1176.59], EntityCreeper['Creeper'/497, l='MpServer', x=-11.50, y=22.00, z=-1181.50], EntityZombie['Zombie'/753, l='MpServer', x=39.14, y=63.00, z=-1128.86], EntitySkeleton['Skeleton'/498, l='MpServer', x=10.50, y=64.00, z=-1262.50], EntityCreeper['Creeper'/499, l='MpServer', x=31.50, y=64.00, z=-1264.50], EntityCreeper['Creeper'/500, l='MpServer', x=23.62, y=64.00, z=-1269.22], EntitySkeleton['Skeleton'/501, l='MpServer', x=-1.77, y=64.00, z=-1228.82], EntityChicken['Chicken'/507, l='MpServer', x=43.14, y=66.00, z=-1285.59], EntitySkeleton['Skeleton'/508, l='MpServer', x=44.44, y=66.00, z=-1286.29]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:401)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1699268616 bytes (1620 MB) / 3829620736 bytes (3652 MB) up to 4268163072 bytes (4070 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.38 Powered by Forge 13.20.0.2255 Optifine OptiFine_1.11.2_HD_U_B7 43 mods loaded, 43 mods active
	States:
 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2255.jar) 
	UCHIJAAAA	forge{13.20.0.2255} [Minecraft Forge] (forge-1.11.2-13.20.0.2255.jar) 
	UCHIJAAAA	adobeblocks{7.0.1} [Adobe Blocks 2] (Adobe-Blocks-2-Mod-1.11.2.jar) 
	UCHIJAAAA	ambientsounds{1.2.0} [AmbientSounds] (AmbientSounds v1.2.2 mc1.11.zip) 
	UCHIJAAAA	forgelin{1.4.0} [Forgelin] (Forgelin-1.4.0.jar) 
	UCHIJAAAA	thedragonlib{1.11.2-3.1.1} [TheDragonLib] (thedragonlib-1.11.2-3.1.1.jar) 
	UCHIJAAAA	armorplus{1.11.2-10.1.0.1} [ArmorPlus] (armorplus-1.11.2-10.1.0.1.jar) 
	UCHIJAAAA	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.11-1.1.4.jar) 
	UCHIJAAAA	biomesoplenty{6.0.2.2157} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.0.2.2157-universal.jar) 
	UCHIJAAAA	birdsnests{1.5.1} [Bird's Nests] (BirdsNests1.11.2-1.5.1.jar) 
	UCHIJAAAA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.11.2.jar) 
	UCHIJAAAA	fairylights{2.0.6} [Fairy Lights] (fairylights-2.0.6-1.11.jar) 
	UCHIJAAAA	farseek{2.1} [Farseek] (Farseek-1.11-2.1.jar) 
	UCHIJAAAA	giacomosfoundry{1.3.9} [Giacomo's Foundry] (Giacomos-Foundry-Mod-1.11.2.jar) 
	UCHIJAAAA	giacomos_bookshelf{1.0.5} [Giacomo's Bookshelves Mod] (GiacomosBookshelf-1.11.2-1.0.5.jar) 
	UCHIJAAAA	fishing{1.4.9} [Fishing Net Mod] (GiacomosFishingNet-1.11.2-1.4.9.jar) 
	UCHIJAAAA	giacomos_maps{1.0.1} [Giacomo's maps] (GiacomosMaps-1.11.2-1.0.1.jar) 
	UCHIJAAAA	giacomostravelogue{1.0.4} [Giacomo’s Travelogue] (GiacomosTravelogue-1.11.2-1.0.4.jar) 
	UCHIJAAAA	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar) 
	UCHIJAAAA	hcmw{1.0} [Homecraft Mineware] (hcmw-1.11.2-0.2.9-universal.jar) 
	UCHIJAAAA	ironchest{1.11-7.0.17.799} [Iron Chest] (IronChest-1.11.jar) 
	UCHIJAAAA	jei{4.2.8.242} [Just Enough Items] (jei_1.11.2-4.2.8.242.jar) 
	UCHIJAAAA	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHIJAAAA	kleeslabs{4.3.2} [KleeSlabs] (KleeSlabs_1.11.2-4.3.2.jar) 
	UCHIJAAAA	magicalmap{1.0.0} [Magical Map] (Magical Map-1.0.0.jar) 
	UCHIJAAAA	missing_pieces{4.1.2} [Missing Pieces] (Missing-Pieces-Mod-1.11.2.jar) 
	UCHIJAAAA	shear{1.1.2} [More Shearables] (MoreShearables1.2.2-1.11.2.jar) 
	UCHIJAAAA	shetiphiancore{3.4.1} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.2.jar) 
	UCHIJAAAA	multibeds{1.3.2} [Multi-Beds] (MultiBeds-Mod-1.11.2.jar) 
	UCHIJAAAA	harvestcraft{1.11.2e} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2e.jar) 
	UCHIJAAAA	platforms{1.3.2} [Platforms] (platforms-1.11.0-1.3.2.jar) 
	UCHIJAAAA	roots{0.010} [Roots 2] (roots-2-0.011.jar) 
	UCHIJAAAA	spartanshields{1.2a} [Spartan Shields] (SpartanShields-1.11-1.2a.jar) 
	UCHIJAAAA	staircraftmod{7.0} [Staircraft] (Staircraftmod v7.0 - MC1.11 Forge.jar) 
	UCHIJAAAA	streams{0.3} [Streams] (Streams-1.11-0.3.jar) 
	UCHIJAAAA	substratum{1.9.2.0} [Substratum] (Substratum-1.11.2-1.9.2.0.jar) 
	UCHIJAAAA	terraqueous{1.3.6} [Terraqueous] (terraqueous-1.11.0-1.3.6.jar) 
	UCHIJAAAA	villagenames{1.11.2-1.0} [Village Names] (VillageNames-1.11.2-1.0.jar) 
	UCHIJAAAA	waddles{0.5.1} [Waddles] (Waddles-1.11-0.5.1.jar) 
	UCHIJAAAA	wallcraftmod{7.0} [Wallcraft] (Wallcraftmod v7.0 - MC1.11 Forge.jar) 
	UCHIJAAAA	wolfarmor{1.3.2} [Wolf Armor and Storage] (wolfarmor-1.3.3.6.jar) 
	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.4.0.jar)
  
FarseekCoreMod (Farseek-1.11-2.1.jar)
  farseek.core.FarseekClassTransformer
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.2.jar)
  shetiphian.core.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 378.66' Renderer: 'GeForce GTX 950/PCIe/SSE2'
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2255
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 950/PCIe/SSE2 GL version 4.5.0 NVIDIA 378.66, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Affinity-HD-Bundle-x256.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
	OptiFine Version: OptiFine_1.11.2_HD_U_B7
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 378.66
	OpenGlRenderer: GeForce GTX 950/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
What happens / happened?: 1) While attempting to 'destroy' Workbench (left-click w/tool), game froze & crashed; while attempting to 'use' workbench (right-click), game froze & crashed.  Also, in JEI menu Workbench is shown twice, once with name 'Workbench' and once with an 'item.name' tag, which has no uses or recipes attached to it.
Game generated a kotlin error, as well as the crash log: “kotlin.TypeCastException: null cannot be cast to non-null type net.minecraft.util.EnumFacing”
While making sure I had everything updated correctly, I also noticed that installing the mod (by putting it in mod folder & starting Minecraft), it created both an 'armorplus' folder, which was empty, AND a file named 'armorplus.cfg' in the config folder.

How can I reproduce it?: This has occurred every time I have attempted to use the Workbench, and even making another workbench has not helped – neither of them has worked.  As I have no other way to remove the workbenches, I have opted to remove armorplus/thedragonlib/forgelin until I hear from you – thanks!
(Optional) Mod List:

**Comment by sokratis12GR** [comment]
It looks like FairyLights is the mod causing the issue

**Comment by sokratis12GR** [comment]
nvm releasing a fix in a sec

**Comment by Mulvaaken** [comment]
k - I saw that too, but wanted to make sure... I'll pull that out and try again (my gf is gonna be hot, but oh well :) )
Thanks for the prompt response - love the mod!

**Comment by Mulvaaken** [comment]
Whoops - hehehe - I'm a developer myself, I feel your pain :)

**Comment by sokratis12GR** [comment]
File *should* be live and have the issue fixed. Let me know if it happens again

**Comment by Mulvaaken** [comment]
Will do, thanks much!

**Comment by Mulvaaken** [comment]
No joy, sok... Removed previous version, deleted armorplus items in \config... Right-clicked on workbench, bench opened, displayed my inventory below, then game promptly crashed before I could do anything else...
[crash-2017-03-09_12.42.59-client.txt](https://github.com/TheDragonTeam/ArmorPlus/files/831859/crash-2017-03-09_12.42.59-client.txt)


"The game crashed whilst unexpected error
The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method net.thedragonteam.armorplus.tileentity.base.TileEntityInventoryBase.getItemHandler, parameter facing"
~ Mul

**Comment by sokratis12GR** [comment]
u.u ... give me another sec... thats from another tile entity... In the end I'll keep all tile entities away from kotlin..

**Comment by Mulvaaken** [comment]
kk, added new crash report just now...

**Comment by Mulvaaken** [comment]
sok:
    armorplus-1.11.2-10.1.2.3.jar appears to have fixed the issue - many thanks! Please be aware the issue with JEI still exists - multiple workbenches - and I also noticed the 2 advanced tables are not searchable in JEI using 'bench' (maybe just my issue?)
Have a great weekend!
~ Mul

**Comment by sokratis12GR** [comment]
Alright, going to take a look at it! I must thank you for your report!
