### ISSUE TITLE
Outdated Optifine version problems

### ISSUE THREAD

**Issue by ghost** [sokratis12GR/ArmorPlus#117]
hi , i have a problem with Armor plus

Im using a mod "Just Enough items" and when i change the pages of the list of blocks "in the armors" in the inventory , it crash at page 4 , there is surely a problem

i really need help

thanks.

**Comment by sokratis12GR** [comment]
I need crashlog in order to help :)

**Comment by ghost** [comment]
okay , here it is :


---- Minecraft Crash Report ----

WARNING: coremods are present:
  BCModPlugin (Backpacks-Mod-by-Brad16840-1.11.2.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 3/23/17 5:55 PM
Description: Unexpected error

java.lang.IllegalStateException: Already building!
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:291)
	at net.minecraft.client.shader.Framebuffer.func_178038_a(Framebuffer.java:264)
	at net.minecraft.client.shader.Framebuffer.func_147615_c(Framebuffer.java:229)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1104)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:291)
	at net.minecraft.client.shader.Framebuffer.func_178038_a(Framebuffer.java:264)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['RayanAuditore'/578, l='MpServer', x=-864.50, y=3.00, z=235.50]]
	Chunk stats: MultiplayerChunkCache: 168, 168
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-438,4,131), Chunk: (at 10,0,3 in -28,8; contains blocks -448,0,128 to -433,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 168839 game time, 96535 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 54 total; [EntityItem['item.item.potatoPoisonous'/908, l='MpServer', x=-898.08, y=4.94, z=246.30], EntityVillager['Villager'/559, l='MpServer', x=-858.29, y=5.00, z=241.45], EntityVillager['Villager'/560, l='MpServer', x=-866.03, y=5.00, z=265.59], EntityVillager['Villager'/561, l='MpServer', x=-865.30, y=5.00, z=265.17], EntityVillager['Villager'/562, l='MpServer', x=-879.40, y=3.94, z=259.52], EntityVillager['Villager'/563, l='MpServer', x=-886.57, y=5.00, z=266.70], EntityVillager['Villager'/564, l='MpServer', x=-895.35, y=4.94, z=270.50], EntityVillager['Villager'/565, l='MpServer', x=-882.57, y=5.00, z=256.52], EntityVillager['Villager'/566, l='MpServer', x=-887.41, y=5.00, z=270.28], EntityVillager['Villager'/567, l='MpServer', x=-888.70, y=5.00, z=287.70], EntityVillager['Villager'/568, l='MpServer', x=-895.04, y=5.00, z=284.52], EntityVillager['Villager'/569, l='MpServer', x=-880.50, y=5.00, z=230.70], EntityVillager['Villager'/570, l='MpServer', x=-883.63, y=4.00, z=226.49], EntityVillager['Villager'/571, l='MpServer', x=-878.55, y=4.00, z=228.34], EntityVillager['Villager'/572, l='MpServer', x=-911.48, y=5.00, z=220.92], EntityVillager['Villager'/573, l='MpServer', x=-901.52, y=4.94, z=292.71], EntityVillager['Villager'/574, l='MpServer', x=-910.50, y=5.00, z=299.49], EntityVillager['Villager'/575, l='MpServer', x=-899.39, y=3.94, z=298.49], EntityVillager['Villager'/576, l='MpServer', x=-884.57, y=5.00, z=293.50], EntityItem['item.tile.dirt.default'/579, l='MpServer', x=-855.26, y=3.00, z=228.13], EntityItem['item.tile.dirt.default'/580, l='MpServer', x=-852.87, y=4.00, z=229.92], EntityItem['item.tile.dirt.default'/581, l='MpServer', x=-853.37, y=3.00, z=230.60], EntityItem['item.tile.wood.oak'/582, l='MpServer', x=-861.28, y=4.00, z=229.88], EntityItem['item.tile.wood.oak'/583, l='MpServer', x=-863.38, y=5.00, z=229.88], EntityPlayerSP['RayanAuditore'/578, l='MpServer', x=-864.50, y=3.00, z=235.50], EntityVillager['Villager'/592, l='MpServer', x=-886.26, y=4.00, z=213.19], EntityVillager['Villager'/593, l='MpServer', x=-886.15, y=5.00, z=222.23], EntityVillager['Villager'/595, l='MpServer', x=-866.66, y=4.94, z=215.43], EntityVillager['Villager'/596, l='MpServer', x=-875.67, y=4.94, z=215.50], EntityVillager['Villager'/597, l='MpServer', x=-897.53, y=4.94, z=246.34], EntityItem['item.tile.dirt.default'/598, l='MpServer', x=-822.88, y=1.00, z=190.88], EntityItem['item.tile.dirt.default'/599, l='MpServer', x=-822.88, y=1.00, z=182.24], EntityItem['item.tile.dirt.default'/600, l='MpServer', x=-821.43, y=1.00, z=190.57], EntityItem['item.tile.dirt.default'/601, l='MpServer', x=-822.66, y=1.00, z=189.90], EntityItem['item.tile.dirt.default'/602, l='MpServer', x=-822.69, y=1.00, z=188.88], EntityItem['item.tile.dirt.default'/603, l='MpServer', x=-823.58, y=1.00, z=188.42], EntityItem['item.tile.dirt.default'/604, l='MpServer', x=-824.73, y=1.00, z=186.13], EntityItem['item.tile.dirt.default'/605, l='MpServer', x=-824.75, y=1.00, z=184.42], EntityItem['item.tile.dirt.default'/606, l='MpServer', x=-890.88, y=3.00, z=248.88], EntityItem['item.tile.dirt.default'/607, l='MpServer', x=-889.88, y=3.00, z=247.82], EntityItem['item.tile.dirt.default'/608, l='MpServer', x=-888.45, y=3.00, z=249.88], EntityItem['item.tile.dirt.default'/609, l='MpServer', x=-889.61, y=3.00, z=249.88], EntityItem['item.tile.dirt.default'/611, l='MpServer', x=-800.88, y=2.00, z=183.71], EntityItem['item.tile.dirt.default'/612, l='MpServer', x=-800.88, y=2.00, z=182.13], EntityItem['item.tile.dirt.default'/614, l='MpServer', x=-801.13, y=1.00, z=184.40], EntityItem['item.tile.dirt.default'/615, l='MpServer', x=-802.28, y=1.00, z=184.22], EntityItem['item.tile.dirt.default'/616, l='MpServer', x=-803.24, y=1.00, z=183.56], EntityItem['item.tile.dirt.default'/617, l='MpServer', x=-809.30, y=1.00, z=182.13], EntityItem['item.tile.dirt.default'/618, l='MpServer', x=-815.88, y=3.00, z=180.60], EntityItem['item.tile.dirt.default'/623, l='MpServer', x=-803.59, y=3.00, z=201.07], EntityItem['item.tile.dirt.default'/624, l='MpServer', x=-805.88, y=2.00, z=200.53], EntityItem['item.tile.dirt.default'/625, l='MpServer', x=-805.88, y=2.00, z=199.77], EntityItem['item.tile.dirt.default'/627, l='MpServer', x=-803.98, y=1.00, z=195.88], EntityVillager['Villager'/630, l='MpServer', x=-871.49, y=4.00, z=272.42]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:401)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_73, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 77134784 bytes (73 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2259 Optifine OptiFine_1.11.2_HD_U_B5 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2259.jar) 
	UCHIJAAAA	forge{13.20.0.2259} [Minecraft Forge] (forge-1.11.2-13.20.0.2259.jar) 
	UCHIJAAAA	backpacks16840{3.1.6} [Backpacks!] (Backpacks-Mod-by-Brad16840-1.11.2.jar) 
	UCHIJAAAA	forgelin{1.3.0} [Forgelin] (Forgelin-1.3.0.jar) 
	UCHIJAAAA	thedragonlib{1.11.2-3.1.1} [TheDragonLib] (thedragonlib-1.11.2-3.1.1 (1).jar) 
	UCHIJAAAA	armorplus{1.11.2-10.1.1.2} [ArmorPlus] (armorplus-1.11.2-10.1.1.2.jar) 
	UCHIJAAAA	ironchest{1.11.2-7.0.18.800} [Iron Chest] (Iron-Chests-Mod-1.11.2.jar) 
	UCHIJAAAA	jei{4.2.10.248} [Just Enough Items] (jei_1.11.2-4.2.10.248.jar) 
	UCHIJAAAA	lucky{7.4.0} [Lucky Block] (LuckyBlock_1-11_v7-4-0.zip) 
	UCHIJAAAA	metamorph{1.1} [Metamorph] (Metamorph-1.11.2.jar) 
	UCHIJAAAA	mysticalagriculture{1.4.3} [Mystical Agriculture] (mysticalagriculture[1.11.2]-1.4.3a.jar) 
	UCHIJAAAA	xaerominimap{1.11.7} [Xaero's Minimap] (Xaeros_Minimap_1.11.7_Forge_1.11.jar) 
	Loaded coremods (and transformers): 
BCModPlugin (Backpacks-Mod-by-Brad16840-1.11.2.jar)
  brad16840.common.asm.ClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.15.4248' Renderer: 'Intel(R) HD Graphics'
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2259
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics GL version 4.3.0 - Build 10.18.15.4248, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Faithful 1.11-rv2.zip
	Current Language: English (Canada)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Celeron(R) CPU N3050 @ 1.60GHz
	OptiFine Version: OptiFine_1.11.2_HD_U_B5
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.3.0 - Build 10.18.15.4248
	OpenGlRenderer: Intel(R) HD Graphics
	OpenGlVendor: Intel
	CpuCount: 2

**Comment by sokratis12GR** [comment]
`OptiFine_1.11.2_HD_U_B5`
Its a bug with optifine
try to use
`OptiFine_1.11.2_HD_U_B7`

**Comment by ghost** [comment]
ill try , thank u a lot anyway :)

**Comment by ghost** [comment]
thanks bro 💯
