### ISSUE TITLE
[Feature Request] Lava Crystal blocks (not like oreLavaCrystal, but like blockLavaCrystal) for better storage.

### ISSUE THREAD

**Issue by JaSpr** [sokratis12GR/ArmorPlus#120]
Just want to be able to convert 9 lava crystal (or charged lava crystal) into lava crystal blocks (and charged blocks)

**Comment by sokratis12GR** [comment]
Will come for 1.11.2

**Comment by ghost** [comment]
yeah , thats would be good :)

**Comment by sokratis12GR** [comment]
Alright, after so many issues occurred for 1.11.2 ... I'm going to release a pre-change update including this :)

**Comment by sokratis12GR** [comment]
Added in [armorplus-1.11.2-10.2.1.2](https://minecraft.curseforge.com/projects/armorplus/files/2416195) :)
