### ISSUE TITLE
[Feature Request] Add interfacing to crafting tables to Workbenches, to allow items to be input/output in automation.

### ISSUE THREAD

**Issue by JaSpr** [sokratis12GR/ArmorPlus#121]
I was attempting (with Refined Storage) to set up an auto-crafting recipe to input the required ingredients for charged lava crystal in the workbench and extract the finished product back into the Refined Storage system, but the workbenches don't have the interface for input/output to make this work.

**Comment by sokratis12GR** [comment]
Sorry, but this won't happen
1. For 1.11.2 I have some more planned changes for things. (The lava infuser how ever CAN be automated)
2. For 1.10.2 I only support bug fixes and Lang updates.
Ps: there might be automation soon tho, will see.

Thank you for your feedback!
