### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [sokratis12GR/ArmorPlus#124]
me , again

just a question , where do we get lava crystals ? "ore,loot,...."

thanks 👍

**Comment by sokratis12GR** [comment]
mining the "Block Lava Crystal" which can be found between y level (6 - 16/18) depending on your config file values, you need a diamond pick to break the blocks

**Comment by ghost** [comment]
THANKS !

**Comment by ghost** [comment]
but if i created a world before instaling the mod , would it appear in mines ?

**Comment by sokratis12GR** [comment]
in loaded chunks, no... only new unloaded chunks will have them

**Comment by ghost** [comment]
i thank u from the deep of my heart thx

**Comment by ghost** [comment]
last question : are these ores "lava crystal" are rare ? "like diamonds ect..."

**Comment by sokratis12GR** [comment]
kind a

**Comment by ghost** [comment]
thx :3
