### ISSUE TITLE
What the...

### ISSUE THREAD

**Issue by ghost** [sokratis12GR/ArmorPlus#125]
me,again

hi , i was playing normally , then i found a weird thing in the gift of gods

first : a "The Dragon Team" item

second : a "Jon Bams" item

what are these ?

**Comment by sokratis12GR** [comment]
cosmetic items

**Comment by ghost** [comment]
oh...

sorry for the annoying question x)

**Comment by sokratis12GR** [comment]
uhm discussions like this could be made in our discord server instead of creating such issues, feel free to join with this link: http://discord.thedragonteam.info/

**Comment by ghost** [comment]
Thanks a million times :)
