### ISSUE TITLE
[1.10.2] ArmorPlus Book contains outdated information

### ISSUE THREAD

**Issue by a-frenzy** [sokratis12GR/ArmorPlus#127]
**ArmorPlus Version 8.5.3.4**:

**TheDragonLib Version 1.0.3.0**:

**MinecraftForge Version 12.18.3.2239**:

**Minecraft Version 1.10.2**:

**Client or Server? both**:
- [X] Client
- [X] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: none

**What happens / happened?**: armorplus book describes the ultimate armor as giving nightvision, it doesn't, and the armorplus properties google doc does not mention nightvision for ultimate armor 

**How can I reproduce it?**: 

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
Miss-information inside the book, will be fixed in the next update

**Comment by sokratis12GR** [comment]
Fixed in [1.10.2-8.5.4.5](https://minecraft.curseforge.com/projects/armorplus/files/2404667)
