### ISSUE TITLE
[1.11.2] Lava Infuser Missing Textures & Model

### ISSUE THREAD

**Issue by TheLimePixel** [sokratis12GR/ArmorPlus#128]
On the latest 1.11.2 version of the mod the Lava Infuser's item and block texture seems to be broken.

**Comment by sokratis12GR** [comment]
That's known, textures will be added after the upcoming major update... but don't expect it to be soon, sorry.

**Comment by sokratis12GR** [comment]
Added in [armorplus-1.11.2-10.2.0.1](https://minecraft.curseforge.com/projects/armorplus/files/2415900) :)
