### ISSUE TITLE
[1.9.4] Super Star Boots

### ISSUE THREAD

**Issue by m1jordanallen** [sokratis12GR/ArmorPlus#13]
The regeneration 2 effect on the super star armor does not work while the armor is on.  As soon as you remove the armor, and while the effect starts to wear out it begins to work.  I have tested this in the current recommended forge (1887) and an earlier version(1865).

**Comment by sokratis12GR** [comment]
What exactly you mean ?
The Super Star Armor works fine.

**Comment by m1jordanallen** [comment]
the regen effect shows on the hearts regenning while the suit is on, but the effect doesnt actually regen when not at full health.  Once the armor is removed, regen 2 takes actual effect.  After work tonight, I will take a short video of this happening to show exactly what Im describing.
