### ISSUE TITLE
Easy recipe difficulty breaks recipes and high-tech bench

### ISSUE THREAD

**Issue by Naxdar** [sokratis12GR/ArmorPlus#130]
**ArmorPlus Version**: 1.10.2-8.5.4.5

**TheDragonLib Version**: 1.10.2-1.0.3.1

**MinecraftForge Version**: 12.18.3.2281

**Minecraft Version**: 1.10.2

**Client or Server?**: Tested on both
- [x] Client
- [x] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:

**What happens / happened?**:
Recipes for high tier armors (superstar, ardite, cobalt, ultimate, ender, etc) don't show up in Just enough items when the recipe difficulty is set to easy.
Recipes for guardian and ender armors do work if you guess the recipe. The ones made from tinker's materials do not, at least not with the vanilla-like recipe.
Higher tier weapons and tools also appear to miss a recipe.

Attempting to use a high-tech bench causes the exception below :
[armorplus.txt](https://github.com/TheDragonTeam/ArmorPlus/files/948520/armorplus.txt)

I did not have the issues above on expert difficulty.

**How can I reproduce it?**: Set recipe difficulty to easy. Try the armor recipes, try to use a high-tech bench.

**(Optional) Mod List**:
armorplus-1.10.2-8.5.4.5
jei_1.10.2-3.14.7.417
TConstruct-1.10.2-2.6.3
Mantle-1.10.2-1.1.5
thedragonlib-1.10.2-1.0.3.1
CodeChickenCore-1.10.2-2.4.0.101-universal
CodeChickenLib-1.10.2-2.5.8.255-universal

**Comment by sokratis12GR** [comment]
Working on it, a fix should be released at some point today.
