### ISSUE TITLE
Compatibility issue with Sugi Forest 

### ISSUE THREAD

**Issue by BSKCorp** [sokratis12GR/ArmorPlus#131]
**ArmorPlus Version**: 1.11.2-10.1.2.3

**TheDragonLib Version**: 1.11.2-3.1.1

**MinecraftForge Version**: 1.11.2-13.20.0.2282

**Minecraft Version**: 1.11.2

**Client or Server?**:
- [x] Client
- [x] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: N/A

**What happens / happened?**: Nether Tower spawning on top/slightly above the trees in a Sugi Forest, I have found only one instance of this happening. Not sure if they are supposed to be floating towers or not.

**How can I reproduce it?**: Install Sugi ver 1.3.1 for 1.11.2 and let world gen generate. 

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
The world generation, is totally random... but I have no clue why they spawn blocks above ground...
For now I'll label this under review until further research is done.

**Comment by BSKCorp** [comment]
Good Deal, if I come across anymore in any other biome I will let you know.

**Comment by sokratis12GR** [comment]
After reviewing and researching this, I'm sorry to say but compatibility wont happen, sorry...

**Comment by PhoenixRiver** [comment]
I presume that the reason for the problem is due to ArmorPlus not recognising the trees in this biome... since they are coded up the same as the trees in any other biome. Hmmm... maybe they are missing an oredict entry?
