### ISSUE TITLE
[1.11.2] Crash When Changing Any Weapon Registry Setting

### ISSUE THREAD

**Issue by Balketh** [sokratis12GR/ArmorPlus#132]
**ArmorPlus Version**: 1.11.2  10.1.2.3

**TheDragonLib Version**: 1.11.2  3.1.1

**MinecraftForge Version**: 13.20.0.2284

**Minecraft Version**: 1.11.2

**Client or Server?**:
- [X] Client
- [  ] Server

**Crash Report (via. [Pastebin](https://pastebin.com/))**: [Crash Report For ArmorPlus](https://pastebin.com/iA05uuYX)

**What happens / happened?**: When Minecraft reaches the end of 2/7 of loading mods with Forge, it crashes.

**How can I reproduce it?**: Go into ArmorPlus' configs with no prior config file. Go into any weapon, into its registry setting, and set any number of any set of weapons' enabled value to false. Restart the game, and it should crash. Deleting armorplus.cfg allows the game to load fully again. Removing any of the values in a weapon's registry also causes a different crash, Crash Report for that found in Pastebin [Here](https://pastebin.com/q73LjTDb)

**(Optional) Mod List**:
Forgelin
TheDragonLib
ArmorPlus
(Removed all others to ensure it wasn't a conflict. No Optifine, no Foamfix, nothing.)

**Comment by Balketh** [comment]
So, having updated to 1.11.2-10.2.0.1, I attempted to recreate the crash by loading a new profile in Twitch/Curse with only Forgelin, TheDragonLib and ArmorPlus, all up to date with Forge 2282 (the version that the latest Sponge supports, despite testing this in SSP).

Loaded game, changed registry (only registry, not effects) configs in-game for Coal and Lapis weapons all to 'false', saved, quit to menu, reloaded game, and it loaded fine, maintaining the changes. Quit to desktop, started game through Twitch/Curse, aaaand crashitycrash. [Log found here](https://pastebin.com/0ZKkdnbN).

**Comment by sokratis12GR** [comment]
Will be fixed soon, I just wasn't able to fix it in the last build because lack of time.

**Comment by sokratis12GR** [comment]
fixed in [armorplus-1.11.2-10.2.1.2](https://minecraft.curseforge.com/projects/armorplus/files/2416195)
