### ISSUE TITLE
Server crash with Furious enchant and Xia botania boss

### ISSUE THREAD

**Issue by a-frenzy** [sokratis12GR/ArmorPlus#133]
**ArmorPlus Version**: 8.5.3.4

**TheDragonLib Version**: 1.0.3.0

**MinecraftForge Version**: 12.13.3.2239

**Minecraft Version**: 1.10.2

**Client or Server?**:
- [ ] Client
- [x] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: https://pastebin.com/5KugUZtW

**What happens / happened?**: server crash in middle of xia (botania) fight

**How can I reproduce it?**: do the xia fight with furious enchant on armor botania r1.9-341

**(Optional) Mod List**: https://minecraft.curseforge.com/projects/grimdark/relations/dependencies

**Comment by sokratis12GR** [comment]
Level of the enchantment used in the battle ??

**Comment by sokratis12GR** [comment]
It looks like you used an enchantment level above 3

**Comment by a-frenzy** [comment]
player doesn't remember enchantment level

**Comment by a-frenzy** [comment]
Just had this happen again in a different modpack https://gist.github.com/frenzye/b0b8a032e953e5a3e060a042ed840aab

**Comment by a-frenzy** [comment]
seems to be when the player take damage the server crashes, player says enchantment level was 2

**Comment by sokratis12GR** [comment]
Doesn't the latest version of A+ 1.10.2 fix it?
I have released a new jar yesterday

**Comment by sokratis12GR** [comment]
@frenzye please let me know if the same issue happens when using latest 1.10.2 build of armorplus

**Comment by sokratis12GR** [comment]
Issue has been reviewed and tested, this doesn't happened... or at least Can't Reproduce
