### ISSUE TITLE
Some Achievements Not Working

### ISSUE THREAD

**Issue by Knighthawker1** [sokratis12GR/ArmorPlus#135]
**ArmorPlus Version**: armorplus-1.11.2-10.1.2.3

**TheDragonLib Version**:thedragonlib-1.11.2-3.1.1

**MinecraftForge Version**: 13.20.02282

**Minecraft Version**: 1.11.2

**Client or Server?**:
- [X] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: N/A

**What happens / happened?**: The achievements related to the emerald and obsidian sets of armor don't trigger when making a piece from the set for the first time.

**How can I reproduce it?**: All armor pieces were tried (helmet, chestplate, leggings, boots) in the high-tech bench and were successfully crafted, but the achievement did not trigger. I've also made sure that any prior achievements have been taken. 

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
Alright, after so many issues occurred for 1.11.2 ... I'm going to release a pre-change update fixing those :)

**Comment by sokratis12GR** [comment]
Fixed in [armorplus-1.11.2-10.2.0.2](https://minecraft.curseforge.com/projects/armorplus/files/2415900)
