### ISSUE TITLE
[Feature Request] Compressed lava crystal blocks

### ISSUE THREAD

**Issue by OrdinatorStouff** [sokratis12GR/ArmorPlus#136]
Suggestion:

Submitting this per our discussion on Discord

Regarding: https://github.com/TheDragonTeam/ArmorPlus/issues/120
COMPRESSED Lava Crystal blocks so that my compacting drawers use up all 3 spots and my OCD can be happy. 

Blast resistance should be at least as strong as obsidian if people want to use it as a decorative (bling-bling) building material. Also, perhaps the **compressed** infused lava crystal block can be wither-proof? Just because why not?

**Comment by sokratis12GR** [comment]
Added in [1.11.2-10.4.1.2](https://minecraft.curseforge.com/projects/armorplus/files/2431319)
