### ISSUE TITLE
[1.11.2] TIC Manual Crash

### ISSUE THREAD

**Issue by TheLimePixel** [sokratis12GR/ArmorPlus#137]
armorplus-1.11.2-10.3.0.1
thedragonlib-1.11.2-3.2.2
forge-13.20.0.2296

 When trying to hover over the Lava Infused Obsidian tools in the TIC Manual, instead of showing the stats the client simply crashes: https://pastebin.com/3x9kktyY

 I tried it 3 times and it always happened, with only the Lava Infused Obsidian stuff.

**Comment by sokratis12GR** [comment]
this is a tinkers construct bug should be redirected there: [Tinkers' Construct GitHub](https://github.com/SlimeKnights/TinkersConstruct/issues)

**Comment by TheLimePixel** [comment]
It only happens with the Lava Infused Obsidian tools though, so it must be something with your TIC integration.

**Comment by sokratis12GR** [comment]
Well, yes I register the items. materials but this is a bug with how they add materials, I mean there are some unupdated to 1.11.2 methods, mappings or fields. Because this is the exact same way of registration as in 1.10.2 and there there are no problems from my side.

**Comment by sokratis12GR** [comment]
Forget what I said. This might have been an issue with my port... Going to do a bigger investigation soon.

**Comment by TheLimePixel** [comment]
Ok?

**Comment by sokratis12GR** [comment]
Issue should be fixed, [armorplus-1.11.2-10.3.1.2](https://minecraft.curseforge.com/projects/armorplus/files/2420119).
