### ISSUE TITLE
I cant craft any armor, recipes call for a 4x4 armor workbench, mine is 3x3

### ISSUE THREAD

**Issue by LocoMinerDad** [sokratis12GR/ArmorPlus#138]
**ArmorPlus Version**: 1.11.2-10.3.0.1

**TheDragonLib Version**: 1.11.2-3.2.2

**MinecraftForge Version**: 13.20.0.2282

**Minecraft Version**: 1.11.2

**Client or Server?**: client
- [ ] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:

**What happens / happened?**: reciepes too big for armor plus work bench, recipes do not match what is on your webpage. I already tried deleting config file and reinstalled mods

**How can I reproduce it?**:

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
There are 3 tables in a+, a 3x3 (workbench), a 4x4 (high-tech bench) and a 5x5 (ulti-tech bench)
