### ISSUE TITLE
[1.11.2] Registry Issues

### ISSUE THREAD

**Issue by ghost** [sokratis12GR/ArmorPlus#140]
forge 2298 mc 1.11.2 armorplus 10.3.1.2 
[crash-2017-05-15_19.32.01-server.txt](https://github.com/TheDragonTeam/ArmorPlus/files/1001723/crash-2017-05-15_19.32.01-server.txt)
and here is the latest image from the game (freezed on crash)
![12](https://cloud.githubusercontent.com/assets/24831406/26068214/769926e8-39a5-11e7-9557-b2a536ed847d.PNG)

**Comment by ghost** [comment]
and ah, don't bother my characters body parts, i was testing Mo' Bends mod. it's buggy.

**Comment by sokratis12GR** [comment]
wait, what how... how can this happen...

**Comment by sokratis12GR** [comment]
Did you change any config values?

**Comment by ghost** [comment]
yes i did, disabled slime armor, and i disabled slime knight armor recipes. i can upload configs if u want.

**Comment by sokratis12GR** [comment]
Alright, there must be a bug with the config change, because this really shouldn't happen... Oh I found the bug... releasing another hotfix in a bit :/

**Comment by sokratis12GR** [comment]
Interesting... this bug has been here for a while... how did I just notice it ...

**Comment by sokratis12GR** [comment]
wait, O.O, ok there must be something very wrong because the code checks if the items are disabled

**Comment by sokratis12GR** [comment]
did you update the configs both to server and client ?

**Comment by ghost** [comment]
it happened on singpleplayer.

**Comment by ghost** [comment]
[armorplus.cfg.txt](https://github.com/TheDragonTeam/ArmorPlus/files/1001739/armorplus.cfg.txt)
here is my config

**Comment by sokratis12GR** [comment]
ahhh right, for a temporary fix change
`B:enableFullSlimeArmorEffect=true` to false

**Comment by ghost** [comment]
oh ok, but you will fix it in next update, right?

**Comment by sokratis12GR** [comment]
yes

**Comment by ghost** [comment]
kay thanks, i'm waiting update for 5 more mods also, i can wait :D

**Comment by sokratis12GR** [comment]
Issue should be fixed in [ armorplus-1.11.2-10.3.2.3](https://minecraft.curseforge.com/projects/armorplus/files/2420160)

**Comment by sokratis12GR** [comment]
Could you provide me the Config file as well ?

**Comment by ghost** [comment]
[armorplus.cfg.txt](https://github.com/TheDragonTeam/ArmorPlus/files/1022453/armorplus.cfg.txt)

**Comment by sokratis12GR** [comment]
I think I solved the issue, but just incase I'll do some more "indepth" testing, will push an update later today fixing this with additional changes

**Comment by sokratis12GR** [comment]
Also, how exactly did the issue occur?

**Comment by ghost** [comment]
i weared an armor from ToroQuest mod. (toro armor)

**Comment by sokratis12GR** [comment]
hmm, I'll need to test this with the mod and see. thanks for the additional info

**Comment by ghost** [comment]
thank you too

**Comment by ghost** [comment]
hey ah, it crashed again when wear the wool pants from tough as nails mod, here is the report:
[crash-2017-05-23_18.34.12-server.txt](https://github.com/TheDragonTeam/ArmorPlus/files/1022722/crash-2017-05-23_18.34.12-server.txt)

**Comment by sokratis12GR** [comment]
Found the issue, will release a fix in a few... for now enable the the armor in the config `enableSlimeArmor=true`

**Comment by ghost** [comment]
ok waiting for you. i have time :D

**Comment by sokratis12GR** [comment]
Update uploaded, issue I believe fixed. ArmorPlus 1.11.2-10.4.0.1

**Comment by ghost** [comment]
okay. u can trust me i will report if crashes again. :D btw, can i use the same config for the new version? thanks.

**Comment by sokratis12GR** [comment]
If nothing goes wrong, yes

**Comment by ghost** [comment]
you mean if game starts without any crash? :D

**Comment by ghost** [comment]
well it looks like all fine
