### ISSUE TITLE
[1.10.2] Lava Crystal Block (via Kechanism Digital Miner + Silk-Touch)

### ISSUE THREAD

**Issue by Blue-w** [sokratis12GR/ArmorPlus#142]
**ArmorPlus Version**: 1.10.2-8.6.1.2.jar

**TheDragonLib Version**:

**MinecraftForge Version**:

**Minecraft Version**: 1.10.2 (modded) forge-12.18.3.2297

**Client or Server?**:
- [ ] Client:  Twitch - Version 7.5.6345.42403
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:

**What happens / happened?**:

reminder for sokratis12GR

When a  Lava Crystal Block is only mined with a Meckanism Digital Miner with silk-touch it produces this block see http://i.imgur.com/j67HYO4.png (Metadata 2)
When it is mined with other tools it produces the correct block see http://i.imgur.com/K4YxsdH.png (Metadata 0)

Hope this helps

**How can I reproduce it?**:

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
This seems to be a bug from Mekanism' Side
