### ISSUE TITLE
Structure Lava transformed into obsidian when next to water

### ISSUE THREAD

**Issue by KewaiiGamer** [sokratis12GR/ArmorPlus#143]
**ArmorPlus Version**:
Latest
**TheDragonLib Version**:
Latest
**MinecraftForge Version**:
Latest
**Minecraft Version**:
1.10.2
**Client or Server?**:
- [X] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
Didn't crash
**What happens / happened?**:
When the super duper cool struture generation begins the structures that include lava might have their lava transformed into obsidian if generated in the same Y as water.
**How can I reproduce it?**:
Just generate a world and look for it or check [this little clip ](https://clips.twitch.tv/CoyNastyCarrotNinjaGrumpy)on twitch:
**(Optional) Mod List**:
Unrelated

**Comment by sokratis12GR** [comment]
That's actually intended, but I will see what I can do about it.

**Comment by KewaiiGamer** [comment]
Seems like a bug. Something like biome-specific generation would look more intended

**Comment by sokratis12GR** [comment]
Nope, it's intended...
