### ISSUE TITLE
Recipes Not Showing

### ISSUE THREAD

**Issue by VisualPine** [sokratis12GR/ArmorPlus#145]
**ArmorPlus Version**:
10.4.0.1
**TheDragonLib Version**:
3.2.2
**MinecraftForge Version**:
13.20.0.2295
**Minecraft Version**:
1.11.2
**Client or Server?**:
- [x ] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:

**What happens / happened?**:
JEI is not showing recipes for armor, workbenches, weapons. Clicking on it shows what enchantments you can put on the gear but not how to make it.
**How can I reproduce it?**:

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
Can you screenshot me what shows up in JEI ?
* There should be a second tab for the recipes

**Comment by VisualPine** [comment]
Here is a group of screenshots I put together. I could not effectively screenshot how when I click on things like the Lava Infuser and High-Tech Bench that it does not show any recipe. I will remove them from imgur after you have viewed them. http://imgur.com/a/Sy9AF

**Comment by sokratis12GR** [comment]
Could you provide me your configuration file? 'configs/armorplus.cfg'

**Comment by VisualPine** [comment]
I copied the config to a txt file. If you need the actual config file I will email it to you.
[Armorplus Config.txt](https://github.com/TheDragonTeam/ArmorPlus/files/1028886/Armorplus.Config.txt)

**Comment by sokratis12GR** [comment]
@VisualPine could you provide me the JEI version you were using ?

**Comment by VisualPine** [comment]
So it looks like this was the issue all along I was using an out of date JEI. I updated to the most recent version and everything works now. Sorry if I caused any stress on this issue.

**Comment by sokratis12GR** [comment]
No worries, I'm happy the issue got resolved
