### ISSUE TITLE
[Suggestion] Add Config to disable Telsla Tools/Sword

### ISSUE THREAD

**Issue by Mohron** [sokratis12GR/ArmorPlus#146]
**ArmorPlus Version**:
armorplus-1.11.2-10.4.0.1

**TheDragonLib Version**:
thedragonlib-1.11.2-3.2.2

**MinecraftForge Version**:
forge-1.11.2-13.20.0.2299-universal

**Minecraft Version**:
1.11.2

**Client or Server?**:
- [X] Client
- [X] Server

I would like to request a config to enable/disable the Tesla items added by ArmorPlus much like those you have for nearly every other thing added.

**Comment by sokratis12GR** [comment]
Will be added in 1.11.2-10.5.2.3 .
