### ISSUE TITLE
[1.11.2] Full armor set effects not working in All The Mods 2

### ISSUE THREAD

**Issue by SuperJelle** [sokratis12GR/ArmorPlus#147]
**ArmorPlus Version**: 
armorplus-1.11.2-10.4.0.1

**TheDragonLib Version**:
thedragonlib-1.11.2-3.2.2

**MinecraftForge Version**:
13.20.0.2304

**Minecraft Version**:
1.11.2

**Client or Server?**:
- [x] Client
- [x] Server
(both)

**Modpack**
All the mods 2 v0.69

**What happens / happened?**:
Full set effects doesn't work. Tested with chicken armor and lava armor, which didn't provide the stated benefit of speed and fire resistance, respectively.
Note that the effects are enabled in the relevant config file.

**How can I reproduce it?**:
Get ATM2 & equip the full set.

**Comment by sokratis12GR** [comment]
Fixed with latest versions of the 1.10.2 (1.10.2-8.7.1.2) and 1.11.2 (1.11.2-10.4.1.2), Thanks for the report!
