### ISSUE TITLE
Crash (1.12)

### ISSUE THREAD

**Issue by ghost** [sokratis12GR/ArmorPlus#148]
[crash-2017-06-14_17.16.22-client.txt](https://github.com/TheDragonTeam/ArmorPlus/files/1074874/crash-2017-06-14_17.16.22-client.txt)
sorry if i shouldn't use it :D i know forge isn't stable

**Comment by sokratis12GR** [comment]
missing forgelin :P

**Comment by sokratis12GR** [comment]
u.u the build script forgot to add it as required dependency... sorry, should be fixed

**Comment by ghost** [comment]
oh, it wasn't in required libraries, so i didn't :D
