### ISSUE TITLE
Anonymous analytics is crashing players.

### ISSUE THREAD

**Issue by IchigoGames** [sokratis12GR/ArmorPlus#150]
**ArmorPlus Version**:armorplus-1.11.2-10.5.2.3

**TheDragonLib Version**:thedragonlib-1.11.2-3.2.2

**MinecraftForge Version**:2315

**Minecraft Version**:1.11.2

**Client or Server?**:
- [x] Client yes
- [x] Server yes

**Crash Report https://pastebin.com/Z8b2buSP

**What happens / happened?**: analitcs crashing players and server with new config or old.

**How can I reproduce it?**: try to connect to a server running armorplus-1.11.2-10.5.2.3

**(Optional) Mod List**: https://minecraft.curseforge.com/projects/the-new-frontier

**Comment by IchigoGames** [comment]
i cant say this happen to me but as soon as i updated players started reporting server going down as soon as some one try to connect and other issues with Anonymous analytics crashing players the crash report posted here is from one of my modpack users let me know if you need anything more hopeing this can be fixed so i can  update tomorrow.

**Comment by Moritz30** [comment]
Alright. We will address the issue. As long as we are working on it please downgrade to armorplus-1.12-11.0.1.2-alpha. We will manually tell you once the issue is resolved

**Comment by sokratis12GR** [comment]
1.11.2-10.4.1.2*

**Comment by Moritz30** [comment]
Yeah

**Comment by sokratis12GR** [comment]
Issue should have been fixed https://minecraft.curseforge.com/projects/armorplus/files/2439663
