### ISSUE TITLE
1.12 no JEI support

### ISSUE THREAD

**Issue by Zygus42** [sokratis12GR/ArmorPlus#151]
**ArmorPlus Version**: armorplus-1.12-11.0.1.2-alpha.jar
**TheDragonLib Version**:  thedragonlib-1.12-4.0.0
                                         Forgelin-1.5.0
**MinecraftForge Version**:forge-1.12-14.21.0.2334-installer-win
**Minecraft Version**: 1.12
jei_1.12-4.6.0.63

**Client or Server?**:- [ x] Client

**What happens / happened?**:
Can't see what the recipes are for anything in your mod in JEI or in the MC Recipe book.  And they're not obvious, as 5 bits of coal or 5 blocks of coal in helmet shape do not make a Coal Helmet.

**How can I reproduce it?**:
Open inventory, select item, hit R.

**Comment by sokratis12GR** [comment]
I said that this version doesn't contain any recipes
