### ISSUE TITLE
1.12 Crash @ Load

### ISSUE THREAD

**Issue by TheXWolf** [sokratis12GR/ArmorPlus#153]
**ArmorPlus Version**: 1.12-11.0.1.2
**TheDragonLib Version**:1.12-4.0.1
**MinecraftForge Version**: 1.12-14.21.0.2362
Crash during game load at Init phase 1, crashlog:
[https://pastebin.com/9Qwaccdu](url)

**Comment by sokratis12GR** [comment]
Forge version, they changed their registry system so ArmorPlus broke, publishing a build soon that fixes this.
For now please consider using forge 1.12-14.21.0.2347

**Comment by sokratis12GR** [comment]
ArmorPlus [1.12-11.2.0.5-alpha](https://minecraft.curseforge.com/projects/armorplus/files/2441157) is released, issue should be fixed

**Comment by TheXWolf** [comment]
Thanks for the quick fix!
