### ISSUE TITLE
[1.12] Poof! crash...

### ISSUE THREAD

**Issue by Migmag789** [sokratis12GR/ArmorPlus#155]
**ArmorPlus Version**: 2.0.5-alpha

**TheDragonLib Version**: 4.0.1

**MinecraftForge Version**: 14.21.1.2187

**Minecraft Version**: 1.12

**Client or Server?**:
- [X] Client
- [ ] Server

**Crash Report** : https://pastebin.com/2WuCbnR1

**What happens / happened?**: 2/7 crash

**How can I reproduce it?**: Just update forge and use the modpack named Beyond the Minecraft.

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
Duplicate of #154

**Comment by Moritz30** [comment]
@sokratis12GR Just wanted to do that
