### ISSUE TITLE
[1.12] Wrong JEI Description

### ISSUE THREAD

**Issue by TheLimePixel** [sokratis12GR/ArmorPlus#156]
**ArmorPlus Version**: 1.12-11.3.0.7

**TheDragonLib Version**: 1.12-4.0.1

**MinecraftForge Version**: 14.21.1.2397

**Minecraft Version**: 1.12

**Client or Server?**:
- [x] Client

**What happens / happened?**:
 
![image](https://user-images.githubusercontent.com/25333164/27912671-01f50780-625e-11e7-9354-75762fad9ae3.png)

**Comment by TheLimePixel** [comment]
And another thing related, to that, the special types of recipes the mod has (the different benches and lava infuser) don't show up in JEI.

**Comment by sokratis12GR** [comment]
1.12 no longer uses Benches, and the lava infuser recipes aren't compatible with JEI integration, yet. soon I'm going to add the JEI integration to the Lava Infuser and fix this too.

**Comment by sokratis12GR** [comment]
[1.12-11.3.5.12-alpha](https://minecraft.curseforge.com/projects/armorplus/files/2452246) should have this fixed:
it includes this fix
![image](https://user-images.githubusercontent.com/12274096/28310560-858e8b9c-6bb5-11e7-9674-797a8adfb826.png)
