### ISSUE TITLE
[1.12] Debuffs applied with all complete armor sets.

### ISSUE THREAD

**Issue by Buster5265** [sokratis12GR/ArmorPlus#157]
**ArmorPlus Version**: 11.3.1.8-alpha

**TheDragonLib Version**: 4.1.0

**Forgelin Version**: 1.5.0

**MinecraftForge Version**: 14.21.1.2412 (and tested on 14.21.1.2413

**Minecraft Version**: 1.12

**(Optional) Just Enough Items (JEI) Version**: 4.7.2.76

**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: n/a

**What happens / happened?**: whenever a complete set of armor is worn (from vanilla or modded) it causes poison, blindness and slowness debuffs to be applied. Can be caused by armor of same type or mixed (i.e lava crystal head,chest,legs & vanilla iron boots). Only complete set that doesn't apply the debuffs is ultimate set from armor plus.

**How can I reproduce it?**: try on any armor set except ultimate and you'll get debuffs applied.

**(Optional) Mod List**: tested on just Forge, ArmorPlus,DragonLib, Forgelin & JEI.

**Comment by sokratis12GR** [comment]
So this happens even if you don't wear even a piece of the ultimate armor ?

**Comment by Buster5265** [comment]
yup, if I have just vanilla Iron armor set on it triggers them.

**Comment by sokratis12GR** [comment]
Okay, gonna look into it asap

**Comment by Buster5265** [comment]
no worries, I'll role back a version whilst you look in to it.
thanks for the speedy response!

**Comment by sokratis12GR** [comment]
this version [1.12-11.3.2.9-alpha](https://minecraft.curseforge.com/projects/armorplus/files/2451225) should fix this issue

**Comment by Buster5265** [comment]
it does indeed, thanks for the quick fix

**Comment by Buster5265** [comment]
got a new issue this version might have caused (?) - I've just got to the end for the first time and on the main island I have over 50 of the challenge towers generated?  I've gone to config but can't find any spawn settings for the end, just overworld.

I say this version might have caused it as prior to this (in the overworld) I'd only discovered 3 towers in approx 700 chunks explored, since the update I've just explored a 10 x 10 area and found 13 towers, which seems high?

**Comment by sokratis12GR** [comment]
:| This is me doing the biggest derp, `DEV_ENVIRONMENT = true`

**Comment by sokratis12GR** [comment]
Going to be fixed, (I was testing the Nether Towers, gonna make some more fields for checks so this doesn't happen even in dev environment, except I have specifically made it so it only works there, thanks for the report but could you open a different issue with this issue ?)

**Comment by sokratis12GR** [comment]
[ArmorPlus 1.12-11.3.4.11-alpha](https://minecraft.curseforge.com/projects/armorplus/files/2451414) Should have this issue fixed as well as the nether towers bug
