### ISSUE TITLE
[1.12] Unable to get Lava Crystals from Lava Crystal blocks & World generates Block Lava Crystal instead of Ore Lava Crystal

### ISSUE THREAD

**Issue by gsperry2011** [sokratis12GR/ArmorPlus#158]
**ArmorPlus Version**:
tested on 1.12-11.3.2.9 and 1.12-11.3.0.7

**TheDragonLib Version**:
Armor plus version 1.12-11.3.0.7 used w/ 1.12-4.0.1
Armor plus version 1.12-11.3.2.9 used w/ 1.12-4.1.0

**Forgelin Version**:
both used with Forgelin-1.5.0

**MinecraftForge Version**:
Armor plus version 1.12-11.3.0.7 used w/ 1.12-14.21.1.2387
Armor plus version 1.12-11.3.2.9 used w/ 1.12-14.21.1.2413

**Minecraft Version**:
1.12

**(Optional) Just Enough Items (JEI) Version**:
Armor plus version 1.12-11.3.0.7 used w/ 1.12-4.7.2.76
Armor plus version 1.12-11.3.2.9 used w/ 1.12-4.7.2.77

**Client or Server?**:
- [X] Client
- [X] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: It does not crash. Armor plus reads as loaded

**What happens / happened?**: From what I can tell I am having what I believe are two be two possible bugs:

1) Lava Crystal blocks spawn in my world as expected, however mining them with a diamond pickaxe results in getting a Lava Crystal block and no lava crystals. Using JEI recipes / uses I see no way to break this block into crystals so forgive me if i'm being foolish here. I have found no source of lava crystals.

2) From what i can tell from a couple youtube videos, I believe I should expect to have an armorplus workbench. I do not see this recipe in JEI but it may be related to issue #1 above.

**How can I reproduce it?**:

Install said versions and try mining lava crystal blocks. I

**(Optional) Mod List**:

armorplus-1.12-11.3.2.9-alpha.jar
AutoRegLib-1.3-13.jar
Forgelin-1.5.0.jar
Hwyla-1.8.19-B33_1.12.jar
ImmersiveEngineering-0.12-66.jar
jei_1.12-4.7.2.77.jar
Level Up! 2-1.1.1-1.12.jar
Morpheus-1.12-3.3.2.jar
Psi-r1.1-52.jar
thedragonlib-1.12-4.1.0.jar
Wawla-1.12-2.5.239.jar

**Comment by sokratis12GR** [comment]
Uh, this is definitely a bug, 
1) Block Lava Crystal or OreLavaCrystal

**Comment by sokratis12GR** [comment]
[ArmorPlus 1.12-11.3.4.11-alpha](https://minecraft.curseforge.com/projects/armorplus/files/2451414) Should have this issue fixed (new chunks only)
