### ISSUE TITLE
[1.12] Tower Generation is a bit much.

### ISSUE THREAD

**Issue by Werral** [sokratis12GR/ArmorPlus#159]
**ArmorPlus Version**: 1.12-11.3.4.11-alpha

**TheDragonLib Version**: 1.12-4.1.0

**Forgelin Version**: 1.5.0

**MinecraftForge Version**: 14.21.1.2413

**Minecraft Version**: 1.12

**(Optional) Just Enough Items (JEI) Version**: 1.12-4.7.1.69

**Client or Server?**:
- [X] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:

**What happens / happened?**: 
Towers are generated all over the overworld. Just from spawn I can see 23 netherbrick skeleton towers

**How can I reproduce it?**:
change enableTowerGen=true to false "fixes" the issue

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
This shouldn't be the case with the latest version of the mod, it should have fixed the issue. Gonna recheck once again...

**Comment by sokratis12GR** [comment]
not happening in 3.5.12 afaik
