### ISSUE TITLE
[1.11.2] No Guardian Scales dropping

### ISSUE THREAD

**Issue by Apakura** [sokratis12GR/ArmorPlus#160]
**ArmorPlus Version**: 1.11.2-10.7.0.1

**TheDragonLib Version**: 1.11.2-3.2.2

**Forgelin Version**: 1.4.2

**MinecraftForge Version**: 13.20.1.2386

**Minecraft Version**: 1.11.2

**(Optional) Just Enough Items (JEI) Version**: 1.11.2-5.4.7

**What happens / happened?**: Cannot get the Guardian Scale to drop from normal guardians or Elders.  after killing 9 Elders in the prismarine monuments I turned to autospawning them - Autospawned guardians to the point of getting 2000 wet sponges and also no drops - used a Woot spawner, Industrial Forecoming autospawner and Soul Shards the old way to autospawn

**How can I reproduce it?**:

**(Optional) Mod List**:
ActuallyAdditions-1.11.2-r110.jar
Advanced Solar Panels-4.1.0.jar
AppleCore-mc1.11.2-2.2.0.jar
AppleSkin-mc1.11-1.0.7.jar
applied-llamagistics-1.11.2-rv5-alpha-5.jar
armorplus-1.11.2-10.7.0.1.jar
Aroma1997Core-1.11.2-1.2.0.0.jar
Aroma1997s-Dimensional-World-1.11.2-1.3.0.0.jar
atg-1.11.2-2.1.7.jar
AutoPickup-1.11.2-2.4.3.jar
AutoRegLib-1.1-4.jar
baublelicious-1.11-1.3BETA.jar
Baubles-1.11-1.4.5.jar
bdlib-1.13.2.7-mc1.11.2.jar
BetterBuildersWands-1.11-0.11.1.239+9162f74.jar
BetterFps-1.4.5.jar
BiomesOPlenty-1.11.2-6.2.0.2267-universal.jar
BloodArsenal-1.11.2-2.1.0-19.jar
BloodMagic-1.11-2.1.11-80.jar
Botania r1.9-345.jar
BrandonsCore-1.11.2-2.2.1.115-universal.jar
ChickenChunks-1.11.2-2.3.1.68-universal.jar
Chisel-MC1.11.2-0.0.13.21.jar
CodeChickenLib-1.11.2-3.0.0.284-universal.jar
CoFHCore-1.11.2-4.2.6.14-universal.jar
CommonCapabilities-1.11.2-1.3.3.jar
CompactSolars-1.11.2-5.0.12.333-universal.jar
compatlayer-1.11.2-0.2.9.jar
computality-1.11.2-1.82.jar
Controlling-2.0.5.jar
CosmeticArmorReworked-1.11.2-v1a.jar
CraftingTweaks_1.11.2-7.1.9.jar
CraftTweaker-1.11.2-3.0.26.jar
CTM-MC1.11.2-0.2.0.8.jar
Cyclic-1.11.2-1.5.9.jar
CyclopsCore-1.11.2-0.10.6.jar
Draconic-Evolution-1.11.2-2.2.1.248-universal.jar
ElevatorMod-1.11.2-1.3.2.jar
embers-0.220.jar
EnderCompass-1.11-1.2.5.3.jar
EnderStorage-1.11.2-2.3.1.116-universal.jar
endertanks-1.11.0-1.5.5.jar
extrautils2-1.11.2-1.5.jar
ExtremeReactors-1.11.2-0.4.5.30.jar
FastLeafDecay-v12.jar
FluxNetworks-1.11.2-2.0.0.jar
foamfix-0.7.1-law.jar
forestry_1.11.2-5.3.4.133.jar
Forgelin-1.4.2 (1).jar
FTBLib-1.1x-3.6.5.jar
Futurepack-1.11.2-25.2.104.jar
generators-0.9.20.5-mc1.11.2.jar
geneticsreborn-mc1.11.2-v1.06.jar
gravestone-1.7.4.jar
Guide-API-1.11.2-2.1.1-52.jar
HammerCore_1.11.2-1.8.9.jar
Hwyla-1.8.17-B31_1.11.jar
ic2
ImmersiveEngineering-0.11-63.jar
immersivepetroleum-1.11.2-1.0.7.jar
ImprovedHoes-1.11.2-1.2.2.jar
industrialcraft-2-2.7.74-ex111.jar
industrialforegoing-1.11.2-0.3-17.jar
IntegratedDynamics-1.11.2-0.7.6.jar
IntegratedTunnels-1.11.2-1.2.4.jar
InventoryTweaks-1.63+dev.92.jar
ironchest-1.11.2-7.0.25.815.jar
jei_1.11.2-4.5.0.292.jar
journeymap-1.11.2-5.4.7.jar
JustEnoughResources-1.11.2-0.6.6.12.jar
k4lib-1.11.2-2.1.76-universal.jar
LargeVeins-1.11-1.0.0.jar
literalascension-1.11.2-1.0.2.2.jar
llibrary-1.7.6-1.11.2.jar
Mantle-1.11.2-1.2.0.26.jar
mcjtylib-1.1x-2.4.3.jar
MCMultiPart-2.0.2.jar
Mekanism-1.11.2-9.3.2.309.jar
MekanismGenerators-1.11.2-9.3.2.309.jar
MekanismTools-1.11.2-9.3.2.309.jar
MobGrindingUtils-0.2.0.jar
MouseTweaks-2.8-mc1.11.2.jar
multistorage-1.11.0-1.3.7b.jar
mysticalagriculture[1.11.2]-1.5.7a.jar
NetherEx-1.11.2-1.1.4.5.jar
NetherPortalFix_1.11-4.3.1.jar
NoMobSpawningOnTrees-1.2.0-mc1.11.2.jar
NoMoreRecipeConflict-0.8(1.11).jar
notenoughwands-1.1x-1.5.5.jar
NuclearCraft-2.3a--1.11.2.jar
omlib-1.11.2-3.0.0-114.jar
OpenGlider-1.11.2-1.0.0.jar
openmodularturrets-1.10.2-3.0.0-189.jar
OreExcavation-1.3.99.jar
OreExcavationIntegration-1.11.2_2.0.jar
plustic-5.2.0.0.jar
Quark-r1.2-93.jar
rangedpumps-0.4.jar
ReAuth-3.5.0.jar
RebornCore-1.11.2-2.16.1.115-universal.jar
RedstoneArsenal-1.11.2-2.2.5.9-universal.jar
RefinedRelocation-mc1.11.2-3.1.14.jar
refinedstorage-1.4.20.jar
Reliquary-1.11.2-1.3.3.653.jar
rftools-1.1x-6.10.jar
roots-2-0.025.jar
ropebridge-1.11.2-2.0.6.jar
ServerInfoViewer-1.11.2-2.0.9-universal.jar
ShadowMC-1.11.2-3.7.5.jar
shetiphiancore-1.11.0-3.4.6.jar
simplegenerators-1.11.2-0.11.0a.jar
simplemagnet-1.11.2-1.2.4.jar
SimpleQuarry_1.11.2-1.0.3.jar
SimpleTeleporters-1.11.2-2.1.3.jar
SimplyConveyors-3.1.1d.jar
Snad-1.11.2-1.7.03.26a.jar
SolarFluxReborn_1.11.2-2.21r.jar
SonarCore-1.11.2-4.0.0.jar
SoulShards-TOW-1.11-2.6.6-47.jar
StevesCarts-1.11.2-2.3.0.22.jar
TConstruct-1.11.2-2.7.0.26.jar
TechReborn-1.11.2-2.3.3.181-universal.jar
Tesla-1.11-1.3.0.52.jar
tesla-core-lib-1.11.2-0.7.3.jar
thedragonlib-1.11.2-3.2.2 (1).jar
ThermalDynamics-1.11.2-2.2.5.12-universal.jar
ThermalExpansion-1.11.2-5.2.5.20-universal.jar
ThermalFoundation-1.11.2-2.2.4.15-universal.jar
Tinkers' Addons-1.11.2-1.0.6.jar
TinkerToolLeveling-1.11.2-1.0.1.jar
tinker_io-1.11.2-release 2.5.2c.jar
torchmaster_1.11.2-1.4.0.45.jar
TrashSlot_1.11.2-7.4.7.jar
UniDict-1.11.2-1.1b.jar
usefulnullifiers-1.3.5.jar
valkyrielib-1.11.2-0.11.0c.jar
WailaHarvestability-mc1.11-1.1.10.jar
WanionLib-1.11.2-1.1.jar
Wither Skeleton Tweaks-1.11.2-2.2.2.jar
woot-1.11.2-0.3.0.jar
WorldEdit CUI Forge Edition 2-2.1.1-mf-1.11.2-13.20.0.2228.jar
worldedit-forge-mc1.11-6.1.6-dist.jar
xnet-1.3.2.jar
Xtones-1.11-1.0.1-3.jar
YABBA-1.11.2-0.5.1.jar
yarn-1.11.2-2.0.1.jar
zerocore-1.11.2-0.1.0.6.jar
[1.11.2] SecurityCraft v1.8.2.2.jar

**Comment by sokratis12GR** [comment]
Just released a version, [1.11.2-10.7.1.2] should fix this issue, thanks for the report! https://minecraft.curseforge.com/projects/armorplus/files/2452464
(done some needed optimizations with the update too!)
