### ISSUE TITLE
[1.12] Config Issues

### ISSUE THREAD

**Issue by Berths** [sokratis12GR/ArmorPlus#161]
**ArmorPlus Version**:1.11.2

**TheDragonLib Version**:3.2.2

**Forgelin Version**:

**MinecraftForge Version**:13.20..1.2414

**Minecraft Version**:1.11.2

**(Optional) Just Enough Items (JEI) Version**:4.5.0.294

**Client or Server?**: server
- [ ] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:

**What happens / happened?**: When I try to configure the stats of armor either it won't apply or only me the can see it, other just see defaults one.

**How can I reproduce it?**:

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
Thanks for the report, 
did you try changing the values via the ingame config? (If so, it never worked and won't work that way, it's just meant for easier visibility of changes made inside the config file configs/armorplus.cfg).

**Comment by sokratis12GR** [comment]
Closing this issue, until more information is provided.
