### ISSUE TITLE
[1.12] Crash with Latest Tinkers' Construct

### ISSUE THREAD

**Issue by ghost** [sokratis12GR/ArmorPlus#162]
**ArmorPlus Version**: 11.3.6.13-alpha

**TheDragonLib Version**: 4.1.0

**Forgelin Version**: 1.5.1

**MinecraftForge Version**: 14.21.1.2426

**Minecraft Version**: 1.12

**(Optional) Just Enough Items (JEI) Version**: 4.7.2.77

**Client or Server?**:
- [X] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: https://pastebin.com/cvkiuiBG

**What happens / happened?**: Crash from launcher (before Minecraft even starts)

**How can I reproduce it?**: Launch with Armor Plus 11.3.6.13-alpha and Tinkers' Construct 2.7.2.15

**Comment by sokratis12GR** [comment]
Confirmed bug, going to be fixed within the next 2 weeks, but for now please consider downgrading either tinkers or armorplus to the version before the intergraton (wiip) with tinkers. Thanks for the report!

**Comment by MokahTGS** [comment]
Hey, just adding my log to see if it helps:  https://pastebin.com/A7tXNZyP

**Comment by Fundryi** [comment]
On what version did you add Tinker's support? I would like to downgrade to that version.
Also, you should add some kind of option in the config so people can disable/enable if they want mod support like tinkers, So if there is an error/conflict with an other mod you can just disable it and still play on the same version :)

**Comment by sokratis12GR** [comment]
Alrighty, ArmorPlus 1.12-11.5.0.15-alpha (same for 11.4.0.14-alpha) should have fixed this issue, also added a config value to enable/disable the integration, thanks for the report!
