### ISSUE TITLE
[1.12] Wrong block generated for Ore Gen

### ISSUE THREAD

**Issue by kingred126** [sokratis12GR/ArmorPlus#164]
**ArmorPlus Version**: 1.12

**TheDragonLib Version**:.1.12

**Forgelin Version**:1.5.0

**MinecraftForge Version**:1.12.2443

**Minecraft Version**:1.12

**(Optional) Just Enough Items (JEI) Version**:

https://ibb.co/mXcZMa

https://ibb.co/mc4QSF

Hi friends of the dragonteam

Look in my world only the lava block is generated
No lava crystal ore is generated

esta es la lista de mods 

https://ibb.co/hDOiga

**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:

**What happens / happened?**:

**How can I reproduce it?**:

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
Hello, thanks for the report.
Please complete the given information, with full version names, and place from where the mod was downloaded.

**Comment by sokratis12GR** [comment]
Uhm, did you try loading new chunks ?
Because its should produce the ore variants:
- https://github.com/TheDragonTeam/ArmorPlus/blob/1.12/src/main/java/net/thedragonteam/armorplus/worldgen/OreGen.java#L35

**Comment by sokratis12GR** [comment]
Closing this issue, until correct information is provided.
