### ISSUE TITLE
super_star_(sword|bow|axe) missing?

### ISSUE THREAD

**Issue by shelbyKiraM** [sokratis12GR/ArmorPlus#166]
**ArmorPlus Version**: 10.7.2.3

**TheDragonLib Version**: 3.2.2

**Forgelin Version**: 1.4.2

**MinecraftForge Version**: 2454

**Minecraft Version**: 1.11.2

**(Optional) Just Enough Items (JEI) Version**: 4.5.1.296

**Client or Server?**:
- [ ] Client
- [ ] Server
- [x] Both

**Crash Report (via. [Pastebin](http://pastebin.com/))**: I put it [HERE](https://pastebin.com/XcGWWRJp)

**What happens / happened?**:
When connecting to the server, it gives these errors (every time) and says, in the client: `Fatally missing blocks and items`

**How can I reproduce it?**:
Fresh install of above versions and… every time.

**(Optional) Mod List**:
AbyssalCraft-1.11.2-1.9.4-pre-4.jar, AbyssalCraft Integration-1.11.2-1.5.0 (1).jar, ActuallyAdditions-1.11.2-r110.jar, AdditionalBanners-1.11.2-1.4.0.32.jar, AkashicTome-1.1-7.jar, Animalium-0.2.0.jar, AoV-1.11.2-0.2.5.jar, Aquaculture-1.11.2-1.5.1.2.jar, AutoRegLib-1.1-4 (2).jar, Baubles-1.11-1.4.6.jar, BetterFoliage-MC1.11.2-2.1.8.jar, BetterFps-1.4.5.jar, BiblioCraft[v2.3.3][MC1.11.2].jar, BiblioWoods[BiomesOPlenty][v2.0][MC1.11.2].jar, BiblioWoods[Forestry][v2.0][MC1.11.2].jar, BiblioWoods[Natura][v2.0][MC1.11.2].jar, BiomesOPlenty-1.11.2-6.2.0.2267-universal (3).jar, Botania r1.9-345.jar, Ceramics-1.11.2-1.2.3b.jar, Chameleon-1.11.2-3.1.0.jar, Clumps-2.0.0.jar, CoFHCore-1.11.2-4.2.7.15-universal.jar, CodeChickenLib-1.11.2-3.0.0.284-universal.jar, CookingForBlockheads_1.11.2-5.3.24.jar, CraftStudioAPI-universal-0.3.0.86-mc1.11.2-beta.jar, CraftTweaker-1.11.2-3.0.26.jar, CraftingTweaks_1.11.2-7.1.9.jar, DoomlikeDungeons-1.9.3-MC1.11.2.jar, EnchantingTable-1.11-1.1.2.jar, Forgelin-1.4.2.jar, HardcoreORE-1.11.2-0.0.30.jar, Hwyla-1.8.15-B29_1.11.jar, ImmersiveEngineering-0.11-63 (1).jar, Improved Villagers-2.1.2.jar, LargeVeins-1.11-1.0.0.jar, LycanitesMobsComplete 1.16.2.3 [1.11.2].jar, Mantle-1.11.2-1.2.0.26 (1).jar, Mekanism-1.11.2-9.3.4-fix.jar, MekanismGenerators-1.11.2-9.3.4-fix.jar, MekanismTools-1.11.2-9.3.4-fix.jar, NewAgeBeeBreeding-1.11.2-1.0.1.jar, Pam's Get all the Seeds! 1.11a (1).jar, Pam's HarvestCraft 1.11.2h.jar, Quark-r1.2-93b.jar, RoguelikeDungeons-1.11.2-1.6.6.jar, Ruins-1.11.2.zip, ShadowMC-1.11.2-3.7.5.jar, StorageDrawers-1.11.2-4.2.10.jar, StorageTech 1.0.jar, TConstruct-1.11.2-2.7.1.34.jar, TamModized-1.11.2-0.9.2.jar, ThermalExpansion-1.11.2-5.2.6.22-universal.jar, ThermalFoundation-1.11.2-2.2.5.16-universal.jar, TinkerToolLeveling-1.11.2-1.0.1.jar, Tinkers' Addons-1.11.2-1.0.6.jar, TinkersComplement-1.11.2-0.1.3.jar, ToughAsNails-1.11.2-2.1.0.63-universal.jar, TrustCircle-1.11.2-r3 (1).jar, Vampirism-1.11.2-1.2.3.jar, VoidCraft-1.11.2-0.19.6.jar, VoidFog-1.0.2.jar, WailaHarvestability-mc1.11-1.1.10.jar, Wawla-1.11.2-2.4.0.233.jar, [1.11.2]AngryBees-1.0 (1).jar, aether_legacy-1.11.2-1.0.1.jar, animania-1.11.2-1.2.2.jar, applied-llamagistics-1.11.2-rv5-beta-5.jar, astikoor-11.0.3.jar, astralsorcery-1.4.5.jar, base-1.11.2-2.1.0.jar, compatlayer-1.11.2-0.2.9.jar, extrautils2-1.11.2-1.5.2.jar, forestry_1.11.2-5.3.4.158.jar, immersivepetroleum-1.11.2-1.1.3.jar, jei_1.11.2-4.5.1.296.jar, journeymap-1.11.2-5.5.0b1.jar, mcjtylib-1.1x-2.4.3.jar, natura-1.11.2-4.2.0.28.jar, plustic-5.2.1.2.jar, refinedstorage-1.4.20.jar, rftools-1.1x-6.12.jar, rftoolsctrl-1.1x-1.6.8.jar, rftoolsdim-1.1x-5.04.jar, shetiphiancore-1.11.0-3.4.6.jar, slurp-1.11.2-0.2.jar, terraqueous-1.11.0-1.3.14.jar, thedragonlib-1.11.2-3.2.2.jar, tinker_io-1.11.2-release 2.5.2d.jar

**Comment by sokratis12GR** [comment]
You seem to be using a wrong config, please change the values of the
registry for the super star weapons inside config/armorplus.cfg to enable
them, and try again. Let me know the result

**Comment by shelbyKiraM** [comment]
I deleted the config folder on client and server… I don't get the error anymore but I always timeout on connecting.
