### ISSUE TITLE
[1.12.1] Poof! crashes.

### ISSUE THREAD

**Issue by Migmag789** [sokratis12GR/ArmorPlus#167]
**ArmorPlus Version**: armorplus-1.12-11.5.1.16-alpha

**TheDragonLib Version**: thedragonlib-1.12.1-5.0.0

**Forgelin Version**: Forgelin-1.5.1

**MinecraftForge Version**: forge-14.22.0.2462

**Minecraft Version**: 1.12.1

**(Optional) Just Enough Items (JEI) Version**: jei_1.12.1-4.7.7.90

**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: https://pastebin.com/6zFCniWt

**What happens / happened?**: 2/7 loading finished, and... poof! crashes.

**How can I reproduce it?**: With the modpack Beyond the Minecraft (just update mods, adding some mods...)

**(Optional) Mod List**: 200 mods ? Not easy... x)

**Comment by sokratis12GR** [comment]
Hello, thanks for the report! Could you post the config used in the modpack ? `config/armorplus.cfg`

**Comment by Migmag789** [comment]
Okay ;)
[armorplus.zip](https://github.com/TheDragonTeam/ArmorPlus/files/1253808/armorplus.zip)

**Comment by sokratis12GR** [comment]
Working on a fix rn, should be fixed in 1.12.1-11.6.0.17-alpha once its done, thanks for the report!

**Comment by Migmag789** [comment]
Okay ;)

**Comment by sokratis12GR** [comment]
Should be fixed in [1.12.1-11.6.0.17-alpha](https://minecraft.curseforge.com/projects/armorplus/files/2469372) :)

**Comment by Migmag789** [comment]
Ok thank you ^^ I'm going to wait the update to update my modpack, because ArmorPlus is one of the most important tools / armor mods, If someone lose his armor... x)
