### ISSUE TITLE
[Feedback/Suggestion] Lava Infuser Recipe Configuration

### ISSUE THREAD

**Issue by Boolyman** [sokratis12GR/ArmorPlus#168]
I am really loving the new additions to Armor Plus in 1.12+   Especially the Lava Infuser.  I am just a bit disappointed that such an awesome machine is only really used for one thing.  I would love to make this machine a bit more incorporated into my upcoming pack.  Would it be too troublesome for you to include a way to for modpack devs to add recipes to the Lava Infuser via the config file.

Something like:
`ore:logWood, 50mb, minecraft:charcoal`2,
This would create a recipe that allows you to put logs into the lava infuser, and it will infuse 50mb of lava from the internal tank into the log, to create 2 pieces of charcoal.  Of course this is just one example.

Thanks for any consideration you might give this idea!

**Comment by sokratis12GR** [comment]
Thats a really nice idea, but not sure how I would be able to do it... I mean I could make it use CT but otherwise I would need help on that

**Comment by Boolyman** [comment]
Even using Craftweaker integration would be fine.

lavainfuser.addRecipe(<minecraft:charcoal> * 2, <ore:logWood>, 50);

**Comment by sokratis12GR** [comment]
Added in [1.12.2-11.8.0.26-beta](https://minecraft.curseforge.com/projects/armorplus/files/2501670)
