### ISSUE TITLE
[1.9] Chainmail overwrites vanilla shears recipe

### ISSUE THREAD

**Issue by kwpugh** [sokratis12GR/ArmorPlus#17]
Hi,

You appear to have a shapeless recipe for the chain mail and it is overwriting the vanilla shears recipe.  You you change that please?

Thank you

**Comment by sokratis12GR** [comment]
It doesn't actually overwrite it you to create the chanimail you need to craft it like you craft sticks, if you try to try to craft the shears their recipes work

**Comment by kwpugh** [comment]
this is what I get when I try that

![pic1](https://cloud.githubusercontent.com/assets/8809210/15440216/d55ad60e-1e99-11e6-8224-406860767429.jpg)

![pic2](https://cloud.githubusercontent.com/assets/8809210/15440222/dc4e4ef0-1e99-11e6-917d-ddef416b2172.jpg)

**Comment by sokratis12GR** [comment]
Hmm Interesting. Does it do the same in vanilla crafting table ?

**Comment by kwpugh** [comment]
that is a vanilla crafting table, with the crafting tweaks mod, I will try without that mod

**Comment by kwpugh** [comment]
is your chainmail a shaped or shapeless recipe?   Any combination of two iron ingots makes the chainmail.

**Comment by sokratis12GR** [comment]
it is shapeless, well It seems that 2 iron ingots wont do it. I will change the recipe from 2 iron ingot to 4 and give more chainmail

**Comment by kwpugh** [comment]
Here is with a vanilla table

![pic1](https://cloud.githubusercontent.com/assets/8809210/15440537/89e539f6-1e9b-11e6-99cb-08eb3fc9721f.jpg)

![pic2](https://cloud.githubusercontent.com/assets/8809210/15440542/8f84f05e-1e9b-11e6-9e40-05f5d178649b.jpg)

Perhaps you could make it shaped.

**Comment by sokratis12GR** [comment]
Ok, I have an idea 4 iron ingots 1 top, 1 left, 1 right, 1 bottom.

**Comment by kwpugh** [comment]
I think another mod is using that, let me check really quick.

**Comment by kwpugh** [comment]
For people using AdvancedGenerators mod by blew, you would be overwriting the "iron fame" recipe.

**Comment by kwpugh** [comment]
How about this?

![pic3](https://cloud.githubusercontent.com/assets/8809210/15440795/fdbde1a6-1e9c-11e6-8c3a-b43f1689eb66.jpg)

**Comment by sokratis12GR** [comment]
yeah, great idea and will be perfect. Because a full Chainmail set costs 24 chainmail with this recipe you get 12 chainmail on craft. Thank you for reporting this issue it will be fixed in 1.13.1-1.9

**Comment by kwpugh** [comment]
Thank you are addressing.   Have a great day!

**Comment by kwpugh** [comment]
Uhh oh, we have trouble.  Everytime I click into a table, there are chainmail boot.   If I remove them and exit, click in again, more chainmail.

I tried breaking the table and replacing, same results.

![pic1](https://cloud.githubusercontent.com/assets/8809210/15441929/708dea36-1ea3-11e6-8b12-4acf157148e3.jpg)

**Comment by kwpugh** [comment]
the new recipe works though.

**Comment by sokratis12GR** [comment]
Ok thats more strange lol.

**Comment by sokratis12GR** [comment]
Fixed it 1.13.2 forgot to change the recipe , it had a "blank" recipe

**Comment by kwpugh** [comment]
Everything seems to be working fine with the latest release.

Question: How does one harvest the lava crystal for making the armor?

**Comment by kwpugh** [comment]
Never mind, wrong mod.
