### ISSUE TITLE
What gamemode is the default and can we change to easy/expert?

### ISSUE THREAD

**Issue by mahilo3550** [sokratis12GR/ArmorPlus#170]
**ArmorPlus Version**:
11.5.1.16
**TheDragonLib Version**:
4.1.0
**Forgelin Version**:
1.5.1
**MinecraftForge Version**:
14.21.1.2443
**Minecraft Version**:
1.12
**(Optional) Just Enough Items (JEI) Version**:
4.7.8.93
**Client or Server?**:
- [x] Client
- [ ] Server

Just wondering if we can enter which game mode (easy or expert) into the config where it says "gamemodes {}"

**Comment by sokratis12GR** [comment]
Not possible in 1.12 (maybe soon, but not very likely)

**Comment by sokratis12GR** [comment]
Oops, sorry forgot to mention, default is Expert
