### ISSUE TITLE
High-Tech Bench Crashes to desktop

### ISSUE THREAD

**Issue by SplitInfinitive** [sokratis12GR/ArmorPlus#171]
**ArmorPlus Version**: 1.10.2-8.7.1.2

**TheDragonLib Version**: 1.10.2-1.0.3.1

**Forgelin Version**: n/a

**MinecraftForge Version**: 12.18.3.2316

**Minecraft Version**: 1.10.2

**(Optional) Just Enough Items (JEI) Version**: 1.10.2-3.14.7.420

**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: https://pastebin.com/Q6a5EvmD

**What happens / happened?**: Right Clicking High-Tech Bench crashes to desktop after opening the UI

**How can I reproduce it?**: Right Click on a High-Tech Bench

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
Looks like this isn't an ArmorPlus issue, its seems like it is caused by eydamos backpacks or something
![image](https://user-images.githubusercontent.com/12274096/30524780-a219a6e8-9c02-11e7-9499-bf855231e500.png)

**Comment by SplitInfinitive** [comment]
noted.  When I tried without that mod, it seems to have been fixed.  thanks!
