### ISSUE TITLE
item name request.

### ISSUE THREAD

**Issue by mattrix444** [sokratis12GR/ArmorPlus#172]
hi sorry if this is in the totally wrong place. i would like to modify the drops of the enderdragon in "woot" as in the factory the dragon scale is not set to default. i was just wondering if i can find the item id/meta for the scale?

**Comment by sokratis12GR** [comment]
Minecraft Version ?

**Comment by sokratis12GR** [comment]
1.11.2+ should be "armorplus:material" metadata of 3
