### ISSUE TITLE
[1.12] Crafting Bug

### ISSUE THREAD

**Issue by ben3536** [sokratis12GR/ArmorPlus#173]
**ArmorPlus Version**:
1.12.-11.5.16-alpha
**TheDragonLib Version**:
1.12.0-4.1.0
**Forgelin Version**:
1.5.1
**MinecraftForge Version**:
1.12
**Minecraft Version**:
1.12
**(Optional) Just Enough Items (JEI) Version**:

**Client or Server?**:
- [ ] Client team extreme
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:

**What happens / happened?**:
I cannot craft compressed obsidian I placed 9 blocks of obsidian into crafting table but i still couldn't craft compressed obsidian.I have recipe conflict installed
**How can I reproduce it?**:

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
Hello, would you be able to provide more specific version details?
ie. in ArmorPlus Versin: instead of 1.12.0 to "1.12.x-x-x-x-x-beta/alpha"

**Comment by ben3536** [comment]
It's version 1.12-11.5.1.16-alpha

**Comment by sokratis12GR** [comment]
have you tried any latter versions ? **1.12.2** is the *recommended*, mc version for this mod.
Try with [ArmorPlus 1.12.2-11.7.0.22-beta](https://minecraft.curseforge.com/projects/armorplus/files/2489161).
It should have all the recipes needed.

**Comment by ben3536** [comment]
But the problem is that I've installed other mods that only work on 1.12 so I rly sonny know what to do. Because if I get armor plus for Minecraft 1.12.2 it would mean I'll have to delete all my other mods

**Comment by ben3536** [comment]
I rly don't know what to do*

**Comment by sokratis12GR** [comment]
:/ I can't really help, Im sorry but we can only support 1.12.2 versions  of A+... You could try to add the recipe using CraftTweaker. Hope you find a solution

**Comment by ben3536** [comment]
oh ok thanks for the help. the mods amazing btw ^^ keep up the good work
