### ISSUE TITLE
Minecraft crashing on start-up & others.

### ISSUE THREAD

**Issue by VoltenX** [sokratis12GR/ArmorPlus#176]
**ArmorPlus Version**:
11.5.1.16-alpha.jar
**TheDragonLib Version**:
1.12-4.1.0
**Forgelin Version**:
Forgelin - 1.5.1
**MinecraftForge Version**:
1.12-forge1.12-14.21.1.2443
**Minecraft Version**:
Minecraft 1.12
**(Optional) Just Enough Items (JEI) Version**:
Didn't keep track, downloaded on 9minecraft & the name doesn't state the version(was downloaded months ago.)
**Client or Server?**:
- [dis] Client
- [ ] Server
(I dont know what you mean by client or server but because of the situation, probably client.)

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
No crash report, only game output. I will appreciate every help I can get.
https://cdn.discordapp.com/attachments/285715429610225664/380006059210702858/unknown.png
(Picture of minecraft launcher after crash)
Have tried this but my friend says he doesn't have a crash-report folder.
http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/mods-discussion/1393774-crash-reports-101

**What happens / happened?**:
(For my friend who knows nothing related to modding on Minecraft)
Minecraft crashes on startup.
The timeline goes like this: 
Downloaded whole modlist as seen below except for NatureCompass, malisiscore/door & Xaero's Minimap then my friend tried to reinstall TheDragonLib, Shadowfacts Forgelin and ShadowMC(using UnderwaterUtilities) & ArmorPlus, still didn't work. 
Removing ArmorPlus worked, then redownloaded it as aforementioned & put it in. It worked. That's all what I remembered on the situation but then whenever loading/creating a world becomes stuck on Loading Terrain/World/whatchamacallit so my friend redownloaded my whole modlist again (this time with the mods stated above) which put it into the present state.
Removing ArmorPlus still crashes Minecraft with no crashlogs(only Game Output.)

**How can I reproduce it?**:
I have no idea, crashes on start up.
**(Optional) Mod List**:
https://cdn.discordapp.com/attachments/285715429610225664/380001003019304960/pasdpad.png
(dont mind the file name)

(Excuse me for making this look messy and I tried to organize them, just wanted to give every information I can and I haven't played Minecraft in a long time.)

**Comment by VoltenX** [comment]
If I dont reply within an hour, please contact me through Steam & comment on my friend's profile; http://steamcommunity.com/id/quacktheduck

**Comment by UpcraftLP** [comment]
That screenshot doesn't show anything related to a crash, please provide the full fml log. It's usually located in `<mc dir>/logs/fml-client-latest.log`

**Comment by VoltenX** [comment]
Will check.

**Comment by VoltenX** [comment]
Will this help?
https://pastebin.com/YVWXPvz0

**Comment by sokratis12GR** [comment]
Hey, thanks for reporting the issue, but it seems like its something else that causes the issues to happen. Probably Optifine having some conficts/inabillity to access some clases (Mentioning optifine because of its spam log, but it may be any mod that interferes somehow with OptiFine).
I'm sorry but I can't help, this isn't related to ArmorPlus. The mod never used ASM and will never do.
It may be worth reporting the issue to Optifine itself. https://github.com/sp614x/optifine/issues

**Comment by VoltenX** [comment]
Thanks for your help!
