### ISSUE TITLE
[1.12.2] Piece Effect Configuration Malfunctioning

### ISSUE THREAD

**Issue by Arcanatias** [sokratis12GR/ArmorPlus#178]
**ArmorPlus Version**: armorplus-1.12.2-11.8.0.26-beta

**TheDragonLib Version**: thedragonlib-1.12.2-5.2.0

**Forgelin Version**: Forgelin-1.5.1

**MinecraftForge Version**: forge-14.23.0.2531

**Minecraft Version**: 1.12.2

**(Optional) Just Enough Items (JEI) Version**: jei_1.12.2-4.8.0.114

**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:

**What happens / happened?**: I am trying to change the configs of some of the earlier obtained Armorplus armors to only require 1 piece to get the desired effect such as the coal armor. I changed the full coal armor effect to false and the tooltip in game reflects that saying "Equip a piece". I also changed the enable/disable effect for each individual piece to true but am getting no results in game. I also tried it with the other armor sets I was wanting to change but getting the same results. So I'm not sure if this is considered a bug or maybe just hasn't been implemented yet or won't be for the 1.12.2 version of Armorplus. I remember being able to change the armor effects to only require 1 piece to be worn in 1.10.2 versions of Armorplus via a similar method I am describing but maybe the configs have changed. I plan to keep the mod installed as I am not experiencing any actual bugs or crashes and the effects do still work with the default configs and while wearing a full set of the same type of armor. Any help would be much appreciated, maybe I am just overlooking something simple. 

**How can I reproduce it?**: Change the enable/disable effect for each piece of armor and turning off the full armor effect in the Armorplus configs and getting no results in game.

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
Alrighty, it has to do with the very important bug fix check with full set armor, managed to reproduce this bug shrotly before release, I thought I fixed it but I'd it only tested with the Lava Armor set. goint to try and fix this issue asap. Thanks for your report!

**Comment by sokratis12GR** [comment]
Could you also provide me your config file ?
- Which Armors did you change
- Tinkers' Armors have only full set effects

**Comment by Arcanatias** [comment]
Sorry was having issues uploading the whole config file but I can give you an example of what I changed. I just copy pasted a small section straight from the config and everything else is default. I thought changing the enable/disable effect (default false) would add it to each individual piece and enable/disable the full armor effect (default true) would change the tooltip to reflect that. I did look for the Tinker armors in the config but I just assumed there wasn't an option to change them. I just wanted to change the less expensive ones like Coal or Redstone armor as an example.

# Enable/Disable the Coal Effect (Boots, Leggings, Chestplate, Helmet)
            B:enableCoalEffect <
                true
                true
                true
                true
             >

            # Enable/Disable the Potion Effect the Coal Weapons will have
            B:enableCoalWeaponsEffects=true

            # Enable/Disable the Full Coal Armor Effect
            B:enableFullCoalArmorEffect=false

**Comment by Arcanatias** [comment]
![2017-11-23_13 47 37](https://user-images.githubusercontent.com/20810007/33187310-966db9b4-d056-11e7-98c8-b26dedd9e14e.png)

This is a coal helmet with the config changes I posted above. The tooltip says "Equip a piece" but there is no potion effect for wearing it.

**Comment by sokratis12GR** [comment]
Yeah, it is 100% a bug, give me some time to investigate where does this come from

**Comment by sokratis12GR** [comment]
Ugh, seems like this issue is into how I confured and created the functionallity of the mod.
Will need to rewrite a big portion of the abilities and effects for each armors individually, and basically the entire system.
Will try within the next week to fix this issue and many more **critical** bugs for mod's functionallity
Extra Note: Additionally I'll need to rewrite the configuration system to use Forge's one

**Comment by sokratis12GR** [comment]
Should be fixed in [1.12.2-11.8.1.27-beta](https://minecraft.curseforge.com/projects/armorplus/files/2504974). Thanks for reporting this issue!
