### ISSUE TITLE
[1.12.2] Crash on placing items into tier 1 workbench

### ISSUE THREAD

**Issue by Samario1** [sokratis12GR/ArmorPlus#182]
**ArmorPlus Version**:
1.12.2-11.8.1.27-beta

**TheDragonLib Version**:
1.12.2-5.2.0

**Forgelin Version**:
1.6.0

**MinecraftForge Version**:
forge-14.23.1.2558

**Minecraft Version**:
1.12.2

**(Optional) Just Enough Items (JEI) Version**:
1.12.2-4.8.4.130

**Client or Server?**:
- [X] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
https://hastebin.com/iqakizumag.txt

**What happens / happened?**:
The game locks up and crashes.

**How can I reproduce it?**:
This was an attempt to craft coal armour, so it should in theory be reproducible that way.

**Comment by sokratis12GR** [comment]
Which recipe specifically did you try?
Is it caused by the coal boots recipe?

**Comment by Samario1** [comment]
None specifically, it crashed before or as I was trying to place a coal block into the middle-left slot when there was already one in the top-left slot. The intention was to make the chestplate, but two coal blocks on top of each other is a part of every single one.

**Comment by sokratis12GR** [comment]
Alrighty, found the issue. Will release a fix in a few minutes/hours. will also improve the performance of the recipes, to reduce some issues.

**Comment by sokratis12GR** [comment]
Thanks for the report, I released a version to fix this issue, if the issues continious to happen, please create a new issue ticket!
Link to version [armorplus-11.8.2.28-beta](https://minecraft.curseforge.com/projects/armorplus/files/2506549)
