### ISSUE TITLE
[1.12.2] Vanilla GameMode (All Recipes via the vanilla crafting table)

### ISSUE THREAD

**Issue by wise-io** [sokratis12GR/ArmorPlus#183]
When easy crafting is enabled in the config, it'd be nice to have all workbenches disabled and use the vanilla crafting table. Alternatively, adding a "vanilla" setting to that config option to enable this would be cool, and would allow you to retain the easy setting as is.

I left this on the mod download page but thought I'd leave it here too to track progress (if any).

**Comment by wise-io** [comment]
I just realized that there's a config option to enable json recipes in 1.12.2 not available in the 1.10.2 version I was using previously. This essentially does what I was looking for. The only thing it doesn't do is actually disable the tiered workbenches.

**Comment by sokratis12GR** [comment]
In order to disable the recipes just do gamemode -1, meaning "none" and enable json recipes :D

**Comment by wise-io** [comment]
That's what I was looking for! Maybe just add some comments in the config to let users know that's an option?

**Comment by sokratis12GR** [comment]
Actually, will try to merge the two so there is an -1 which is vanilla and -2 which is totally disabled... soon :)
