### ISSUE TITLE
[1.12.2] Additional options in config file

### ISSUE THREAD

**Issue by wise-io** [sokratis12GR/ArmorPlus#185]
It'd be nice if the config file allowed you to specify default enchantments and the unbreakable attribute (already exists for ultimate armor) for every armor type.

**Comment by Iteries** [comment]
Hi, Additional options in config file #2 
Feature of The Gift of the Gods items Blacklist not just of individual items but also a whole mod.  Unless that option is there but no example of how to for us dummies.

**Comment by sokratis12GR** [comment]
This... could be interesting, don't exactly know how it would work but might do something like that. but if you want only certain items to be enabled you could just use whitelist. But I'll consider that for future review will see if it works out. Thanks for the suggestion(s). Also a headsup for the default enchantments, this feature will be added on a soonish update, the enchantments will be applied only when the armor is crafted (via the default table, if you wanna use a custom table or something else, you should add the enchantments by support provided by others).

**Comment by Iteries** [comment]
lmao, if you know Harvestcraft  that is a huge mod of food items.  GotG gives about 80% from that mod on average balance.  This is one example of a way to blacklist a whole mod.  I tried to see if blacklist a folder from the mod itself and not possible in testing it.  
The enchantments via crafting is an awesome idea.  I only seen that feature via Twilight Forest where you can get a drop of the said armor without enchantments until you uncraft it and remake it to get enchantments.  If I read that correctly, then suggest to take a look at it.  Plus, might consider an uncrafter/smelter of all armors & weapons that are crafted via armorplus  tables.   Hmm, smelter via cauldron appearance to smelt it all then -cough- pour into ingots/blocks.   Just another idea as I like armorplus for the customization that is available to fit into any game balance.

**Comment by sokratis12GR** [comment]
Alright. looking back at this, these will be implemented in a future version of A+.
Sorry that it took so long.

**Comment by sokratis12GR** [comment]
Sorry, not going to implement this features.
