### ISSUE TITLE
[1.12] Server Crash on start

### ISSUE THREAD

**Issue by MasterEnderman** [sokratis12GR/ArmorPlus#186]
**ArmorPlus Version**:
11.10.0.34-beta
**TheDragonLib Version**:
5.2.0
**Forgelin Version**:
1.6.0
**MinecraftForge Version**:
14.23.1.2606
**Minecraft Version**:
1.12.2
**(Optional) Just Enough Items (JEI) Version**:
4.8.5.147
**Client or Server?**:
- [ ] Client
- [ x] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
https://pastebin.com/saSxUcaf
**What happens / happened?**:
Crash on Server Startup.
**How can I reproduce it?**:

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
Hey thanks for the issue, I've released a fix for this, should be live shortly

**Comment by sokratis12GR** [comment]
Version 1.12.2-1110.1.35-beta

**Comment by MasterEnderman** [comment]
thank you for the quick fix.

**Comment by sokratis12GR** [comment]
Just let me know if that still occurs on some situations
