### ISSUE TITLE
Crash on launch, only client side

### ISSUE THREAD

**Issue by ilFau** [sokratis12GR/ArmorPlus#187]
hi! thank you for this mod, can you help me with this issue?

**ArmorPlus Version**: beta 11.10.1.35

**TheDragonLib Version**: 5.2.0

**MinecraftForge Version**: 2586

**Minecraft Version**: 1.12.2

**(Optional) Just Enough Items (JEI) Version**: 4.8.5.138

**(Optional) Tinkers' Construct Version**: 8.1.49

**Client or Server?**:
- [X] Client: crash
- [ ] Server: doesn't crash

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
[Crash on pastebin](https://pastebin.com/eksQ2inr)

**What happens / happened?**:
on launch the client crash

**How can I reproduce it?**:
launch the packet

**Comment by sokratis12GR** [comment]
Could you try re-downloading the mod from https://minecraft.curseforge.com/projects/armorplus/files/2525703 ? and test if this fixes the issue ?

**Comment by ilFau** [comment]
nope, it won't work
[v. 11.10.1.35](https://pastebin.com/N6Vxdp4k)

**Comment by sokratis12GR** [comment]
Ah, you are using an outdated forge version, please update your forge to 1.12.2-14.23.2.2611 (stable) or later

**Comment by ilFau** [comment]
ah... i have trouble with newest forge version... because i use sponge forge on server.
Are there any versions of the armorplus for previous versions of Forge?

**Comment by sokratis12GR** [comment]
I guess.. [11.9.2.32-beta](https://minecraft.curseforge.com/projects/armorplus/files/2514849)

**Comment by ilFau** [comment]
It WORKS!!!

Thank you so much for best/fastest helpdesk ever!

**Comment by sokratis12GR** [comment]
Happy to help :)
