### ISSUE TITLE
Onced placed, the trophies can't be broken

### ISSUE THREAD

**Issue by StarkRG** [sokratis12GR/ArmorPlus#188]
**ArmorPlus Version**: 1.12.2-11.10.1.35-beta

**TheDragonLib Version**: 1.12.2-5.2.0

**MinecraftForge Version**: 14.23.2.2611

**Minecraft Version**: 1.12.2

**(Optional) Just Enough Items (JEI) Version**: 1.12.2-4.8.5.151

**(Optional) Tinkers' Construct Version**: 1.12.2-2.9.0.55

**(Optional) CraftTweaker (CT) Version**: 1.12-4.1.2

**Client or Server?**:
- [ ] Client
- [ x] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: N/A

**What happens / happened?**: I received the wither boss trophy after killing one and placed it down, however, after that, I couldn't remove it again. Even in creative mode I can't break it, and the setblock command returns an error

**How can I reproduce it?**:

**(Optional) Mod List**:
  AbyssalCraft-1.12.2-1.9.4.3
  ActuallyAdditions-1.12.2-r130
  ActuallyBaubles-1.12-1.1
  ae2stuff-0.7.0.4-mc1.12.2
  aether_legacy-1.12.2-v2.0
  AIImprovements-1.12-0.0.1b3
  AkashicTome-1.2-10
  alternatingflux-0.12-3
  AppleCore-mc1.12.2-3.1.0
  AppleSkin-mc1.12-1.0.9
  appliedenergistics2-rv5-stable-8
  armorplus-1.12.2-11.10.1.35-beta
  Aroma1997Core-1.12.2-2.0.0.0.b142
  Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b65
  astralsorcery-1.12.2-1.8.5
  AutomatedRedstone-1.12.2-6.1.0
  autoplant-1.12-1.0.0
  AutoRegLib-1.3-15
  base-1.12.2-3.6.1
  Baubles-1.12-1.5.2
  bdlib-1.14.3.12-mc1.12.2
  BedBugs-1.12-1.0.1
  BetterFoliage-MC1.12-2.1.10
  BetterFps-1.4.8
  BetterPlacement-1.0.0-cfgfix
  BetterThanMending-1.1.1
  BiblioCraft[v2.4.3][MC1.12.0]
  binnie-mods-1.12.2-2.5.0.112
  BiomesOPlenty-1.12.2-7.0.1.2313-universal
  blockdrops-1.12.2-1.4.0
  Bookshelf-1.12.2-2.3.523
  Born+In+A+Barn+V1.8-1.12-1.0
  Botania r1.10-353
  BowInfinityFix-1.11.x-1.12.x-rv5
  BrandonsCore-1.12-2.3.7.140-universal
  buildcraft-7.99.14
  CD4017BE_lib-1.12.2-6.0.8
  ceanimals-1.12-1.4.0
  Chameleon-1.12-4.1.3
  ChestTransporter-1.12.2-2.8.8
  chickens-6.0.3
  Chisel-MC1.12-0.1.1.26
  chiselsandbits-14.13
  ClayBucket-1.12-1.1
  ClientTweaks_1.12-3.1.2
  Clumps-3.0.0
  CodeChickenLib-1.12.2-3.1.5.331-universal
  CoFHCore-1.12.2-4.3.10.5-universal
  CoFHWorld-1.12.2-1.1.1.12-universal
  colored-torches-1.0.2
  comforts-1.12.2-1.1.0.1
  CommonCapabilities-1.12-1.4.0
  compacter-1.3.0.3-mc1.12.2
  compactmachines3-1.12.2-3.0.6-b192
  CompactSolars-1.12.2-5.0.17.340-universal
  Controlling-3.0.6
  CookingForBlockheads_1.12.1-6.3.17
  CraftingTweaks_1.12.1-8.1.6
  CraftTweaker2-1.12-4.1.2
  CTM-MC1.12-0.2.3.12
  CustomMainMenu-MC1.12.2-2.0.8
  CyclopsCore-1.12.2-0.11.4
  dailies-1.12.2-6
  DankNull-1.12-1.4.31
  DarkUtils-1.12.2-1.8.193
  DeathQuotes-1.2.0-mc1.12-forge
  Decocraft-2.5.2_1.12.2
  diethopper-1.1
  DimensionalEdibles-1.12-1.0
  dirt2path-1.7.0
  DiscordSuite-1.3.1
  Draconic-Evolution-1.12-2.3.8.279-universal
  Durability+Show-1.12-5.0.0
  DynamicSurroundings-1.12.2-3.4.9.3
  ElevatorMod-1.12.2-1.4.0
  elulib-0.1.11
  embers-0.230
  EnchantingTable-1.12-1.1.2
  endertanks-1.12.0-1.6.3
  EnderZoo-1.12.1-1.4.0.49
  energyconverters_1.12.1-1.0.1.2
  environmentaltech-1.12.2-2.0.7b
  Exchangers-1.12.2-2.6.2
  expandedbonemeal-1.11-1.2.1
  extraalchemy-0.3.7.1-release
  ExtraCells-1.12.2-2.5.11a48
  ExtraRails-1.12-1.3.0
  extrautils2-1.12-1.7.3
  ExtremeReactors-1.12.2-0.4.5.46
  FarmingForBlockheads_1.12-3.1.5
  FastLeafDecay-v14
  fencejumper-1.12-1.0.3
  fluxnetworks-1.12.2-3.0.3
  FoamFix-1.12.2-0.9.2-Anarchy
  forestry_1.12.2-5.8.0.242
  Forgelin-1.6.0
  FTBLib-4.2.5
  FTBUtilities-4.2.4
  FullscreenWindowed-1.12-1.6.0
  furniture-4.1.5-1.12.2
  GardenStuff-1.12-2.1.0
  gendustry-1.6.5.8-mc1.12.2
  generators-0.9.20.12-mc1.12.2
  gottagofast-1.0
  GravelMiner_1.12.1-6.1.2
  HammerCore-1.12.2-1.9.6.5
  heartdrops-1.12.2-1.0.7.1
  HungerOverhaul-1.12.2-1.3.1.jenkins142
  HuntingDimension-1.12.2-1.0.12
  ic2magma-1.0
  ImmersiveCables-1.12.2-1.2.0.1
  ImmersiveEngineering-0.12-76
  ImmersiveEngineering-0.12-76-core
  immersivepetroleum-1.12.2-1.1.7
  immersivetech-1.12-1.3.4
  industrialcraft-2-2.8.53-ex112
  industrialforegoing-1.12.2-1.7.2-117
  IntegratedDynamics-1.12.2-0.11.3
  IntegratedTunnels-1.12.2-1.5.1
  IntegrationForegoing-1.12-1.4
  inventorypets-1.12-1.4.9.9b
  InventoryTweaks-1.64-dev
  IronBackpacks-1.12.2-3.0.5-6
  itemscroller-1.12.0-0.11.0
  IvToolkit-1.3.3-1.12
  JAOPCA-1.12.2-2.2.6.71
  JAOPCAOC-1.12.2-1.0.9
  jehc-1.12-1.3.1
  jei_1.12.2-4.8.5.151
  jeibees-0.9.0.5-mc1.12.2
  jeiintegration_1.12.2-1.5.1.36
  jeivillagers-1.12-1.0.2
  jepb-1.12-1.2.1
  journeymap-1.12.2-5.5.2
  JustAFewFish-1.7_for_1.12
  JustEnoughResources-1.12.2-0.8.7.41
  keywizard-1.12.2-1.5.2
  lanolin-1.12-0.2b
  MagicalPsi-1.3
  MagicBees-1.12.2-3.1.9
  malisisblocks-1.12.2-6.1.0
  malisiscore-1.12.2-6.4.0
  malisisdoors-1.12.2-7.3.0
  Mantle-1.12-1.3.1.21
  mcjtylib-1.12-2.6.3
  Mekanism-1.12.2-9.4.3.330
  MekanismGenerators-1.12.2-9.4.3.330
  MekanismTools-1.12.2-9.4.3.330
  MineTweakerRecipeMaker-1.12.2-1.2.2.30
  MmmMmmMmmMmm-1.12-1.14
  MobGrindingUtils-0.3.4
  modtweaker-4.0.6
  modular-routers-1.12.2-3.1.2
  morechickens-1.12.2-3.1.0
  MoreShearables1.2.3-1.12
  Morph-o-Tool-1.2-16
  MTLib-3.0.1
  multistorage-1.12.0-1.4.7
  naturalbabyanimals-1.1.3-mc1.12.x
  NetherEx-1.12-2.1.14.15
  NoMoreRecipeConflict-0.9(1.12)
  NotEnoughIDs-1.5.4.2
  NotEnoughItems-1.12.2-2.4.1.233-universal
  notenoughwands-1.12-1.6.1
  OceanFloor-1.12-1.0.1
  ocsensors-1.0.4-b23
  oeintegration-2.3.2
  omlib-1.12.2-3.0.0-138
  ompd-1.12.2-3.0.0-35
  OpenComputers-MC1.12.1-1.7.1.43
  OpenGlider-1.12.1-1.1.0
  openmodularturrets-1.12.2-3.0.0-236
  OreExcavation-1.4.113
  p455w0rdslib-1.12-2.0.27
  Pam's HarvestCraft 1.12.2o
  Ping-1.12-1.4.2
  placementpreview-1.12.2-0.3.2
  plustic-6.3.6.2
  primitivemobs-1.1.5c_beta
  Psi-r1.1-59
  Quark-r1.4-122
  RandomThings-MC1.12.2-4.1.2
  rangedpumps-0.5
  RealisticItemDrops-1.2.11
  ReAuth-3.5.2
  RebornCore-1.12.2-3.6.5.197-universal
  RedstoneArsenal-1.12.2-2.3.10.4-universal
  RedstoneFlux-1.12-2.0.1.2-universal
  Reliquary-1.12.2-1.3.4.733
  ResourceLoader-MC1.12.1-1.5.3
  RFTLR1.1
  rftools-1.12-7.27
  rftoolsctrl-1.12-1.8.0
  rftoolsdim-1.12-5.51
  RoguelikeDungeons-1.12.2-1.8.0
  roost-1.12-1.2.0
  roots-2-0.104
  Ruins-1.12
  SaltyMod_1.12.1_e_
  ScalingHealth-1.12-1.3.10-90
  ShadowMC-1.12-3.8.0
  shetiphiancore-1.12.0-3.5.6
  SilentLib-1.12-2.2.16-97
  simplefluidtanks-1.12.2-1.7.1.0
  SimplyJetpacks2-1.12.2-2.2.2.28
  Snad-1.12.1-1.7.09.16a
  SolarFluxReborn_1.12.2-3.42r
  sonarcore-1.12.2-5.0.5
  SoundFilters-0.10_for_1.12
  SpartanShields-1.12.2-1.4.1
  StevesFactoryManager-1.12.2-2.0.0beta7
  stg-1.12.2-1.2.3
  StorageDrawers-1.12.2-5.3.4
  StorageDrawersExtras-1.12-3.1.0
  supersoundmuffler-1.12.1-1.0.2.9
  switchbow-1.5.2-1.12.2
  TConstruct-1.12.2-2.9.0.55
  tesla-core-lib-1.12-1.0.12
  thebomplugin-1.12-0.2.3
  thedragonlib-1.12.2-5.2.0
  theoneprobe-1.12-1.4.19
  ThermalDynamics-1.12.2-2.3.10.4-universal
  ThermalExpansion-1.12.2-5.3.10.15-universal
  ThermalFoundation-1.12.2-2.3.10.6-universal
  TinkerToolLeveling-1.12-1.0.3
  TombManyGraves-1.12-4.0.2
  topaddons-1.12.2-1.3.0
  torchmaster_1.12.2-1.6.1.53
  TrashSlot_1.12.1-8.4.6
  twilightforest-1.12.2-3.6.345-universal
  UniDict-1.12.2-2.3.2
  UnlimitedChiselWorks-0.1.10
  valkyrielib-1.12.2-2.0.7a
  Waddles-1.12.2-0.5.6
  WanionLib-1.12.2-1.4
  WaterStrainer-1.12-3.2.0
  Waystones_1.12.2-4.0.20
  WirelessCraftingTerminal-1.12.2-3.9.58
  wolfarmor-1.12.2-2.1.0.24-RELEASE
  worldedit-forge-mc1.12-6.1.8-dist
  WrapUp-1.12-1.1.3
  xnet-1.12-1.6.7
  YNot-0.2.1
  zerocore-1.12-0.1.1.0
  zettaindustries-1.3-1.12.2-148

**Comment by sokratis12GR** [comment]
Thanks for the issue report, will look into a fix or how I could help you, but currently not able to check and/or do a quick fix, if you want we could try to get deeper into the issue via discord https://discord.gg/FteuZ5e

**Comment by sokratis12GR** [comment]
Actually could you send me the error after the setblock command? It might be an issue with error in Tile Entities

**Comment by StarkRG** [comment]
Sorry, it's taken me a little while to get this:

> ```
> [15:05:43] [Server thread/WARN]: Couldn't process command: setblock 1991 66 118 minecraft:stone
> java.lang.AbstractMethodError: net.thedragonteam.armorplus.blocks.special.TrophyType.getEntityId()Lnet/minecraft/util/ResourceLocation;
> 	at net.thedragonteam.armorplus.blocks.special.BlockTrophy.createTileEntity(BlockTrophy.java:33) ~[BlockTrophy.class:1.12.2-11.10.1.35-beta]
> 	at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:780) ~[axw.class:?]
> 	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:798) ~[axw.class:?]
> 	at net.minecraft.world.World.func_175625_s(World.java:2396) ~[amu.class:?]
> 	at net.minecraft.command.server.CommandSetBlock.func_184881_a(CommandSetBlock.java:106) ~[di.class:?]
> 	at com.feed_the_beast.ftbu.ranks.CmdOverride.func_184881_a(CmdOverride.java:76) ~[CmdOverride.class:?]
> 	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
> 	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
> 	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
> 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
> 	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
> 	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
> 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
> ```

Additionally, when looking at it with The One Probe the server log gets spammed with these, very similar, messages:

> ```
> [14:54:41] [Server thread/FATAL]: Error executing task
> java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: net.thedragonteam.armorplus.blocks.special.TrophyType.getEntityId()Lnet/minecraft/util/ResourceLocation;
> 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_161]
> 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_161]
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
> Caused by: java.lang.AbstractMethodError: net.thedragonteam.armorplus.blocks.special.TrophyType.getEntityId()Lnet/minecraft/util/ResourceLocation;
> 	at net.thedragonteam.armorplus.blocks.special.BlockTrophy.createTileEntity(BlockTrophy.java:33) ~[BlockTrophy.class:1.12.2-11.10.1.35-beta]
> 	at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:780) ~[axw.class:?]
> 	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:798) ~[axw.class:?]
> 	at net.minecraft.world.World.func_175625_s(World.java:2396) ~[amu.class:?]
> 	at appeng.integration.modules.theoneprobe.config.AEConfigProvider.getProbeConfig(AEConfigProvider.java:47) ~[AEConfigProvider.class:?]
> 	at mcjty.theoneprobe.network.PacketGetInfo.getProbeInfo(PacketGetInfo.java:136) ~[PacketGetInfo.class:?]
> 	at mcjty.theoneprobe.network.PacketGetInfo.access$600(PacketGetInfo.java:32) ~[PacketGetInfo.class:?]
> 	at mcjty.theoneprobe.network.PacketGetInfo$Handler.handle(PacketGetInfo.java:108) ~[PacketGetInfo$Handler.class:?]
> 	at mcjty.theoneprobe.network.PacketGetInfo$Handler.lambda$onMessage$0(PacketGetInfo.java:101) ~[PacketGetInfo$Handler.class:?]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_161]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_161]
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
> 	... 5 more
> ```

**Comment by sokratis12GR** [comment]
hmm, inside `config/forge.cfg` there should be a `    B:removeErroringEntities=false` make it to true and let me know the result, will try and work on a fix for the trophy block

**Comment by StarkRG** [comment]
neither that setting nor B:removeErroringTileEntities=true had any effect. Note that the server doesn't actually crash, it's just that this block is apparently untouchable by anything.

**Comment by sokratis12GR** [comment]
hmm, could you try to edit the nbt of the trophy?
`/blockdata <coords> {DisplayEntity:{id:"minecraft:ender_dragon"}, EntityScale:0.1f}`

**Comment by StarkRG** [comment]
Same error, this time with "Couldn't process command: blockdata 1991 66 118 {DisplayEntity:{id:"minecraft:ender_dragon"}, EntityScale:0.1f}"

**Comment by sokratis12GR** [comment]
:/ no clue, maybe not enough perms ? Sorry... will have to look deeper into it once I can.

**Comment by StarkRG** [comment]
I am opped. Plus I've tried it from the console. 

I'll see if I can find the region file and open it with an nbt editor. I'll let you know what (if) I uncover.

**Comment by StarkRG** [comment]
I downloaded the region file and opened it in mcedit2, I found the block and, as far as I could tell, it didn't have a tile entity. The trophy items I received have no NBT either (I'm not sure if they're supposed to)

**Comment by sokratis12GR** [comment]
Yes they were supposed to have nbt. Will be fixed in the new update coming soon. Thank you so much for tracking down the issue!

**Comment by StarkRG** [comment]
No worries. I was very intrigued by a block that the server itself can't remove. :)

**Comment by sokratis12GR** [comment]
Should be fixed :). Let me know if it was or wasn't. Please re-open the issue or join our discord server for contact ;)
