### ISSUE TITLE
[1.12.2] Config option for potion timer resets

### ISSUE THREAD

**Issue by plunginghornets** [sokratis12GR/ArmorPlus#191]
**ArmorPlus Version**: 11.11.0.36

**TheDragonLib Version**:5.2

**Minecraft Version**:1.12

**Client or Server?**:
- [x] Client

I don't want flight in my modpack, so I changed the dragon armor to give a 5 heart health boost instead. It works fine, except that the effect timer runs out completely before being reapplied. So every 11 seconds, any part of the 5 boosted hearts that you fill is lost.
Could you add a config option to change potion effects to reapply every second like the Night Vision on Coal armor does?

**Comment by sokratis12GR** [comment]
Thanks for the great suggestion, will see what I can do. Just a note, that there are some effects that require time to get applied (i.e Regeneration).

**Comment by sokratis12GR** [comment]
Added this option for the individual potion effects, side note setting the effect to `0` or `1` will make them constantly apply (will not work for overtime effects like regeneration).
Added this option for the armors & the weapons.
Update: [1.12.2-11.12.1.39-beta](https://minecraft.curseforge.com/projects/armorplus/files/2556365)
**Not yet approved by the time of posting this**
