### ISSUE TITLE
Really Awesome Concept Getting Finished Soon?

### ISSUE THREAD

**Issue by Boolyman** [sokratis12GR/ArmorPlus#192]
I have been keeping an eye on the unadvertised bosses that are built into Armor Plus, like the Skeletal King and the Overlord of the Guardians.  I have been hoping they would be ready by the time my modpack came out, but unfortunately time has gone by and they still say WIP.  Is there any chance that either of these, or at least the Skeletal King will be ready to play in the next few weeks?

The only thing I see wrong with the Skeletal king is that when you look upwards, his model dissappears.

**Comment by sokratis12GR** [comment]
The thing is, all of the bosses must be ready at the same time, they will all change how the mod's abilities and stuff is being acquired.

**Comment by Boolyman** [comment]
Yea, I was afraid of that.  I kinda just need the mobs... not the summoning rituals, drops, etc... I can take care of all that in a way that fits the modpack story.  But I understand, its your mod and you have a vision for how you want the bosses to incorporate.  If you don't mind, I'm probably still going to use the bosses and cross my fingers that they don't crash anything.  I will be sure not to report any bugs related to them, since they are not officially released.

**Comment by sokratis12GR** [comment]
Dunno worry about reporting bugs about them, it would be even better for us here ;). Also they should crash you... They still got dome work on abilities and mechanics to do.

**Comment by Boolyman** [comment]
They should, or they shouldnt crash me?  I dont know if that was a typo or just honesty lol.

**Comment by sokratis12GR** [comment]
Shouldn't, my bad xD

**Comment by sokratis12GR** [comment]
Will close this issue, as it will take a long while until the bosses are actually fully implemented and will be only available (with actual gameplay and progression) only for 1.13.
