### ISSUE TITLE
Lava infuser

### ISSUE THREAD

**Issue by wickeddeamon** [sokratis12GR/ArmorPlus#193]
**ArmorPlus Version**: 1.12.2-11.11.0.36 beta

**TheDragonLib Version**:5.2.0

**MinecraftForge Version**: 14.23.2.2624

**Minecraft Version**: 1.12.2

**Client or Server?**:
- [X ] Client
- [ ] Server

the lava infuser dont permit me to put lava inside, ill try with a bucket, with extra util. liquid transfer

**Comment by sokratis12GR** [comment]
You are **required** to use a lava bucket, as in an item form and place it in the first slot.
*ps: you can use lava crystals to power it too*
No support for actual fluids, yet.
