### ISSUE TITLE
Trying to craft helmet causes client crash 1.10.2

### ISSUE THREAD

**Issue by jaylowbear** [sokratis12GR/ArmorPlus#194]
**ArmorPlus Version**: 1.10.2-8.5.2.3

**TheDragonLib Version**: 1.10.2-1.0.3.1

**MinecraftForge Version**: 12.18.3.2316

**Minecraft Version**: 1.10.2

**(Optional) Just Enough Items (JEI) Version**: 1.10.2-3.14.7.420

**(Optional) Tinkers' Construct Version**: 1.10.2-2.6.1

**(Optional) CraftTweaker (CT) Version**:

**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: https://pastebin.com/cgZcbBei

**What happens / happened?**: Trying to craft the helmet of any armor results in client crash. Instead of the helmet name there is "Tooltip error, see log" .. console log says: https://pastebin.com/uHK2mVUJ

**How can I reproduce it?**: Try to craft any helmet ? 

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
Hello, thanks for your issue report! But seems like its an issue caused by the voxels mod.

**Comment by jaylowbear** [comment]
I just dont get why only the helmets arent working :(
