### ISSUE TITLE
[MC 1.12.2  A+11.11.137] Texture issue with horsearmor in jei & inventory too

### ISSUE THREAD

**Issue by Iteries** [sokratis12GR/ArmorPlus#195]
**ArmorPlus Version**:armorplus-1.12.2-11.11.1.37

**TheDragonLib Version**: thedragonlib-1.12.2-5.2.0

**MinecraftForge Version**:1.12.2

**Minecraft Version**:

**(Optional) Just Enough Items (JEI) Version**: jei_1.12.2-4.8.5.159

**(Optional) Tinkers' Construct Version**:none

**(Optional) CraftTweaker (CT) Version**:none

**Client or Server?**:

- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:n/a

**What happens / happened?**: Texture for Horse Armor in wonderful pink/black boxes.  Shows up in JEI & inventory in checking if just JEI but nope.  IF the horse armors are coming out that is great news.

**How can I reproduce it?**:  Unknown

**(Optional) Mod List**: PureBDcraft Resourcepack for Minecraft  but they have none for armorplus

**Comment by sokratis12GR** [comment]
Thanks for your issue ticket.
The horse armors are yet to be complete, especially their textures. I've noted that the horse armors textures (item textures) aren't ready in one of the changelogs

**Comment by sokratis12GR** [comment]
Made the horse armors not visible/obtainable without use of commands, as they are not ready.
Update: [1.12.2-11.12.1.39-beta](https://minecraft.curseforge.com/projects/armorplus/files/2556365)
**Not yet approved by the time of posting this**
