### ISSUE TITLE
high tech workbench free items bug.

### ISSUE THREAD

**Issue by IchigoGames** [sokratis12GR/ArmorPlus#196]
armorplus-1.12.2-11.11.1.37-beta

thedragonlib-1.12.2-5.2.0

**MinecraftForge Version**:2623

1.12.2

jei_1.12.2-4.8.5.159

NoMoreRecipeConflict-0.10(1.12.2)

**Client or Server?**:
- [y ] Client
- [ y] Server

**What happens / happened?**: i was using the high tech workbench to craft some lava armor im using easy mode fyi and i saw that i could craft items from ImmersiveEngineering and immersivepetroleum as well as vanilla torch from nothing like nothing in the workbench but it lets me pull the item out tested with op and none op players with no change not sure if its this mod or one of the others allowing this to happen.

**How can I reproduce it?**: add the mods below with armorplus and click on the arrow key to see you can craft things from nothing click the small box with arrow and items pop out.

ImmersiveEngineering-0.12-80-core
immersivepetroleum-1.12.2-1.1.8
NoMoreRecipeConflict-0.10(1.12.2)
https://imgur.com/cCdpMBF

**Comment by sokratis12GR** [comment]
That's strange.

**Comment by sokratis12GR** [comment]
It's not my issue.

**Comment by sokratis12GR** [comment]
Do you have any minetweaker scripts? Because otherwise there shouldn't be any conflicts with the recipes. Probably a bug on their side.

**Comment by IchigoGames** [comment]
ya sorry i think its a issue with nomorerecipeconflict treating the  high tech workbench the same as a crafting table.

**Comment by sokratis12GR** [comment]
No worries :)
