### ISSUE TITLE
Crash When Putting On Ultimate Armor

### ISSUE THREAD

**Issue by Boolyman** [sokratis12GR/ArmorPlus#197]
**ArmorPlus Version**: 11.12.1.39

**TheDragonLib Version**: 5.2.0

**MinecraftForge Version**: 14.23.3.2676

**Minecraft Version**: 1.12.2

**(Optional) Just Enough Items (JEI) Version**:

**(Optional) Tinkers' Construct Version**:

**(Optional) CraftTweaker (CT) Version**:

**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: https://pastebin.com/cZz8HR2G

**What happens / happened?**:
Player put on Ultimate armor... crashed.

**How can I reproduce it?**:
Put on ultimate armor.

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
Thanks for the issue report, will look into it. Not sure if I'll be able to push a release today but will try my best, if not it will probably be Monday.

**Comment by sokratis12GR** [comment]
Could you show me your config file. seems like you have incorrect values for the potion effects.

**Comment by Boolyman** [comment]
Your mod has 7 different config files for some reason.  So I just zipped them up onto google docs.  https://drive.google.com/file/d/1YdFLiONDM0rYpYR5PqFeJIFVzqH9k26T/view?usp=sharing

**Comment by sokratis12GR** [comment]
Yes, 7 different configs for 7 different parts of the mods, if something related to armors crashes and is affected by a config I would need the registry.cfg . I should have specified which one I need

**Comment by sokratis12GR** [comment]
Sorry for taking that long to review it but as expected the issue is that you have an additional effect in the ultimate armor part of the `registry.cfg` config, remove the potion effect `saturation`, you should have 2 effects by default (If you haven't changed what potion effects it should provide).

**Comment by sokratis12GR** [comment]
As well as removing the first `0` on the effect levels.
