### ISSUE TITLE
Ender Dragon Armor issue

### ISSUE THREAD

**Issue by xSlimeGamerx123** [sokratis12GR/ArmorPlus#199]
**ArmorPlus Version**: 11.13.0.40

**TheDragonLib Version**: 5.2.0

**MinecraftForge Version**: 14.23.3.2655

**Minecraft Version**: 1.12.2

**(Optional) Just Enough Items (JEI) Version**: 4.9.1.187

**(Optional) Tinkers' Construct Version**:

**(Optional) CraftTweaker (CT) Version**:

**Client or Server?**:
- [*] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: No Crash

**What happens / happened?**: When i tried Ender Dragon armor and i had Creative mode, then I put it out of my inventory and i couldn´t fly in my World.. idk what happened but to fly i need to have the armor on, and i don´t really want that...

**How can I reproduce it?**: idk, try to fix that glitch ^^^^

**(Optional) Mod List**:
+RPG HUD
MoVillages
AdditionalBanners
AmbientSounds 2
architecturecraft
armorplus
ArmorStandGUI
ATLCraftCandles
AttributeFix
backpack
B.A.S.E.
BaseMetals
BetterFoliage
BetterFPS
BetterTitleScreen
betterunderground
BiblioCraft
Blur
Bookshelf
MrCrayfish´s Device Mod
Ceramics
MrCrayfish´s Furniture Mod
Clumps
CodeChickenLib
combutfish
cookiecore
CreativeCore
CustomCursorMod
Cyclic
DecoCraft 2
DoggyTalents
DynamicTrees
Earthworks
Exotic+ Birds
extraalchemy
fairylights
forestry
ForgeMultipart (Universal)
gigaherz.commons (idk what this is, it added showed up automatically)
ChestTransporter
ChickenASM
ChickenChunks
ChunkAnimator
InventoryTweaks
iTorch
JEI
JourneyMap
JustAFewFish
justthetips
LabyMod 3
landlust
MrCrayfish´s LightSwitch
Malisis Core
Malisis Doors
MineMenu
MinIHeads
Missing_Pieces
morebeautifulplates
morebeautifulbuttons
morebees
MoreCommands (This is what I tried to fix the problem with, but when i tope /fly on, ArmorPlus automatically disabled it)
MorePlayerModels
MoreShearables
MultiStorage
MW
Neat+
Optifine HD_U_D2
Pillagers
placeableitems
PTRLib
RebornCore
redstonepaste
refinedstorage
rustic
ShadowMC
shetiphiancore
signpost
SimpleCorn
smarthud
Snad
spectrite
SplashAnimation
StevesCarts
Tails
thedragonlib
ToolBelt
Toolbox
Torchmaster
TrashSlot
Traverse
WearableBackpacks
worledit-fore

**Comment by xSlimeGamerx123** [comment]
Actually, will removing ArmorPlus mod fix it?

**Comment by sokratis12GR** [comment]
Thanks for your issue ticket.
Considering this issue happens only when the player already has a flight effect and removes it via the clear command or a conflicting mod makes this happen I'll need the following information.
- the `registry.cfg` configuration file inside `config/armorplus`
- How exactly did you remove the armor
- Did you try going back to survival and then back to creative mode?
- have you disabled flight inside the config file?
- Did you have any other flight providers equipped while you had the armor on?

**Comment by xSlimeGamerx123** [comment]
Oh, Hi thanks, nothing what you typed work, but I fixed it by removing everything from my Inventory with the X icon while I had the armor on, now I can fly without the armor, but anyways thanks for your response :)

**Comment by sokratis12GR** [comment]
Alrighty. Happy to hear that you have found a solution :)
