### ISSUE TITLE
Crash on Nether and Re-enter

### ISSUE THREAD

**Issue by euphoniumlover** [sokratis12GR/ArmorPlus#203]
**Affected Versions (Do not use "latest"):**:
  - **ArmorPlus**: 11.12.1.39
  - **TheDragonLib**: 5.2.0
  - **Minecraft**: 1.12.2
  - **Forge**: 14.23.4.2708
  - (Optional) Just Enough Items (JEI): v 1.0.0
  - (Optional) Tinkers' Construct: 2.9.1.65
  - (Optional) CraftTweaker (CrT): CT2 4.1.8

**Affected Side (Client or Server)**:
- [x] Client
- [ ] Server

**What happens**: When I entered the nether I got this crash, and then when I exited and reopened the game, then started the world, I got the same exact crash.

**What you expected to happen:**: To enter the nether, and to re-enter into the nether

**If its a crash, post your crash report (via. pastebin/gist/etc)**: [https://pastebin.com/tbaYwHgQ](https://pastebin.com/tbaYwHgQ)

**Your configuration files from `config/armorplus/` (`registry.cfg` mainly)**: [https://pastebin.com/RyVizza2](https://pastebin.com/RyVizza2), worldgen: [https://pastebin.com/fbNKz6RE](https://pastebin.com/fbNKz6RE)

**(Optional) Mod List**:

**Comment by antoinegag** [comment]
Small suggestion related to this issue for the devs, maybe add the value of `minHeight` and `maxHeight` in the exception thrown here, makes it easier to debug.
https://github.com/TheDragonTeam/ArmorPlus/blob/d932701b6a38697417e8fcb6393fd918bd4e4520/src/main/java/net/thedragonteam/armorplus/util/WorldGenUtils.java#L34

**Comment by sokratis12GR** [comment]
Hello, thanks for the issue report.
Could you try the following things:
- Attempt to load the world without HammerCore (if possible)
- Provide me the `worldgen.cfg` config file

**Comment by sokratis12GR** [comment]
Meanwhile, your armorplus version is outdated. newest one is [ArmorPlus 1.12.2-11.13.0.40 (May 16, 2018)](https://minecraft.curseforge.com/projects/armorplus/files/2562477)

**Comment by euphoniumlover** [comment]
Tried it without HammerCore and came back with the same crash, and I had updated ArmorPlus

**Comment by sokratis12GR** [comment]
Could you link the crash ? Because it cannot be the same crash. but might help resolving the issue.

**Comment by euphoniumlover** [comment]
Crash w/o HammerCore: [https://pastebin.com/VQe0jFkT](https://pastebin.com/VQe0jFkT)

**Comment by sokratis12GR** [comment]
Alrighty, now I need your `worldgen.cfg` inside `config/armorplus`. The height value seems to have been changed to an unacceptable value. *`minHeight`* must be greater than `0` and not greater than *`maxHeight`*, while *`maxHeight`* must not be greater than 256.

**Comment by euphoniumlover** [comment]
I posted the config in the first comment, but just in case it didn't show up, here it is: [https://pastebin.com/fbNKz6RE](https://pastebin.com/fbNKz6RE)

**Comment by sokratis12GR** [comment]
Well, here is your issue, thats a big nono xD 
![image](https://user-images.githubusercontent.com/12274096/41997991-46155d80-7a62-11e8-95ce-b1f75de908d6.png)

**Comment by euphoniumlover** [comment]
WOAH! I must have accidentally set that. Thanks! I never expected this to get answered in the same day, and now it's fixed! Thanks for your quick response.

**Comment by sokratis12GR** [comment]
Happy to help ^^
