### ISSUE TITLE
Cobalt Armor doesn't give the Haste III effect

### ISSUE THREAD

**Issue by Mariomm-marti** [sokratis12GR/ArmorPlus#204]
**Affected Versions (Do not use "latest"):**:
  - **ArmorPlus**: 1.12.2-11.13.1.41
  - **TheDragonLib**: 1.12.2-5.3.0
  - **Minecraft**: 1.12.2
  - **Forge**: 14.23.4.2705
  - (Optional) Just Enough Items (JEI): 4.11.0.204
  - (Optional) Tinkers' Construct: 1.12.2-2.10.1.87
  - (Optional) CraftTweaker (CrT): -

**Affected Side (Client or Server)**:
- [ X ] Client
- [ X ] Server

**What happens**: When I equip the full cobalt armor it doesn't give the Haste III effect.

**What you expected to happen:**: I expect the Haste III effect to happen.

**If its a crash, post your crash report (via. pastebin/gist/etc)**:

**Your configuration files from `config/armorplus/` (`registry.cfg` mainly)**: https://hastebin.com/ojehijezap.coffeescript

**(Optional) Mod List**: https://cdn.discordapp.com/attachments/398242599762132994/470333206831300609/unknown.png

**Additional detail**: When it happened to me I tried using the ArmorPlus mod alone and it still didn't work. It is the only armor with that issue

![imagen](https://user-images.githubusercontent.com/24687973/43040044-59126ba4-8d3a-11e8-96ea-97cb5d5683ed.png)

**Comment by sokratis12GR** [comment]
Found the issue, on the set check I've made a typo and check for Coal leggings, instead of a cobalt one.

**Comment by Mariomm-marti** [comment]
What do you mean? You mean the registry.cfg?

**Comment by sokratis12GR** [comment]
No, it's a bug. I derped again, on the same armor for the second time. Will be fixed in the future.. For now you would need coal leggings in order to activate the haste.

**Comment by Mariomm-marti** [comment]
Thank you!

**Comment by sokratis12GR** [comment]
[ArmorPlus 1.12.2-11.14.0.42](https://minecraft.curseforge.com/projects/armorplus/files/2617273) should have this issue fixed.
