### ISSUE TITLE
Can't repair Manyullyn armor

### ISSUE THREAD

**Issue by Mariomm-marti** [sokratis12GR/ArmorPlus#205]
**Affected Versions (Do not use "latest"):**:
  - **ArmorPlus**: 1.12.2-11.13.1.41
  - **TheDragonLib**: 1.12.2-5.3.0
  - **Minecraft**: 1.12.2
  - **Forge**: 14.23.4.2705
  - (Optional) Just Enough Items (JEI): 4.11.0.204
  - (Optional) Tinkers' Construct: 1.12.2-2.10.1.87
  - (Optional) CraftTweaker (CrT): -

**Affected Side (Client or Server)**:
- [ X ] Client
- [ X ] Server

**What happens**: I cannot repair some armors, for example the manyullyn one

**What you expected to happen:**: I expect it to be repaired according to this guide: https://ftb.gamepedia.com/ArmorPlus_repairing

**If its a crash, post your crash report (via. pastebin/gist/etc)**: -

**Your configuration files from `config/armorplus/` (`registry.cfg` mainly)**: https://hastebin.com/ojehijezap.coffeescript

**(Optional) Mod List**: https://cdn.discordapp.com/attachments/398242599762132994/470333206831300609/unknown.png

**Additional detail**: When it happened to me I tried using the ArmorPlus mod alone and it still didn't work. I didn't test this on other armors.

![imagen](https://user-images.githubusercontent.com/24687973/43079612-de00bff6-8e8d-11e8-8a0f-eda3e39e0636.png)
![imagen](https://user-images.githubusercontent.com/24687973/43079627-e80b9f84-8e8d-11e8-94db-d73b3667b415.png)
![imagen](https://user-images.githubusercontent.com/24687973/43079634-ed04ccb8-8e8d-11e8-9845-6d42f0cc9560.png)

**Comment by sokratis12GR** [comment]
Unless tinkers` changed from having their ingots reg name as `ingot` and using meta from 0-x amount of ingots, it should work fine. Can't confirm if it a bug or not, currently on a vacation will try to resolve the issue asap once I'm back home.. But this will take a long while. You for now would need to use CraftTweaker to add a repairing recipe for the armors that have a broken repair item. I'm sorry about that, hope the little info I provided helps.

**Comment by Mariomm-marti** [comment]
Hey, thanks for this fast support. Here you have an image of the reg name (I think this is what you mean). It's `ingots` and it data value is 2.
![imagen](https://user-images.githubusercontent.com/24687973/43083667-5a5353e4-8e97-11e8-90db-fe3e461fc29d.png)

I will find out what exactly CraftTweaker is.

**Comment by sokratis12GR** [comment]
Ugh it might be a problem that tconstruct loaded after armorplus, making some of the required stacks not able to be initialized, tl;dr its... Technically my fault. Will try to resolve this issue as well as the other issues once I'm back from vacation

**Comment by sokratis12GR** [comment]
[ArmorPlus 1.12.2-11.14.0.42](https://minecraft.curseforge.com/projects/armorplus/files/2617273) should have this issue fixed.

**Comment by LGPM2** [comment]
Hey I'm in 1.12.2 version and I can't repair the obsidian armor.
