### ISSUE TITLE
ArmorPlus crashes with mantle

### ISSUE THREAD

**Issue by Zer0Lyfe** [sokratis12GR/ArmorPlus#206]
**Affected Versions (Do not use "latest"):**:
  - **ArmorPlus**:1.12.2-11.13.1.41
  - **TheDragonLib**: 1.12.2-5.3.0
  - **Minecraft**: 1.12.2
  - **Forge**: 14.23.4.2750
  - mantle: Mantle-1.12-1.3.2.24
  - (Optional) Tinkers' Construct: TConstruct-1.12.2-2.10.1.87

**Affected Side (Client or Server)**:
- [x] Client
- [ ] Server

**What happens**:
crashes while loading minecraft
**What you expected to happen:**:
to load minecraft
**If its a crash, post your crash report (via. pastebin/gist/etc)**:
https://paste.dimdev.org/fucavezaba.mccrash - VanillaFix
https://gist.github.com/Zer0Lyfe/a340c96a081cf958f54c3a1badc60b3f - Gist
**Your configuration files from `config/armorplus/` (`registry.cfg` mainly)**:
https://gist.github.com/Zer0Lyfe/a4263f76678f87f3fc37607c4121af8a - Registry
**(Optional) Mod List**:
in the crash log

If you need anything extra just let me know.

**Comment by sokratis12GR** [comment]
Seems like mantle had a breaking change or something on a newer update of theirs.
Its a bug, but the only way to fix this is either by disabling the mod integration via `config/armorplus/integration.cfg` and disable tconstruct or downgrade the version of Tconstruct & mantle.

**Comment by sokratis12GR** [comment]
I'll do an update fixing all these issues once summer ends, currently impossible for me to fix those bugs.

**Comment by Zer0Lyfe** [comment]
OK. Thank you @sokratis12GR

**Comment by KenyMylankca** [comment]
hello... just passing through....
[crash-2018-08-25_20.49.21-client.txt](https://github.com/TheDragonTeam/ArmorPlus/files/2320920/crash-2018-08-25_20.49.21-client.txt)
this crash happens when foamfix by @asiekierka is installed... hope somebody fixes it..

**Comment by KenyMylankca** [comment]
also see this: https://github.com/JanneSoon/HarshenModpack/commit/dfbe76386c951bf8afd25892c3eb7eefc471c3f6
...

**Comment by asiekierka** [comment]
My, my, that is a FoamFix bug! But why in this repo?

**Comment by KenyMylankca** [comment]
cus im the first one who noticed it is a foamfix bug :)

**Comment by asiekierka** [comment]
Nonono, please report it on the FoamFix repo or I might miss it :thinking:

**Comment by KenyMylankca** [comment]
okay.

**Comment by sokratis12GR** [comment]
[ArmorPlus 1.12.2-11.14.0.42](https://minecraft.curseforge.com/projects/armorplus/files/2617273) should have this issue fixed.

**Comment by Nawor3565** [comment]
> 
> 
> [ArmorPlus 1.12.2-11.14.0.42](https://minecraft.curseforge.com/projects/armorplus/files/2617273) should have this issue fixed.

Having the bug with the latest version, crash log here: https://paste.dimdev.org/lirayucoso.mccrash

**Comment by sokratis12GR** [comment]
I'm sorry but I cannot reproduce the bug you are reporting.

**Comment by Alphanos** [comment]
FYI since you mentioned you cannot reproduce the crash, it looks like it's actually being caused by a bug in Foamfix.

https://github.com/asiekierka/FoamFix/issues/164

**Comment by sokratis12GR** [comment]
Thank you for letting me know!
