### ISSUE TITLE
TC Armors not craftable

### ISSUE THREAD

**Issue by biomagical** [sokratis12GR/ArmorPlus#208]
**Affected Versions (Do not use "latest"):**:
  - **ArmorPlus**: x
  - **TheDragonLib**:
  - **Minecraft**:
  - **Forge**:
  - (Optional) Just Enough Items (JEI): x
  - (Optional) Tinkers' Construct: x
  - (Optional) CraftTweaker (CrT):

**Affected Side (Client or Server)**:
- [x] Client
- [x] Server

**What happens**:
I cannot see the recipes to craft TC armors(Cobalt, Manylluyn, etc), and they are not craftable with the recipes on FTBwiki
**What you expected to happen:**:
The ability to craft them
**If its a crash, post your crash report (via. pastebin/gist/etc)**:

**Your configuration files from `config/armorplus/` (`registry.cfg` mainly)**:
https://pastebin.com/Btfm55F5
**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
Will investigate, for now manually add the recipes via CraftTweaker

**Comment by biomagical** [comment]
Any luck?

**Comment by sokratis12GR** [comment]
Could you specify which armorplus version, tknkersconstruct version, thedragonlib, jei versions?

**Comment by sokratis12GR** [comment]
The recipes in the FTB Wiki are outdated (Since I got no time to update them, and no other took their time to update the recipes to the latest 1.12.2 recipes). Jei should help for the recipes.

**Comment by biomagical** [comment]
armorplus-1.12.2-11.14.0.42
TConstruct-1.12.2-2.10.1.87
thedragonlib-1.12.2-5.3.0
jei_1.12.2-4.12.1.217

**Comment by biomagical** [comment]
armorplus-1.12.2-11.14.0.42
jei_1.12.2-4.12.1.217
TConstruct-1.12.2-2.10.1.87
thedragonlib-1.12.2-5.3.0

**Comment by sokratis12GR** [comment]
Next update should fix this:
![image](https://user-images.githubusercontent.com/12274096/47614607-2f24be00-daab-11e8-877b-f80b78ec6aaf.png)
Will be published in a few minutes/hours (1.12.2-11.15.0.43)
