### ISSUE TITLE
Crash in MC 1.12.2

### ISSUE THREAD

**Issue by RayzoRayy** [sokratis12GR/ArmorPlus#209]
**Affected Versions (Do not use "latest"):**:
  - **ArmorPlus**:11.14.0.42
  - **TheDragonLib**:5.3.0
  - **Minecraft**:1.12.2
  - **Forge**:14.23.5.2772
  - (Optional) Just Enough Items (JEI):4.12.1.217
  - (Optional) Tinkers' Construct:2.10.1.87
  - (Optional) CraftTweaker (CrT):

**Affected Side (Client or Server)**:
- [X] Client
- [ ] Server

**What happens**:I launch my pack, it crashes

**What you expected to happen:**:Not to crash

**If its a crash, post your crash report (via. pastebin/gist/etc)**:https://pastebin.com/Cm8jut3n

**Your configuration files from `config/armorplus/` (`registry.cfg` mainly)**:They are default configs, I have not changed anything.

**(Optional) Mod List**:https://pastebin.com/BtyCWqY6

**Comment by sokratis12GR** [comment]
**Temporary Fix:**
_Disable the Tinkers' Construct integration_ 
* `config\armorplus\integrations.cfg`

**Comment by sokratis12GR** [comment]
Actually, this might be related to the other issue, with FoamFix:
asiekierka/FoamFix#164
- No clue what's going on here asie :/
