### ISSUE TITLE
Crash with latest Forge

### ISSUE THREAD

**Issue by MCEventHorizon** [sokratis12GR/ArmorPlus#210]
**Affected Versions (Do not use "latest"):**:
  - **ArmorPlus**: 1.12.2-11.14.0.42
  - **TheDragonLib**: 1.12.2-5.3.0
  - **Minecraft**: 1.12.2
  - **Forge**: 14.23.5.2772
  - (Optional) Just Enough Items (JEI):
  - (Optional) Tinkers' Construct:
  - (Optional) CraftTweaker (CrT):

**Affected Side (Client or Server)**:
Server, I think

**What happens**: game crashes

**What you expected to happen:**: not crash?

**If its a crash, post your crash report (via. pastebin/gist/etc)**: https://pastebin.com/EFLeLxwB

**Your configuration files from `config/armorplus/` (`registry.cfg` mainly)**:

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
Will be pushing an update to fix this issue in a few minutes/hours (1.12.2-11.15.0.43)

**Comment by MCEventHorizon** [comment]
Update still didn't fix it.

**Comment by MCEventHorizon** [comment]
Erasing the old config fixes it.
