### ISSUE TITLE
Disabling any Tinkers' Armor causes a crash

### ISSUE THREAD

**Issue by MCEventHorizon** [sokratis12GR/ArmorPlus#211]
**Affected Versions (Do not use "latest"):**:
  - **ArmorPlus**: 1.12.2-11.15.0.43
  - **TheDragonLib**: 1.12.2-5.3.0
  - **Minecraft**: 1.12.2
  - **Forge**: 14.23.4.2760
  - (Optional) Just Enough Items (JEI):
  - (Optional) Tinkers' Construct: not installed
  - (Optional) CraftTweaker (CrT):

**Affected Side (Client or Server)**:
- [ ] Says client crash in crash-reports

**What happens**: disabling any type of Tinkers' armor causes a crash

**What you expected to happen:**: to not crash

**If its a crash, post your crash report (via. pastebin/gist/etc)**: https://pastebin.com/SzFDSyuj

**Your configuration files from `config/armorplus/` (`registry.cfg` mainly)**: 

**(Optional) Mod List**:

**Comment by MCEventHorizon** [comment]
Why is this closed?

**Comment by sokratis12GR** [comment]
Update has been released that fixes this issue, that is why its closed.
[1.12.2-11.15.1.44](https://minecraft.curseforge.com/projects/armorplus/files/2633361)
