### ISSUE TITLE
slimeknights.mantle.util.RecipeMatch$ItemCombination cannot be cast to java.lang.Comparable

### ISSUE THREAD

**Issue by Malrama** [sokratis12GR/ArmorPlus#212]
Hello :)

When I use TinkerConstruct, Mantle and ArmorPlus the game crashes at postInit giving me this crash:

https://paste.dimdev.org/ucusumecov.mccrash

I don't know if I should report it to Mantle or ArmorPlus so I am going to report it to both of you.
If I am mistaken here, I am very sorry and this can be closed :)

Have a nice day! :3

**Comment by sokratis12GR** [comment]
Hello, please next time use the issue template.
But anyways, try to run the game without foam fix, it's been noted many times that it fixes the issue, then report it to foam fix please. Thanks

**Comment by sokratis12GR** [comment]
@Malrama could you try to run the game without FoamFix ?
