### ISSUE TITLE
Client Crash when equipping full Ultimate Armor

### ISSUE THREAD

**Issue by Seyeght** [sokratis12GR/ArmorPlus#213]
**Affected Versions (Do not use "latest"):**:
  - **ArmorPlus**: armorplus-1.12.2-11.14.0.42.jar
  - **TheDragonLib**: thedragonlib-1.12.2-5.3.0.jar
  - **Minecraft**: 1.12.2
  - **Forge**: forge-2770.jar
  - (Optional) Just Enough Items (JEI): jei_1.12.2-4.13.1.220.jar
  - (Optional) Tinkers' Construct: TConstruct-1.12.2-2.10.1.87.jar
  - (Optional) CraftTweaker (CrT): CraftTweaker2-1.12-4.1.11.jar

**Affected Side (Client or Server)**:
- [x] Client
- [ ] Server

**What happens**:
Once full Ultimate Armor is equipped it crashed the client but not the server, and corrupts the player file. 
Tested on all other armor types and no issues.

**What you expected to happen:**:
No Crash

**If its a crash, post your crash report (via. pastebin/gist/etc)**:
https://pastebin.com/JCgSqqYb

**Your configuration files from `config/armorplus/` (`registry.cfg` mainly)**:
https://pastebin.com/fRWfhyaU

**(Optional) Mod List**:
300+ mods (PO3 Development)

**Comment by sokratis12GR** [comment]
Will investigate, my apologies for the late response.

**Comment by Cazadorsniper** [comment]
happens on armorplus-1.12.2-11.15.1.44.jar too

**Comment by sokratis12GR** [comment]
Just realized the issue. Cazador have you added/changed anything about the ultimate armour ? It seems like it's effects don't have the respective number of properties
For each effect added there must be a duration and an amplifier line added. There might be one effect more `config/armorplus/registry.cfg/`
