### ISSUE TITLE
Unable to get Ore Lava Crystals from ore generators

### ISSUE THREAD

**Issue by Slyklaw** [sokratis12GR/ArmorPlus#214]
Ore generators like Environmental Tech Ore Miner and Actually Additions Atomic Reconstructor are not generating Ore Lava Crystals.

**Comment by sokratis12GR** [comment]
I cannot do anything about it. 
It might be the way they generate the ores, but I can't fix that on my side.

**Comment by Slyklaw** [comment]
Ah, gotcha, the other mods need to add the ores to their tables.
