### ISSUE TITLE
Bug when adding health boost to armor

### ISSUE THREAD

**Issue by MCEventHorizon** [sokratis12GR/ArmorPlus#216]
**Affected Versions (Do not use "latest"):**:
  - **ArmorPlus**: 1.12.2-2.0.0.2
  - **TheDragonLib**: 1.12.2-5.3.0
  - **Minecraft**: 1.12.2
  - **Forge**: 14.23.5.2811
  - (Optional) Just Enough Items (JEI):
  - (Optional) Tinkers' Construct:
  - (Optional) CraftTweaker (CrT):

**Affected Side (Client or Server)**:
- [yes ] Client
- [yes ] Server

**What happens**: If I add health boost to armor effects, the effect will tick down to 0 and remove extra hearts then add them again once the effect restarts.

**What you expected to happen:**: I thought that it was gonna be like night vision where the effect doesn't tick down, it should not remove the extra hearts when it reaches 0 and restarts the effect.

**If its a crash, post your crash report (via. pastebin/gist/etc)**:

**Your configuration files from `config/armorplus/` (`registry.cfg` mainly)**:

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
you use an Ancient version of the mod, heck that version doesn't even exist
Where did you download the mod from @MCEventHorizon ?

**Comment by sokratis12GR** [comment]
![image](https://user-images.githubusercontent.com/12274096/53029646-06696f80-3472-11e9-883f-1bc54e9d8b56.png)

**Comment by MCEventHorizon** [comment]
My mistake, it's 1.12.2-11.19.1.54, I was looking at the wrong mod.

**Comment by sokratis12GR** [comment]
Will be fixed in 1.12.2-11.19.2.55

**Comment by MCEventHorizon** [comment]
I tried version 1.12.2-11.19.2.55, still not fixed:

![bug](https://user-images.githubusercontent.com/15619786/53072908-c4c6dc00-34e6-11e9-807d-35c054cdf3d0.gif)

**Comment by sokratis12GR** [comment]
I'm terribly sorry, but I cannot seem to find a way to "fix it" in a "friendly" way without causing other issues.

**Comment by SonicX8000** [comment]
Think using a Attribute Modifier would work instead of the Health Boost Potion effect? Since when the Health Boost Potion effect refreshes it resets your health back, much like in the GIF.

EDIT
...erm, I only see Speed II on my end so I might've misread. I guess you can add in Potion effects via a config? I wonder if Attribute Modifiers could be added in. Like if instead of 'speed' I put in "generic.movementSpeed" and put down the operation & amount and when I wear that piece of armor I will get it's effect.

**Comment by sokratis12GR** [comment]
thing is, it user set effect, by default not "supported".
But yes, modifying the attribute modifiers to the player would be one way, but it could be too costly to do so. Will see if I would be able to "suppress" the chances of it breaking.
