### ISSUE TITLE
Broken credits link

### ISSUE THREAD

**Issue by Regnander** [sokratis12GR/ArmorPlus#218]
**Affected Versions (Do not use "latest"):**:
  - **ArmorPlus**: 11.20.0.56
  - **TheDragonLib**: 5.3.0
  - **Minecraft**: 1.12.2
  - **Forge**: 14.23.5.2824
  - (Optional) Just Enough Items (JEI):
  - (Optional) Tinkers' Construct:
  - (Optional) CraftTweaker (CrT):

**Affected Side (Client or Server)**:
- [x] Client
- [ ] Server

**What happens**:
The link that is supposed to take you to the translation credits is broken due to a comma at the end.

![2019-03-29_18 57 34](https://user-images.githubusercontent.com/17113053/55268080-06d20300-5287-11e9-9ab9-c7a3b10c3c50.png)

**What you expected to happen:**:
That the link would take me to "[https://github.com/sokratis12GR/ArmorPlus/blob/1.12/src/main/resources/assets/armorplus/lang/credits.md](https://github.com/sokratis12GR/ArmorPlus/blob/1.12/src/main/resources/assets/armorplus/lang/credits.md)" instead of "[https://github.com/sokratis12GR/ArmorPlus/blob/1.12/src/main/resources/assets/armorplus/lang/credits.md,](https://github.com/sokratis12GR/ArmorPlus/blob/1.12/src/main/resources/assets/armorplus/lang/credits.md,)".

**If its a crash, post your crash report (via. pastebin/gist/etc)**:
_none_
**Your configuration files from `config/armorplus/` (`registry.cfg` mainly)**:
_none_
**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
Thanks for the issue report, will check into it.

**Comment by sokratis12GR** [comment]
Will be fixed in the next release, (1.12.2-11.20.1.57).
