### ISSUE TITLE
Try to use super star bow to shoot normal arrows but error

### ISSUE THREAD

**Issue by Dogodness** [sokratis12GR/ArmorPlus#219]
**Affected Versions (Do not use "latest"):**:
  - **ArmorPlus**:1.12.2-11.20.0.56 
  - **TheDragonLib**:1.12.2-5.3.0   
  - **Minecraft**:1.12.2  
  - **Forge**:14.23.5.2811  
  -  Just Enough Items (JEI):4.15.0.269 

**Affected Side (Client or Server)**:
- [√ ] Client
- [ ] Server

**What happens**:Try to use super star bow to shoot normal arrows but error

**What you expected to happen:**:

**If its a crash, post your crash report (via. pastebin/gist/etc)**: https://pastebin.com/UWHQKMKd

**Your configuration files from `config/armorplus/` (`registry.cfg` mainly)**: default expect projectE intergration

**(Optional) Mod List**: projecte projecteintegration projectex etc.

**Comment by sokratis12GR** [comment]
Thanks for the issue report, will check into it.
For the future, please use a site like paste.ee or pastebin to post your crash log, thanks.

**Comment by sokratis12GR** [comment]
Does this happen only when using the `super star bow` or does this happen when using any of the "special" bows ?

**Comment by sokratis12GR** [comment]
Also try it without a foamfix,. If the issue persists, will see what I can do.
If it is resolved, try updating FoamFix.

**Comment by Dogodness** [comment]
I posted the newest report: https://pastebin.com/qYSC942k
 disabling foamfix and using other special bow  dosen't work

**Comment by sokratis12GR** [comment]
I'm sorry, but I cannot reproduce it.

**Comment by sokratis12GR** [comment]
Actually, thinking about this, you should update your forge to the current latest
A+ uses the better bows support from forge `14.23.5.2813`

**Comment by Dogodness** [comment]
thanks for your reply 
the newest forge is effective
