### ISSUE TITLE
Cant fly with ender dragon armor

### ISSUE THREAD

**Issue by Trnrr** [sokratis12GR/ArmorPlus#220]
**Affected Versions (Do not use "latest"):**:
  - **ArmorPlus**: armorplus-1.12.2-11.20.0.56
  - **TheDragonLib**: thedragonlib-1.12.2-5.3.0
  - **Minecraft**: 1.12.2
  - **Forge**: 14.23.5.2807
  - (Optional) Just Enough Items (JEI): 4.15.0.273
  - (Optional) Tinkers' Construct: 1.12.2-2.12.0.135
  - (Optional) CraftTweaker (CrT): 1.12-4.1.17

**Affected Side (Client or Server)**:
- [x] Client
- [X] Server

**What happens**:
It doesnt let you fly
**What you expected to happen:**:
Be able to fly
**If its a crash, post your crash report (via. pastebin/gist/etc)**:
No crash or errors in console
**Your configuration files from `config/armorplus/` (`registry.cfg` mainly)**:

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
Thanks for your issue report.
    - Are you using the full set?
    - Is flight disabled in the configuration file ?

**Comment by Trnrr** [comment]
Was using a full set and I looked and saw the enableFlightAbility is set to false in misc.conf. I will enable it and see if it works. Sorry, didn't know it was enabled by default.
