### ISSUE TITLE
Crash when Lifesteal >III

### ISSUE THREAD

**Issue by Xetaxheb** [sokratis12GR/ArmorPlus#222]
An enemy has an enchanted chest with some sort of lifesteal enchant because of another mod spawning minibosses with randomly enchanted gear. It's an issue with the mob having it (and proccing it by shooting me with an arrow), and additionally the enchant may be higher level than expected (VI-IX range).
https://gist.github.com/Xetaxheb/d9a3dc478a9f7eebf8b6cf1dc88932b7

edit: It had Lifesteal IV (4)

**Comment by sokratis12GR** [comment]
Yeah well, there is a reason we have set a limit ;)
