### ISSUE TITLE
Crash with Obsidian armor, potentially other armors too

### ISSUE THREAD

**Issue by Cazadorsniper** [sokratis12GR/ArmorPlus#224]
**Affected Versions (Do not use "latest"):**: 
  - **ArmorPlus**: 11.23.0.59
  - **TheDragonLib**: 5.3.0
  - **Minecraft**: 1.12.2
  - **Forge**: 14.23.5.2836
  - (Optional) Just Enough Items (JEI):
  - (Optional) Tinkers' Construct:
  - (Optional) CraftTweaker (CrT):

**Affected Side (Client or Server)**:
- [x] Client
- [ ] Server

**What happens**:
Game freezes when having obsidian armor in my inventory, this crash may happen with other armors as well. I suspect that I may need to regenerate the registry.cfg. Unsure if server is affected.

**What you expected to happen:**:
I expected to be able to equip the obsidian armor no problem.

**If its a crash, post your crash report (via. pastebin/gist/etc)**:
https://pastebin.com/iiEmdmRA 
**Your configuration files from `config/armorplus/` (`registry.cfg` mainly)**:

[registry.cfg.txt](https://github.com/sokratis12GR/ArmorPlus/files/3219648/registry.cfg.txt)

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
Cazador, are you sure you aren't trying to equip the experimental armors ?
- experimental.cfg (check if its enabled or not)
Experimental Armors are rather... unstable.

**Comment by sokratis12GR** [comment]
Experimental Armors have a different ToolTip when used to expand it with [default key: Shift]

**Comment by Cazadorsniper** [comment]
Ah, that is enabled, must of not disabled it after.

**Comment by sokratis12GR** [comment]
@Cazadorsniper let me know if this issue persist with the normal armors. (Shouldn't but it never hurts to be sure) [If it doesn't please close the issue]
