### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by d0ob** [sokratis12GR/ArmorPlus#229]
Hi there ! 

I'm wondering it the lava crystal can maybe be generated elsewhere / differently ?  At least optional.
I find them really missplaced, being black, on stone; could it generate along obsidian or bedrock ?
Maybe being created like obsidian is. I don't know if it's doable, but that way it's really frustrating ^^ 
But hey, it's a minor issue, I really like the mod ! Thanks.

**Comment by sokratis12GR** [comment]
Hey there, well.. there isn't an actual way other than change the Y height of the spawn and/or which dimension it can spawn via `config/armorplus/worldgen.cfg`. 

Additionally you could replace the texture if its too frustrating via a resource pack. 

Thanks

**Comment by d0ob** [comment]
Yes I lowered the spawn, I'm even arguing with myself about puting it in the nether, it's darker out there and more lava, it will be less blatant I suppose ! ^^ So it's allready pretty cool to have an extended configuration for that ! (Excellent config btw, not a lot of mod can say the same ^^) Thanks for your quick answer ! =)

**Comment by d0ob** [comment]
Oh yes, now I think of it, it maybe miss the "#default remember" ^^ just to haggle !
I'm wondering also, if I remove the overworld tower generation, but enable the "other world generation", does it mean I'll have the tower in nether / end ? It would be cool, this time too, I think it would fits better in the nether !
