### ISSUE TITLE
basic worktable not removing stuff

### ISSUE THREAD

**Issue by TheNimbleNinja** [sokratis12GR/ArmorPlus#230]
**Affected Versions (Do not use "latest"):**:
  **armorplus-1.12.2-11.26.0.64.jar**
  - **TheDragonLib**:
  - **Minecraft**:1.12.2
  - **Forge**: 14.23.5.2847

**Affected Side (Client or Server)**:
- [ ] Client client
- [ ] Server

**What happens**:
i removed items from the basic worktable and they are not being removed
**What you expected to happen:**:
gets removed
**If its a crash, post your crash report (via. pastebin/gist/etc)**:

**Your configuration files from `config/armorplus/` (`registry.cfg` mainly)**:

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
Can you send a screenshot/video evidence of how to reproduce it ?

**Comment by TheNimbleNinja** [comment]
how can i give evidence if there are no errors and it just doesnt remove the recipes

**Comment by sokratis12GR** [comment]
gif/video/screenshot proof

**Comment by TheNimbleNinja** [comment]
https://www.curseforge.com/minecraft/modpacks/project-equivalence-2-covalence-unified/files is my modpack

**Comment by TheNimbleNinja** [comment]
![steel](https://user-images.githubusercontent.com/32554596/71754881-d3dc2180-2e4d-11ea-8ee9-d2bcb17a5d15.png)
![steel rtemove](https://user-images.githubusercontent.com/32554596/71754892-df2f4d00-2e4d-11ea-9e79-a5007877ea2e.png)

**Comment by sokratis12GR** [comment]
aaah, you meant CraftTweaker

**Comment by sokratis12GR** [comment]
could you come over at http://discord.gg/ZVwmqyx to discuss this?
