### ISSUE TITLE
[1.12.2] Can't make Guardian, Superstar or Ender Dragon Tinker Parts? They also have the same stats.

### ISSUE THREAD

**Issue by SonicX8000** [sokratis12GR/ArmorPlus#231]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 5
armorplus-1.12.2-11.26.2.66
jei_1.12.2-4.15.0.291
Mantle-1.12-1.3.3.55
TConstruct-1.12.2-2.13.0.171
thedragonlib-1.12.2-5.3.0

-----

I'm aware that it's a Last Update but... despite the materials being available, they're currently impossible to make into tool parts unless you get their Tinkers Shard... which I assume is the default material if no material is set... but you only get this as leftovers from using set materials... which renders it impossible to get the shard, in short... cannot make the tools.

A look at their stats and apparently they're the same between those three materials... aka Guardian Scale, Superstar & Ender Dragon having the same stats shown below

Head
Durability: 1200
Mining Level: Cobalt
Mining Speed: 10
Attack: 7

Handle
Modifier: 1.5
Durability: 100

Extra
Durability: 200

No Traits

-----

If the above is intended, is there a way to disable the option of making these into tinker tool parts?

**Comment by sokratis12GR** [comment]
Actually you need to use the same material, no shards.. but straight up using the items together with the tool part.
Example:
Pickaxe Head Part Pattern + 2xGuardian Scale.

Also the listed above stats are intended, the only way to disable them is by disabling the entire tconstruct integration.

The materials were always supposed to have the same difficulty/tier level.

**Comment by SonicX8000** [comment]
![](https://cdn.discordapp.com/attachments/377171551155650560/673308371453214743/armorplusmaterials.PNG)
Am I doing something wrong? Superstar doesn't appear to have a material to use so I couldn't show it. What's shown in the image is Guardian Scales & Ender Dragon Scales.

![](https://cdn.discordapp.com/attachments/377171551155650560/673309226852024331/toolmaterialsbook.PNG)
Looking at the Materials and You Book... the shards inside the red outline box are the usable materials... but you only get those as leftovers from a actual usable material. Other materials... like the Compress Obsidian has a usable material set so I'm able to make tools out of them and get leftover shards if not enough was used to create the part.

**Comment by sokratis12GR** [comment]
Oh well I forgot to add the actual materials in the end.... 

Also there is no such thing as Shards... I never added any shards.. >.>

**Comment by sokratis12GR** [comment]
Time to push another update..

**Comment by SonicX8000** [comment]
The shards are actually added via Tinkers. They're leftovers from usable materials when you make a tool part.

An example is when you make a Prismarine Plate, which takes 8 Material Value so you'll need 4 Blocks of Prismarine at least... but that gives you a total of 9 Material Value... each Prismarine Block has 2.25 value. You create the Plate and are left with 2 Prismarine Shards. Each shard has a Material Value of 0.5 and since there's two shards... that's 1 Material Value leftover. Can use them for repairing tools or if you have enough shards... you can use them to create tools.

P.S.
Is the Horse Armor suppose to be uncraftable? JEI doesn't show any recipes for them.

**Comment by sokratis12GR** [comment]
Yes, horse armor can be found in dungeon chests inside the world (Strongholds, Mineshaft Chests, Temples, Mansions, Ender Cities)

**Comment by sokratis12GR** [comment]
![image](https://user-images.githubusercontent.com/12274096/73601607-37e92700-456d-11ea-819e-4c1d698819a9.png)
This should do it, also adding options to disable them individually.

**Comment by SonicX8000** [comment]
Huh... didn't think of the Wither Bone being a material for Super Star tools.

**Comment by sokratis12GR** [comment]
well, its literally the material for all of the super star equipment xD

**Comment by SonicX8000** [comment]
True, could they by any chance have traits just to have some slight difference? Though dunno what traits they would have, now thinking about it...

**Comment by sokratis12GR** [comment]
At the moment, no.. but with the update I'm adding some

**Comment by sokratis12GR** [comment]
Added traits for all of them, made them more expensive to craft:
- Guardian: depthdigger, aquadynamic, alien
- Super Star: aridiculous, alien, hellish
- Ender Dragon: enderference, alien, coldblooded

**Comment by SonicX8000** [comment]
Huh... depthdigger's a new trait. Wonder what that does.

**Comment by sokratis12GR** [comment]
![image](https://user-images.githubusercontent.com/12274096/73601811-bf846500-4570-11ea-9954-9f5904e7a995.png)
![image](https://user-images.githubusercontent.com/12274096/73601826-dc209d00-4570-11ea-8810-eda11fce9f7b.png)
![image](https://user-images.githubusercontent.com/12274096/73601827-e3e04180-4570-11ea-8c7b-a25836f361d6.png)

**Comment by sokratis12GR** [comment]
This should be fixed and updated: https://www.curseforge.com/minecraft/mc-mods/armorplus/files/2873463

**Comment by SonicX8000** [comment]
Alright, taking a look...

You left 'modifier.depthdigger.name' on the Guardian Scale Tools. Hovering over it shows 'modifier.depthdigger.desc'.

**Comment by sokratis12GR** [comment]
Its unnamed on Tinkers' Side. I'm just using already provided traits by Tinkers'.

**Comment by SonicX8000** [comment]
...oh? That's pretty interesting.
