### ISSUE TITLE
Equiping a full set of armor (same type) crashes my game

### ISSUE THREAD

**Issue by assassinwolfx27** [sokratis12GR/ArmorPlus#232]
**Affected Versions (Do not use "latest"):**:
  - **ArmorPlus**: 1.12.2-11.26.3.67
  - **TheDragonLib**: 1.12.2-5.30
  - **Minecraft**: 1.12.2
  - **Forge**:1.12.2-14.23.5.2847
  - (Optional) Just Enough Items (JEI): 1.12.2-4.15.0.287
  - (Optional) Tinkers' Construct:
  - (Optional) CraftTweaker (CrT):

**Affected Side (Client or Server)**:
- [Y] Client
- [N] Server

**What happens**: Equiping a full set of arour (same type) crashes my game 

**What you expected to happen:**:The armour to Not crash my game and give me the effects it is meant to give.

**If its a crash, post your crash report (via. [pastebin/gist/etc)**:] [https://pastebin.com/SHAzbtmX](url)

**Your configuration files from `config/armorplus/` (`registry.cfg` mainly)**:
[registry.txt](https://github.com/sokratis12GR/ArmorPlus/files/4301682/registry.txt)

**(Optional) Mod List**: JEI, HWYLA, Damage indicators mod, Blur,

**Comment by sokratis12GR** [comment]
Its not A+'s issue
Please follow up this crash report to the DamageIndicatorsMod issue page.
