### ISSUE TITLE
Infuse Lava Armor still get damaged and applies slowness effect even with config switch set to false.

### ISSUE THREAD

**Issue by LannyE** [sokratis12GR/ArmorPlus#234]
**Affected Versions (Do not use "latest"):**:
  - **ArmorPlus**:armorplus-1.12.2-11.28.0.69
  - **TheDragonLib**:thedragonlib-1.12.2-5.3.0
  - **Minecraft**:1.12.2
  - **Forge**:14.23.5.2854
  - (Optional) Just Enough Items (JEI):jei_1.12.2-4.15.0.291
  - (Optional) Tinkers' Construct:TConstruct-1.12.2-2.13.0.183
  - (Optional) CraftTweaker (CrT):CraftTweaker2-1.12-4.1.20.565

**Affected Side (Client or Server)**:
- [ ] Client
- [X ] Server

**What happens**: When wearing the full set of Infused Lava Armor when I touch water I no longer take a health hit but the slowness effect and durability damage persists.   The config file has B:enableOnWaterTouchDeBuff=false set in the lava armor section.  

**What you expected to happen:**: No debuffs to happen to the player or the armor when touching water.   As described in the config "
        # Enables/Disables the de-buffs that the armor will get when touching water without Water Breathing potion
        # a.k.a nothing happens when player wears this armor while in water."

**If its a crash, post your crash report (via. pastebin/gist/etc)**:

**Your configuration files from `config/armorplus/` (`registry.cfg` mainly)**:
[registry.zip](https://github.com/sokratis12GR/ArmorPlus/files/4654963/registry.zip)
**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
do you have that option set to false on both the server and the client ?

**Comment by LannyE** [comment]
I do not.  I just noticed that when I go into the water it brings down the durability quickly but then when I walk or randomly open the inventory screen the durability points return to normal.  The slowness debuff also never goes away it stays at 0:00.  

I will try setting the client config also and let you know.  Thanks

**Comment by LannyE** [comment]
Setting the config settings the same on both the server and the client fixed the problem.  

I am new to the modding side of Minecraft.  Is setting the config in both the client and server the same a normal procedure or in this case it works as a work around?  Thank you.

**Comment by sokratis12GR** [comment]
You always want to have the server and client configs be the same to work.
