### ISSUE TITLE
[BUG with Tinkers' Construct] Extra Modifier doesn't work

### ISSUE THREAD

**Issue by Duorhs** [sokratis12GR/ArmorPlus#235]
**Affected Versions (Do not use "latest"):**:
  - **ArmorPlus**: 1.12.2-11.28.0.69
  - **TheDragonLib**:  1.12.2-5.3.0
  - **Minecraft**: 1.12.2
  - **Forge**: 14.23.5.2854
  - (Optional) Just Enough Items (JEI):
  - (Optional) Tinkers' Construct: 1.12.2-2.13.0.183
  - (Optional) CraftTweaker (CrT):

**Affected Side (Client or Server)**:
- [√ ] Client
- [ ] Server

**What happens**:
When using the Ultimate material to add extra modifier , there is a bug:
I can get the tool in "output slot" , but nothing changed , and the material haven't been used.
I check the code and found that the extra-modifier  part was similar from the mod "tinker's addons", but a little different.
I tried to change the codes : I tried the trait of paper (writable) from tic itself and extra-modifier from tinker's addons to build a new jar but the bug is still there.

**What you expected to happen:**:
Using Ultimate Material should give 1 more extra modifier to my tool.

**If its a crash, post your crash report (via. pastebin/gist/etc)**:

**Your configuration files from `config/armorplus/` (`registry.cfg` mainly)**:

I did not edit the config at all so I think this is unnecessary maybe ?

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
You need to use 3x Ultimate Materials

**Comment by Duorhs** [comment]
> You need to use 3x Ultimate Materials

Here is an example:
![1](https://user-images.githubusercontent.com/37565352/83471074-4cefab80-a4b6-11ea-9e25-517d41c5fdf6.png)

I tried 3 materials , nothing changed , still "Modifiers : 3".
![2](https://user-images.githubusercontent.com/37565352/83471104-65f85c80-a4b6-11ea-9885-06b37c0fe2f4.png)

Even 64 materials , still the same.
![3](https://user-images.githubusercontent.com/37565352/83471152-87f1df00-a4b6-11ea-9a98-79ff7aca7a4a.png)

Somehow I put diamond and UMaterials in the slot , only Diamond modifier worked . It seemed that UMaterials didn't exist in the slot !
![4](https://user-images.githubusercontent.com/37565352/83471273-dd2df080-a4b6-11ea-9221-dec1fa805ebb.png)
![5](https://user-images.githubusercontent.com/37565352/83471279-e0c17780-a4b6-11ea-8cc7-9f494b8396c6.png)

Mods I am using with tic are : plustic and pewter , But both doesn't touch the Ultimate Materials , I tried removing these mods but still the same bug.

**Comment by sokratis12GR** [comment]
Hmm, it could be possible that the config option is set to false for mod integrations.
If that's not the case then I'm unsure.

**Comment by Duorhs** [comment]
> Hmm, it could be possible that the config option is set to false for mod integrations.
> If that's not the case then I'm unsure.

Emm...Maybe I am unlucky lol.
Nevermind , I used CraftTweaker to make an alternative way.If no other one meeting this bug maybe I can close this issue.
