### ISSUE TITLE
Server Crash when loading

### ISSUE THREAD

**Issue by Breadabix** [sokratis12GR/ArmorPlus#236]
**Affected Versions (Do not use "latest"):**:
  - **ArmorPlus**: armorplus-1.16.3-16.0.0.1
  - **TheDragonLib**: thedragonlib-1.16.3-1.0.0
  - **Minecraft**: 1.16.3
  - **Forge**: forge-1.16.3-34.1.33
  - (Optional) Just Enough Items (JEI): jei-1.16.3-7.6.0.49
  - (Optional) Tinkers' Construct:
  - (Optional) CraftTweaker (CrT):

**Affected Side (Client or Server)**: Server
- [ ] Client
- [x] Server

**What happens**: The server crashes soon after it starts loading. I tried loading with other mod and only this and thedragonlib, the server crashed only after adding armorplus.

**What you expected to happen:**: I expected the server not to crash soon after it starts loading

**If its a crash, post your crash report (via. pastebin/gist/etc)**: https://pastebin.com/RdGv1fTr

**Your configuration files from `config/armorplus/` (`registry.cfg` mainly)**: The server doesnt get far enough to generate a config file.

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
Thanks for the report, I've investigated the issue and it should be fixed now, please let me know if the issue persists:
[ArmorPlus 1.16.3-16.0.1.2](https://www.curseforge.com/minecraft/mc-mods/armorplus/files/3095544)

**Comment by Breadabix** [comment]
Issue is fixed, server loads with no issues now 👍
