### ISSUE TITLE
Crashes when using infinity bow. with or without mods

### ISSUE THREAD

**Issue by GamersAllusion** [sokratis12GR/ArmorPlus#237]
**Affected Versions (Do not use "latest"):**:
  - **ArmorPlus**:
  - **TheDragonLib**:
  - **Minecraft**:
  - **Forge**:
  - (Optional) Just Enough Items (JEI):
  - (Optional) Tinkers' Construct:
  - (Optional) CraftTweaker (CrT):

**Affected Side (Client or Server)**:
- [x] Client 
- [ ] Server - haven't tested server yet since client fails

**What happens**:
when trying to use the infinity bow with one of your modded arrows the game crashes. the game does not crash with one of the regular arrows. I first thought it might of been one of the mods that fixes/changes the infinity bow but found it still does it with just your mod installed.

**What you expected to happen:**:
without the mods - shot the arrow, lol.
with the mods - shoot infinite number of your mods arrows.

**If its a crash, post your crash report (via. pastebin/gist/etc)**:
here is the crash report with just your mod. I have also supplied 2 with mods as well just incase that comes in handy as well.

**Your configuration files from `config/armorplus/` (`registry.cfg` mainly)**:
default configuration from download

[crash-2020-10-29_15.51.08-client.txt](https://github.com/sokratis12GR/ArmorPlus/files/5460988/crash-2020-10-29_15.51.08-client.txt)
[crash-2020-10-29_15.59.35-client.txt](https://github.com/sokratis12GR/ArmorPlus/files/5460989/crash-2020-10-29_15.59.35-client.txt)
[crash-2020-10-29_15.48.09-client.txt](https://github.com/sokratis12GR/ArmorPlus/files/5460991/crash-2020-10-29_15.48.09-client.txt)

**Comment by sokratis12GR** [comment]
Oh yeah, 1.16.3's enties (including arrow entities) are not ready for use, please do not use them for the time being. Thanks for the report tho!

**Comment by GamersAllusion** [comment]
Do you have anything that list what doesn't work?
Or is just the arrows for the time being?
And arrows on general or just with infinity bow?

**Comment by sokratis12GR** [comment]
Well basically anything that is listed as WIP in the changelog: https://github.com/sokratis12GR/ArmorPlus/blob/1.16.3/src/main/resources/changelog.md

**Comment by GamersAllusion** [comment]
Alright, I'll keep it in my kids mod pack that I'm making for them now. And let you know if I come across anything else.

**Comment by sokratis12GR** [comment]
Sounds good, thanks!

**Comment by sokratis12GR** [comment]
Should be fixed in the [1.16.3-16.1.0.0 (BETA) Version](https://www.curseforge.com/minecraft/mc-mods/armorplus/files/3122846)
