### ISSUE TITLE
Crash while loading world, PO3, confirmed with A/B testing.

### ISSUE THREAD

**Issue by jonassm** [sokratis12GR/ArmorPlus#238]
**Affected Versions (Do not use "latest"):**:
  - **ArmorPlus:** 11.28.0.69
  - **TheDragonLib**: 5.3.0
  - **Minecraft:** 1.12.2
  - **Forge:** 14.23.5.2854
  - JEI: 4.16.1.302
  - Tinker: 2.13.0.183
  - CraftTweaker: 4.1.20.594

**Affected Side (Client or Server)**:
- [X] Client
- [ ] Server
*Not entirely sure

**What happens**: Crash when loading world. Did A/B testing of many individual mods, eventually narrowed down to the crash not happening when ArmorPlus is disabled. 

**What you expected to happen:**: Normal load of world

**If its a crash, post your crash report (via. pastebin/gist/etc)**: https://pastebin.com/kzR71kdx

**Your configuration files from `config/armorplus/` (`registry.cfg` mainly)**: https://pastebin.com/JHqcky8F

**(Optional) Mod List**: Project Ozone 3 - 3.3.61

Will happily provide world files or anything else that can help.

**Comment by sokratis12GR** [comment]
Interesting, I cannot see anything wrong going on.
Could you please elaborate on how the issue is occuring ?

**Comment by jonassm** [comment]
So the first time this happened i just loaded a earlier backup. I retraced my steps, one of the steps was crafting my Armor from one of the actually additions crystals to Ardite armor. This also used a extended crafting table (5x5).

EDIT: A high-tier bench, the blue one iirc, not extended crafting.

**Comment by sokratis12GR** [comment]
hmm seems to be an erroring tile entity (some item from another mod either errored out, maybe the recipe has a null/incorrect output), could you try and confirm if the issue persists on older versions of the pack ?
Also you could try and forcefully remove the erroring tile entity via a forge command/world edit/server configuration.

Thanks for the report btw.

**Comment by jonassm** [comment]
Okay i tracked down the crash.

With MCEdit i removed the blue and red tiered workbenches. Game now loaded the world fine. Replaced them ingame. Reloaded world. Crash.

EDIT: Did the same procedure with the lava infuser i had. No problems.

**Comment by sokratis12GR** [comment]
I'm sorry but I cannot reproduce this.
