### ISSUE TITLE
Save does not include armourplus:ailments

### ISSUE THREAD

**Issue by rose7524** [sokratis12GR/ArmorPlus#239]
**Affected Versions (Do not use "latest"):**:
  - **ArmorPlus**: armouplus-1.12.2-11.28.0.69.jar
  - **TheDragonLib**:
  - **Minecraft**: 1.12.2
  - **Forge**: 14.23.5.2854
  - (Optional) Just Enough Items (JEI):
  - (Optional) Tinkers' Construct:
  - (Optional) CraftTweaker (CrT):

**Affected Side (Client or Server)**:
- [x] Client
- [ ] Server

**What happens**: When I load up save it says I do not have the armourplus.ailments in the file.  I have never touched the file.

**What you expected to happen:**: Load correctly and the same as it has before.

**If its a crash, post your crash report (via. pastebin/gist/etc)**:

**Your configuration files from `config/armorplus/` (`registry.cfg` mainly)**: confic.cfg, debug.cfg, dimensions.cfg, entities.cfg, experimental.cfg, integrations.cfg, misc.cfg, registry.cfg, worldgen.cfg.

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
Right... this isn't an issue, don't worry about it.

**Comment by rose7524** [comment]
It is though because it deletes everything

**Comment by sokratis12GR** [comment]
What does it delete? In survival none of those items that use ailments are obtainable.
