### ISSUE TITLE
[Bug] Lava Crystal Ore variants drop themselves instead of the item forms.

### ISSUE THREAD

**Issue by JorgeAbrahamCh** [sokratis12GR/ArmorPlus#240]
**Affected Versions (Do not use "latest"):**:
  - **ArmorPlus**:  1.16.3-16.1.1
  - **TheDragonLib**:  1.16.3-1.1.0
  - **Minecraft**: 1.16.3
  - **Forge**: 34.1.42
  - (Optional) Just Enough Items (JEI):
  - (Optional) Tinkers' Construct:
  - (Optional) CraftTweaker (CrT):

**Affected Side (Client or Server)**:
- [x ] Client
- [ ] Server

**What happens**: I mined the Lava crystal Ore and it gave me the lava crystal ore by itself

**What you expected to happen:**: I expected to recive de lava crystal ingot

**If its a crash, post your crash report (via. pastebin/gist/etc)**: It didnt crashed

**Your configuration files from `config/armorplus/` (`registry.cfg` mainly)**:

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
Thanks for the report!
Are the stone/obsidian variants the ones that are affected?

**Comment by JorgeAbrahamCh** [comment]
The stone variants and the crying obsidian variants
The normal obsidian variant it's okay

**Comment by sokratis12GR** [comment]
Will be fixed in the next version, but I'm not sure when it will be live.

**Comment by weasel1677** [comment]
hi dear, one more bug. 1.16.3 lava infuser does not work. I put lava bucket and crystal and nothing happens

**Comment by sokratis12GR** [comment]
Hey, lava infusers is no longer the way to infuse lava crystal, instead you will need to throw them in lava, and that will infuse them.

**Comment by Shorepion** [comment]
> Hey, lava infusers is no longer the way to infuse lava crystal, instead you will need to throw them in lava, and that will infuse them.

Tested this in creative:
The 'blank' lava crystal just got burned by the lava and doesnt get infused.
If I throw a Infused Crystal into lava it doesnt get deleted and pops up.

**Comment by sokratis12GR** [comment]
> The 'blank' lava crystal just got burned by the lava and doesnt get infused.

I'm pretty sure the Lava Crystal will transform into Infused Lava Crystals when in lava, they wont pop out, so you will need to get them from the lava.

**Comment by Shorepion** [comment]
> > The 'blank' lava crystal just got burned by the lava and doesnt get infused.
> 
> I'm pretty sure the Lava Crystal will transform into Infused Lava Crystals when in lava, they wont pop out, so you will need to get them from the lava.

Did I miss something?
https://www.youtube.com/watch?v=1Ow794hUNq8&feature=youtu.be

**Comment by sokratis12GR** [comment]
This is not the lava crystal I have for 1.16.3, they don't have any tooltips.
for 1.12.2 you must use the lava infuser + lava buckets or other lava crystals to power it and infuse it.

**Comment by Shorepion** [comment]
It is.
Minecraft 1.16.3, Forge 34.1.4**1** (does the one version below have any effect on that?)
armorplus-1.16.3-16.1.1
thedragonlib 1.16.3-1.1.0

(had to make 2 screeshots because ftbchunks buttons are overlapping the mcversion)
![2020-11-30_21 53 09](https://user-images.githubusercontent.com/24994890/100663387-7c447f80-3356-11eb-9d70-01e68f2bf285.png)
![2020-11-30_21 53 13](https://user-images.githubusercontent.com/24994890/100663392-7f3f7000-3356-11eb-8b08-5673e0ebd7b6.png)

(lava infuser doesnt do anything)

**Comment by Shorepion** [comment]
Tested it in a new pack with only armorplus, jei and waila installed (see image)
![Unbenannt](https://user-images.githubusercontent.com/24994890/100666073-b6168580-3358-11eb-81b0-ffa2a53966e2.JPG)

https://youtu.be/Pd9X4TQZxxo

Somehow the Tooltips disappeared but its still not working :(

**Comment by sokratis12GR** [comment]
Interesting, will have to look more into it, thanks for the report.

**Comment by Shorepion** [comment]
> Interesting, will have to look more into it, thanks for the report.

✌
