### ISSUE TITLE
Render/animation bug

### ISSUE THREAD

**Issue by castilio20** [sokratis12GR/ArmorPlus#242]
**Affected Versions (Do not use "latest"):**:
  - **ArmorPlus**:armorplus-1.16.3-16.1.1
  - **TheDragonLib**:thedragonlib-1.16.3-1.1.0
  - **Minecraft**:1.16.4
  - **Forge**:35.1.11
 
![2020-12-30_17 24 54](https://user-images.githubusercontent.com/76228548/103363779-d5e0bc80-4a70-11eb-8a55-8e9efcaf0dc1.png)
Bow doesn't have animation for when you shoot arrow

**Comment by sokratis12GR** [comment]
Thanks for the report!
It will be fixed in one of the later versions.
