### ISSUE TITLE
Armor Table removed ?

### ISSUE THREAD

**Issue by Switch-Back18** [sokratis12GR/ArmorPlus#244]
Did you hade the armor upgrade table in a next version ?

I love this mods for that !

Thanks before !

**Comment by sokratis12GR** [comment]
1.16.3+ Is currently not containing the bigger crafting tables, and will likely not have them going further.
All crafting will be exclusively made with the help of vanilla GUIs, such as crafting table, smithing table, brewing stand recipes and in-world crafting.

**Comment by Switch-Back18** [comment]
https://www.curseforge.com/minecraft/mc-mods/extended-crafting

That works for bigger table and in 1.16

**Comment by sokratis12GR** [comment]
Well there is no real need for that. I'll close this issue now.
But if you want to chat more, or have more questions you are welcome to join our discord server, [Discord Invite](https://discord.gg/JCWbJvA)

**Comment by Switch-Back18** [comment]
Hello do change your advise for that or what frere ?
