### ISSUE TITLE
[1.16.3+] Armors that provide flight, will cause MekaSuit Bodyarmor's Gravitational Module to malfunction.

### ISSUE THREAD

**Issue by ghost** [sokratis12GR/ArmorPlus#245]
Affected Versions:
-Armor Plus version 16.1.1 (1.16.3)
-Mekanism version 10.0.18.445 (1.16.4)

Affected Side:
[x] Client
[  ] Server (unsure, have not tested).

Issue:
Armor pieces from creative flight bonus sets prevent Mekanism's Gravitational Module from functioning. If you equip a MekaSuit Bodyarmor with the Gravitational Module installed, and you equip any armor pieces from sets that will give creative flight if set condition is met (Ender Dragon armor pieces, Slayer armor pieces, etc.), the MekaSuit Bodyarmor's flight ability would immediately malfunction.

Additional Notes:
- It seems that it is regardless of which armor piece it is. It will produce the same effect whether it is leggings, boots, or helmets.
- The effect will be instantaneous. If you are flying with the MekaSuit Bodyarmor, and you equip any of the "interfering armor 
   pieces", the flight will immediately be disabled.
   - If this were to happen, the camera bugs will bug as well as it "thumps". It continuously zooms in and out. The camera effect 
     seems to be similar to if you were transitioning from walking to sprinting, and vice versa. 
   - However, if you were not on flight when you put on any of the "interfering armor pieces", the camera bug is not present, only the flight bug is.

**Comment by sokratis12GR** [comment]
Hello, apologies for the rather late reply ~~(I thought I had replied but apparently I haven't)~~.

Thanks for the report but yeah that's the side effect of using setpiece matching for the armor, once I figure out a better way to do the set matching this will be no more ^^.

**Comment by ghost** [comment]
No problem! All is good. It's honestly not a big thing, just a minor issue or something. It did make me feel like a bit of an idiot when I was standing there spamming jump trying to fly, but that's really about it. More importantly, thank you for being an amazing mod author!

**Comment by sokratis12GR** [comment]
Hello, just wanted to note that this issue will be resolved in the next ArmorPlus update 16.3.0 ^^

**Comment by sokratis12GR** [comment]
![image](https://user-images.githubusercontent.com/12274096/106146175-09e9f300-617f-11eb-97da-4375040bc0a4.png)
![image](https://user-images.githubusercontent.com/12274096/106146211-13735b00-617f-11eb-9a2c-bead8b5fbb61.png)

**Comment by ghost** [comment]
That's amazing! Thank you so much for taking the time to fix this! You are a great mod author, thank you.

**Comment by sokratis12GR** [comment]
~~Actually my bad, I don't think there is a possible fix for this when using the full set requirement, though I'll add a config option to allow "per-piece" effects, and while that is active it shouldn't interfere here.~~

**Comment by sokratis12GR** [comment]
Scratch my last message, after some trial and error, the issue has been fixed:
[Video Example](https://youtu.be/Q-TNcYR6zQ4)

**Comment by ghost** [comment]
Cool! Thank you! <3

PS, I really thought you were gonna go as far as dying from fall damage in the demonstration.

**Comment by sokratis12GR** [comment]
Haha no worries, I'll push the update in a few days as there are still some things I want to improve/change and document. ^^
