### ISSUE TITLE
Ore Lava Crystal drops two lava crystals? Bug or feature?

### ISSUE THREAD

**Issue by SpeedRunHunter** [sokratis12GR/ArmorPlus#246]
- **Minecraft**: 1.16.3
  - **ArmorPlus**: 16.2.2
  - **TheDragonLib**: 1.1.0
  - **GeckoLib**: 3.0.1
  - **Forge**: 34.1.41
  - (Optional) Just Enough Items (JEI): 7.6.0.51
  
**Affected Side (Client or Server)**:
- [x] Client
- [?] Server

**Describe the issue**: Sometimes regular Ore Lava Crystal - the non-obsidian/stone versions - will drop two Lava Crystals instead of one. On a sample scale of 35, 15 ores dropped two crystals. The obsidian or stone versions, in my testing didn't seem to do this.

**(Optional) Additional notes**: I'm unsure if this is intended or not, but I'm going to throw this out there just in case

**(Optional) The crash report (via. pastebin/gist/etc)**: No crashes experienced.

**(Optional) The config file from** `config/ap_config.toml`: No changes to the config file.

**(Optional) Mod list**: 

- Apotheosis-1.16.3-4.4.1.jar
- **armorplus-1.16.3-16.2.2.jar**
- AutoRegLib-1.6-47.jar
- BetterAdvancements-1.16.3-0.1.0.102.jar
- BiomesOPlenty-1.16.3-12.0.0.417-universal.jar
- carryon-1.16.3-1.15.1.7.jar
- cofh_core-1.16.3-1.1.6.jar
- **forge-1.16.5-geckolib-3.0.1.jar**
- FpsReducer-mc1.16.3-1.18.jar
- Hwyla-Mod-1.16.3.jar
- InventoryHud_1.16.x.forge-3.1.4.jar
- inventorypets-2.0.11.jar
- inventorysorter-1.16.1-18.1.0.jar
- ironchest-1.16.4-11.2.10.jar
- ironfurnaces-1.16.3-2.4.0.jar
- jei-1.16.3-7.6.0.51.jar
- MouseTweaks-2.13-mc1.16.2.jar
- obfuscate-0.6.0-1.16.3.jar
- OptiFine-1.16.3_HD_U_G5.jar
- pamhc2crops-1.16.3-1.0.1.jar
- pamhc2foodcore-1.16.3-1.0.0.jar
- pamhc2foodextended-1.16.3-1.0.0.jar
- pamhc2trees-1.16.3-1.0.0.jar
- Placebo-1.16.3-4.3.3.jar
- Quark-r2.4-272.jar
- randomloot-2.1.7.jar
- SimpleCoreLib-1.16.3-2.0.1.2.jar
- SimpleOres2-1.16.3-2.3.1.0.jar
- Space-Bosstools-1.16.3-3.7.jar
- **thedragonlib-1.16.3-1.1.0.jar**
- thermal_cultivation-1.16.3-1.1.6.jar
- thermal_expansion-1.16.3-1.1.6.jar
- thermal_foundation-1.16.3-1.1.6.jar
- thermal_innovation-1.16.3-1.1.7.jar
- thermal_locomotion-1.16.3-1.1.6.jar
- tl_skin_cape_forge_1.15.x_1.16.x-1.16.jar
- torohealth-1.16.3-forge-4.jar
- Waila-Harvestability-Mod-1.16.3.jar
- Xaeros_Minimap_21.0.0_Forge_1.16.5.jar

**Comment by sokratis12GR** [comment]
That's a feature added in the latest version for the *original* Ore Lava Crystal block (also affected by fortune), mentioned in the changelog ^^

**Comment by SpeedRunHunter** [comment]
hey, sorry for the late response - im not that active on github as you can see -, but thanks for the clarification. that's all i needed i guess ill close this thread now
