### ISSUE TITLE
Items aren't recognized by the /kill command

### ISSUE THREAD

**Issue by PhoenixEvolver** [sokratis12GR/ArmorPlus#247]
**Affected Versions**
  - **Minecraft**: 1.16.4 (and possibly future versions)
  - **ArmorPlus**: 1.16.3-16.2.2 (and most likely previous versions)
  - **TheDragonLib**: thedragonlib-1.16.3-1.1.0
  - **GeckoLib**: forge-1.16.4-geckolib-3.0.0 (and possibly future versions)
  - **Forge**: 35.1.20 (and possibly future versions)
  - (Optional) Just Enough Items (JEI):
  
**Describe the issue**:

When executing /kill @e[type=item] or /kill @e[type=!player], dropped armorplus items aren't recognized and require picking up and inventory clearing for full deletion.

**Comment by sokratis12GR** [comment]
That's intended.

**Comment by PhoenixEvolver** [comment]
But why?

**Comment by sokratis12GR** [comment]
It's a vanilla related feature, like how netherite works. But just in case could you list the affected items?

**Comment by PhoenixEvolver** [comment]
Well I discovered this with the Lava infused armor set, sword and bow

**Comment by PhoenixEvolver** [comment]
Update, items generated from this command aren't recognized as killable items.

/setblock ~ ~1 ~ chest[facing=north]{Items:[{Slot:10b,id:"armorplus:infused_lava_helmet",Count:1b,tag:{Enchantments:[{id:"minecraft:protection",lvl:4s},{id:"minecraft:unbreaking",lvl:3s}]}},{Slot:11b,id:"armorplus:infused_lava_chestplate",Count:1b,tag:{Enchantments:[{id:"minecraft:protection",lvl:4s},{id:"minecraft:unbreaking",lvl:3s}]}},{Slot:12b,id:"armorplus:infused_lava_leggings",Count:1b,tag:{Enchantments:[{id:"minecraft:protection",lvl:4s},{id:"minecraft:unbreaking",lvl:3s}]}},{Slot:13b,id:"armorplus:infused_lava_boots",Count:1b,tag:{Enchantments:[{id:"minecraft:protection",lvl:4s},{id:"minecraft:feather_falling",lvl:4s},{id:"minecraft:unbreaking",lvl:3s}]}},{Slot:14b,id:"armorplus:infused_lava_sword",Count:1b,tag:{Enchantments:[{id:"minecraft:sharpness",lvl:5s},{id:"minecraft:unbreaking",lvl:3s}]}},{Slot:15b,id:"armorplus:infused_lava_bow",Count:1b,tag:{Enchantments:[{id:"minecraft:unbreaking",lvl:3s},{id:"minecraft:power",lvl:5s},{id:"minecraft:punch",lvl:2s},{id:"minecraft:infinity",lvl:1s}]}},{Slot:16b,id:"armorplus:infused_lava_arrow",Count:1b},{Slot:22b,id:"minecraft:golden_apple",Count:15b}]} destroy
