### ISSUE TITLE
[1.16.5] Crash on Pack Boot

### ISSUE THREAD

**Issue by TwilightPSN** [sokratis12GR/ArmorPlus#248]
**Affected Versions (Do not use "latest"):**:
  - **Minecraft**: 1.16.5
  - **ArmorPlus**: 16.3.0
  - **TheDragonLib**: 1.1.0
  - **GeckoLib**: 3.0.13
  - **Forge**: 36.0.40
  
**Affected Side (Client or Server)**:
- [ X ] Client
- [ ] Server

**Describe the issue**: Crash on pack startup

**Additional notes**: Crash from Mekanism when Mekanism is not in the pack.

**The crash report**: https://gist.github.com/TwilightPSN/c0934c3f4611f32d0adb159e10f1acbb

**Comment by sokratis12GR** [comment]
Thanks for the issue report, there should be a quick fix for this in a bit (1.16.5-16.3.1)

**Comment by sokratis12GR** [comment]
Here is a link to the fixed version [1.16.5-16.3.1](https://www.curseforge.com/minecraft/mc-mods/armorplus/files/3205847)

**Comment by sokratis12GR** [comment]
Going to leave this open for a bit. If this crash persists after the update, please let me know.
