### ISSUE TITLE
Issues between Better Diving and Reliquary

### ISSUE THREAD

**Issue by CloWnicide** [sokratis12GR/ArmorPlus#249]
Minecraft Version: 1.16.5
ArmorPlus: 16.3.1
TheDragonLib: 1.16.3-1.1.0
GeckoLib: 3.0.14
Forge: 36.0.39
JEI: 7.6.1.71
Affected Side: Server

While having AP in the mid list, I cannot join into my singleplayer world as it crashes, but removing AP fixes the issue. Any insight into this would be appreciated.

Crashlog: https://gist.github.com/CloWnicide/e1c3d584bf0fbcdc684381c55005c99f

**Comment by sokratis12GR** [comment]
Thanks for the report, seems to be that weird issue with Reliquery once again. Absolutely no idea what's causing this.#243

**Comment by sokratis12GR** [comment]
Will be fixed in the next update.

**Comment by sokratis12GR** [comment]
ArmorPlus [1.16.5-16.4.1](https://www.curseforge.com/minecraft/mc-mods/armorplus/files/3303891) should fix this.
