### ISSUE TITLE
Client Disconnect on Lava Infused Armor Water Break

### ISSUE THREAD

**Issue by 57OH** [sokratis12GR/ArmorPlus#250]
**Affected Versions (Do not use "latest"):**:
  - **Minecraft**: 1.16.5
  - **ArmorPlus**: 1.16.5-16.3.1
  - **TheDragonLib**: 1.16.3-1.1.0
  - **GeckoLib**: 1.16.5-.3.0.15
  - **Forge**:  1.16.5-forge-36.0.41
  - (Optional) Just Enough Items (JEI): jei- 1.16.3-7.6.0.51
  
**Affected Side (Client or Server)**:
- [✓ ] Client
- [ ] Server

**Describe the issue**:
I was on a private server with just my friend and I. My lava infused armor was low enough to break, we were fighting a dungeon and when I fell in water my armor was supposed to break but instead disconnected me every time I tried to log back in until I was able to be tp'd out by my friend

**Comment by sokratis12GR** [comment]
Thanks for the report, would it be possible to send me the log file?

**Comment by 57OH** [comment]
sorry it took a while, had to recreate it :P
(server console, pretty much the same as crash log but why not include it)
[message (1).txt](https://github.com/sokratis12GR/ArmorPlus/files/6217627/message.1.txt)

and the actual log v
[latest.log](https://github.com/sokratis12GR/ArmorPlus/files/6217631/latest.log)

hope you can fix it, been loving this mod <3

**Comment by sokratis12GR** [comment]
Thanks for that! Already identified the issue, it should be fixed in the next update. (please reopen if it continues, will mention this commit once the release is live)

EDIT: It will take a few days until the update is ready for release.
