### ISSUE TITLE
Recipe of Workbench exists twice in Workbench, only one can be remove with TC integration

### ISSUE THREAD

**Issue by NeutronSelector** [sokratis12GR/ArmorPlus#252]
**Affected Versions:**:
  - **Minecraft**: 1.12.2
  - **ArmorPlus**: 11.28.0.96
  - **TheDragonLib**: 5.3.0
  - **GeckoLib**: NA
  - **Forge**: 14.23.5.2855
  - Just Enough Items (JEI): 4.16.1.301
  
**Affected Side (Client or Server)**:
- [ ] Client
- [x] Server

**Describe the issue**: The recipe for Workbench appear twice in JEI for Workbench and i can't remove both with crafttweaker integration. Only one recipe is remove. 

**My armor_plus.zs script**: 
recipes.remove(<armorplus:workbench>, false); // This work, the recipe is removed
mods.armorplus.Workbench.remove(<armorplus:workbench>); // This partially work, only one recipe is removed

**Screenshot JEI recipes**:
Without script
![image](https://user-images.githubusercontent.com/32287303/120066647-bf6a7b80-c077-11eb-858d-fce815d44a07.png)

With script
![image](https://user-images.githubusercontent.com/32287303/120066586-87633880-c077-11eb-83e0-935b0c754ff1.png)

**Mod list**: ArmorPlus, CrafTweaker, JEI.

**Comment by sokratis12GR** [comment]
Hey there, thanks for the issue report.
1.12.2 is no longer supported, but could you confirm for me that you can indeed perform the recipe even after it has been removed ?
Also have you tried removing the recipe twice from the workbench as it has 2 recipes, one with normal materials and one with dictionary.

**Comment by NeutronSelector** [comment]
Hello, thank you for your answer.
Yes, the recipe is working fine. It's not just JEI that displays the recipe while it is being deleted.
And yes, I tried to delete the recipe twice (putting the same line twice in the script) but nothing changes. The recipe still exists.
I don't have an error message in the log or in the game console.

**Comment by sokratis12GR** [comment]
Could you try removing the recipe from all locations ? (Also disable recipes from the config)

**Comment by NeutronSelector** [comment]
I found config.cfg -> global -> gameMode. I put this value to -1. Is that what you were thinking ?
If yes, it's nothing change. Unfortunately

**Comment by sokratis12GR** [comment]
there should be multiple configs, such as jsonRecipes which removes all recipes all together and replaces them with vanilla crafting table recipes.

**Comment by NeutronSelector** [comment]
Oh ! It's work !
You just had to put useJsonRecipes=true in addition to gameMode=-1
Sorry for the inconvenience and thank you for your help !

**Comment by sokratis12GR** [comment]
No worries, glad to be of help. Hope you have fun! ^^
