### ISSUE TITLE
Localization Issue causes crash

### ISSUE THREAD

**Issue by klospk** [sokratis12GR/ArmorPlus#254]
**Affected Versions (Do not use "latest"):**:
  - **Minecraft**: 1.16.5
  - **ArmorPlus**: 16.4.1
  - **TheDragonLib**: 1.1.0
  - **GeckoLib**: 3.0.45
  - **Forge**: 36.2.0 - 36.2.2
  - (Optional) Just Enough Items (JEI): 
  
**Affected Side (Client or Server)**: Client

**Describe the issue**: forge crash while loading the mods,the modpack (i made) works without it

**(Optional) Additional notes**: tried both forge 36.2.0 and 36.2.2, added and removed sodiumforge and optifine to try if the problem was them

**(Optional) The crash report (via. pastebin/gist/etc)**: https://pastebin.com/8zg1LeDb

**(Optional) The config file from** `config/ap_config.toml`:

**(Optional) Mod list**: 	Mod List: 

![](https://cdn.discordapp.com/attachments/625743469071302659/881179962017726534/unknown.png)

**Comment by sokratis12GR** [comment]
Thanks for the report, where did you download the mod from ?

**Comment by klospk** [comment]
> Thanks for the report, where did you download the mod from ?

curseforge, redowloaded,deleted the config to be sure if thats the problem,

**Comment by sokratis12GR** [comment]
Alrighty, are you using a different locale ?
Like, what language is the game on ?

**Comment by klospk** [comment]
> Alrighty, are you using a different locale ?
> Like, what language is the game on ?

i think its english but the computer itself is turkish if that changes anything

**Comment by sokratis12GR** [comment]
Okay yes thanks for that, that's the issue

**Comment by klospk** [comment]
so what to do to fix the issue other than changing the computers language?

**Comment by sokratis12GR** [comment]
[ArmorPlus 1.16.5-16.5.0](https://www.curseforge.com/minecraft/mc-mods/armorplus/files/3510935) fixes this.
