### ISSUE TITLE
ArmorPlus crashing on load

### ISSUE THREAD

**Issue by sauerkrau5** [sokratis12GR/ArmorPlus#255]
**Affected Versions (Do not use "latest"):**:
  - **Minecraft**: 1.12.2
  - **ArmorPlus**: 1.12.2-11.28.0.69
  - **TheDragonLib**: 1.12.2-5.3.0
  - **GeckoLib**: none
  - **Forge**: 14.23.5.2854
  - (Optional) Just Enough Items (JEI): 1.12.2-1.0.8
  
**Affected Side (Client or Server)**:
- [X] Client
- [ ] Server

**Describe the issue**: The crash happens while the world is loading.

**(Optional) Additional notes**: Backups are also affected. I removed ArmorPlus from the modpack and it works fine.

**(Optional) The crash report (via. pastebin/gist/etc)**: https://pastebin.com/CnCieMsx

**(Optional) The config file from** `config/ap_config.toml`: 

**(Optional) Mod list**: Project Ozone 3 from the curseforge app.

**Comment by sokratis12GR** [comment]
Will be fixed in the next release. Thanks for the issue report!

**Comment by sokratis12GR** [comment]
Thanks for the report.

Will need the configuration file(s) for that version.

Also when did this start happening?

**Comment by sauerkrau5** [comment]
It started happening yesterday after I placed the first workbench. Yesterday was also the first time I have ever used the mod. I only figured out the cause because of a vague unsolved bug complaint that suggested it was ArmorPlus.

https://pastebin.com/FpSNkz2K This is the only config file I found. There is no ap_config.toml that I could see.

**Comment by sokratis12GR** [comment]
Apologies for both the delayed answer following response but 1.12.2 is no longer supported and I couldn't replicate the issue given the parameters provided. Wont be able to assist you/fix this.
