### ISSUE TITLE
[1.16.5] 16.5.0 - Non Effect Providing Armors Throw a null effect when invoked, caused by a null effect list.

### ISSUE THREAD

**Issue by TheDarkPreacher** [sokratis12GR/ArmorPlus#256]
**Affected Versions (Do not use "latest"):**:
  - **Minecraft**: 1.16.5
  - **ArmorPlus**: 16.5.0
  - **TheDragonLib**: 1.1.0 
  - **GeckoLib**: 3.0.49
  - **Forge**: 36.2.8
  - (Optional) Just Enough Items (JEI): 7.7.1.129
  
**Affected Side (Client or Server)**:
- [X ] Client
- [X ] Server

**Describe the issue**: When updating from Smashing Mods Together version 1.0.2 to 1.0.3-hotfix on server, if a player is wearing ArmorPlus armor when connecting to server, there is a Ticking Player crash, which causes the player to never actually connect with their client.

**(Optional) Additional notes**: Smashing Mods Together version 1.0.2 uses ArmorPlus version 16.4.1, TheDragonLib v. 1.1.0, GeckoLib v. 3.0.49, and Forge 36.2.8. Issue also reported to Smashing Mods Together pack dev https://github.com/SmashingModsTogether/SMT-Issues/issues/7

**Comment by TheDarkPreacher** [comment]
Update: Latest.log from the crash

https://gist.github.com/TheDarkPreacher/9d21c1aafdddd6ea5e63909d1b8511f3

**Comment by sokratis12GR** [comment]
Hey there, thanks for your report, but I'm afraid that log report doesn't contain any information about the crash, and nothing  related to ArmorPlus.

**Comment by TheDarkPreacher** [comment]
Sorry, it was super late, had a ton of logs to go through, snagged the wrong one. This is the only crash log I can actually find on the server, since the one it says it generates in the log can't be found. https://gist.github.com/TheDarkPreacher/885c3a370bc967014066525ea073ff41

**Comment by sokratis12GR** [comment]
Thanks for that, which armor was being equipped/is affected?

**Comment by TheDarkPreacher** [comment]
The enhanced diamond armor. I made a partial set (ran out of glowstone
before I could make boots) and if I'm wearing any of it, Ticking Player
crash in 16.5.0.

**Comment by sokratis12GR** [comment]
Alrighty thanks, that shouldn't be happening considering the armor has no effects, does that happen with other armors (excluding enhanced)?

**Comment by TheDarkPreacher** [comment]
I have no idea, honestly, I hadn't had a chance to make any other sets yet.

**Comment by TheDarkPreacher** [comment]
Did some testing on a fresh server, here is the list of effected armor sets.

Enhanced Iron
Enhanced Gold
Enhanced Diamond
Enhanced Netherite
Manyullyn
Pig Iron
Cobalt

Same crash, every time, like clockwork.

**Comment by sokratis12GR** [comment]
Alrighty thanks, seems all non-effect providing gear were affected, will be fixed in the next patch.

**Comment by TheDarkPreacher** [comment]
Awesome, thanks!

**Comment by Dark-Arcana** [comment]
Thanks for the update on the issue. When your mod updates, I will update it in my pack.

**Comment by sokratis12GR** [comment]
Hey there, thanks for waiting.
[ArmorPlus 1.16.5-16.5.1](https://www.curseforge.com/minecraft/mc-mods/armorplus/files/3521227) should fix this issue.
Note: Please delete armorplus related configuration files after updating.

**Comment by Dark-Arcana** [comment]
Thanks! I'm adding this to my next update. We'll report back if there's any other issues.
