### ISSUE TITLE
Tridents summoning lightning without enchantment

### ISSUE THREAD

**Issue by Dark-Arcana** [sokratis12GR/ArmorPlus#257]
**Affected Versions (Do not use "latest"):**:
  - **Minecraft**: 1.16.5
  - **ArmorPlus**: 16.6.0
  - **GeckoLib**: 3.0.65
  - **Forge**: 36.2.26 (and lower)
  
**Affected Side (Client or Server)**:
- [ ❌ ] Client
- [ ✔️ ] Server

**Describe the issue**:

We discovered SmashingModsTogether/SMT-Issues#34 in Smashing Mods Together. Attacking using a trident causes 5 bolts of lightning to spawn on the entity being attacked. After some searching, I found that this comes from an ArmorPlus enchantment on tridents. However, this happens to all tridents even from other mods and even if they are not enchanted.

Even if you can't fix the issue itself right now, please add configuration for disabling the enchantment and its mechanics outright for now.

**Comment by sokratis12GR** [comment]
Thanks for the report, that's seems to indeed be a bug, thar effect should only be a thing when a Trident is enchanted with the "Unknown" enchant and shouldn't affect others.

**Comment by sokratis12GR** [comment]
Am currently unable to release a fix as am currently unavailable until the evening today, will release a fix asap but can't give an ETA.

**Comment by Dark-Arcana** [comment]
Thanks for responding. Don't worry, you don't have to give an eta. I'll look out for the fix!

**Comment by sokratis12GR** [comment]
[ArmorPlus 1.16.5-16.6.1](https://www.curseforge.com/minecraft/mc-mods/armorplus/files/3642182) should fix this issue.
Will be releasing a fix for the 1.18 later as well.

**Comment by Dark-Arcana** [comment]
Thanks! That's quick.
