### ISSUE TITLE
The Infused Lava Sword Bug.

### ISSUE THREAD

**Issue by Mykosayyad** [sokratis12GR/ArmorPlus#260]
**Affected Versions (Do not use "latest"):**:
  - **Minecraft**:
  - **ArmorPlus**:
  - **TheDragonLib**:
  - **GeckoLib**:
  - **Forge**:
  

[ ] Client

Issue Description:
When you get hit by a mob with the infused lava sword in your inventory, you light on fire.
The mobs light on fire when you hit them but it's also reversed so when you get hit by a mob you also light on fire.

**Comment by sokratis12GR** [comment]
Thanks for your report, but this is the intended behavior.

Ignite puts the enemey on fire (ignites it), if they collide with another entity, they will also catch fire.

**Comment by Mykosayyad** [comment]
I'm aware about the feature that makes mobs on fire light you on fire too when you collide with them but even when a mob isn't on fire and it hits me while the sword is in my inventory I get lit on fire. I hope that made it more clear :D 

Also sorry for replying to a closed ticket but I just wanted to make it more clear with what I meant.

**Comment by sokratis12GR** [comment]
Apologies for the dayl!

Will look into it and release a fix if that's the case and find a solution.

Please state the Mod's and Forge Version.

**Comment by Mykosayyad** [comment]
Forge Version: 40.1.0 
Minecraft Version: 1.18.2
Mod Version: armorplus-1.18.2-18.0.5-beta

**Comment by sokratis12GR** [comment]
Thank you, will have a look at it on Monday and might release a fix for it.
