### ISSUE TITLE
Client instantly crashes simply by interacting with the mob trophies

### ISSUE THREAD

**Issue by Asveste** [sokratis12GR/ArmorPlus#261]
**Affected Versions (Do not use "latest"):**:
  - **Minecraft**: 1.16.5
  - **ArmorPlus**: 16.7.0
  - **TheDragonLib**: 1.1.0
  - **GeckoLib**: 3.0.73
  - **Forge**: 36.2.35
  - (Optional) Just Enough Items (JEI): 7.7.1.152
  
**Affected Side (Client or Server)**:
- [X] Client
- [ ] Server

**Describe the issue**: Any sort of interaction with the Mob Trophies (in my case it was a Wither one) crashes the game. Just existing near one that lays on the ground will crash your game. If it's placed down the game works completely fine but if you break it, place it, pick it up, drop it or anything else the game will crash.

**(Optional) Additional notes**:

**(Optional) The crash report (via. pastebin/gist/etc)**: https://gist.github.com/Asveste/336a48477f7e12b971c2981c36beb3aa

**(Optional) The config file from** `config/ap_config.toml`: Nothing changed here, I only deactivated the trophies later on for obvious reasons.

**(Optional) Mod list**:

**Comment by sokratis12GR** [comment]
Thanks for the report, will try and release a few releases disabling them from the game until futher fix is made.

**Comment by sokratis12GR** [comment]
[ArmorPlus 1.18.2-18.1.0 (BETA)](https://www.curseforge.com/minecraft/mc-mods/armorplus/files/3830482) disables trophies by default for the mod.
1.16.5 will be released in a bit.

**Comment by sokratis12GR** [comment]
Upon further review, Mob Trophies will not be returning to ArmorPlus.
Latest available ArmorPlus versions:
1.18.2: [ArmorPlus 1.18.2-18.2.0](https://www.curseforge.com/minecraft/mc-mods/armorplus/files/3933975)
1.16.5: [ArmorPlus 1.16.5-16.8.1](https://www.curseforge.com/minecraft/mc-mods/armorplus/files/3860026)
