### ISSUE TITLE
Workbench crashes the game

### ISSUE THREAD

**Issue by 4b616d696c** [sokratis12GR/ArmorPlus#262]
**Affected Versions (Do not use "latest"):**:
  - **Minecraft**: 1.12.2 Optifine
  - **ArmorPlus**: 1.12.2-11.28.0.69
  - **TheDragonLib**: 1.12.2-5.3.0
  - **GeckoLib**: ??
  - **Forge**: 14.23.5.2860
  - **Just Enough Items (JEI)**: 4.16.1.302

**Affected Side (Client or Server)**:
- [ ] Client
- [x] Server

**Describe the issue**:
By leaving the workbench placed in the world, the world won't load again.

**Additional notes**:
I'm using Project Ozone 3 modpack.

By using MCEdit to remove the workbench, the world can be fixed.

Confirmed here:
https://github.com/Cazadorsniper/PO3/issues/1412
https://github.com/Cazadorsniper/PO3/issues/1260

**The crash report (via. pastebin/gist/etc)**: https://pastebin.com/kjMQYm3W

**Comment by sokratis12GR** [comment]
Hey there, thanks for the report!

Unfortunately the 1.12.2 version is no longer supported (Support stopped on May 10, 2020), following the steps shown in those issue reports should help you fix the issue.
