### ISSUE TITLE
Suggestion ( Minecraft 1.12.2 ) To make dimensions ( including vanilla dimensions ) load faster especially in big modpacks when loading world save.

### ISSUE THREAD

**Issue by Kasia1403** [sokratis12GR/ArmorPlus#268]
As above

**Comment by sokratis12GR** [comment]
Hey there, thanks for the suggestion but as it stands it's as optimized as possible currently by itself.

I can't really help with optimization for other mods or world generation.

1.12.2 is also a no longer supported version.

Have a nice day and happy holidays!
