### ISSUE TITLE
lava infuser is missing

### ISSUE THREAD

**Issue by WEEDMEN** [sokratis12GR/ArmorPlus#270]
Affected Versions (Do not use "latest"):
  - Minecraft:
  - ArmorPlus:
  - Just Enough Items (JEI):
  
Affected Side (Client or Server):
- [x] Client
- [x] Server

Describe the issue:

hello the lava infuser does not appear in version 1.19.2 neither do the workbenches and the hammer icons are invisible

**Comment by sokratis12GR** [comment]
Hey there, 1.16.5+ ArmorPlus doesn't use the workbenches neither the lava infuser.

For the recipes it uses the crafting table for basic gear and bases, smithing table for high tier equipment and world recipes for infusing
i.e:
Lava Crystal when thrown in Lava will produce an Infused Lava Crystal.
Frost Crystal when hit by lightning will produce an Infused Frost Crystal.

**Comment by WEEDMEN** [comment]
thank you very much, sorry for my confusion
