### ISSUE TITLE
Sporadic client crash on boot (java.util.ConcurrentModificationException)

### ISSUE THREAD

**Issue by evhub** [sokratis12GR/ArmorPlus#272]
**Affected Versions (Do not use "latest"):**:
  - **Minecraft**: 1.19.2
  - **ArmorPlus**: 19.1.0-beta
  - **TheDragonLib**: 1.0.0
  - **GeckoLib**: 3.1.40
  - **Forge**: 43.2.6
  - (Optional) Just Enough Items (JEI): 11.6.0.1011
  
**Affected Side (Client or Server)**:
- [x] Client
- [ ] Server

**Describe the issue**: Sporadic crash when launching client; seems to be related to ArmorPlus.

**(Optional) Additional notes**:

**(Optional) The crash report (via. pastebin/gist/etc)**: https://gist.github.com/kcwoolverton/520b330590c85c58f8a4699bc145ca8c

**(Optional) The config file from** `config/ap_config.toml`:

**(Optional) Mod list**: See crash report.

**Comment by sokratis12GR** [comment]
Hey there. thanks for the crash report, unfortunately 1.19.2 is an unsupported version due to all the changes from 1.19.2->1.19.3.
Can't recall which forge version was used at the time but that one was the latest it could support.

**Comment by sokratis12GR** [comment]
~~Reconsidering my decision, if I have more time available will fix the issues with 1.19.2.~~
