### ISSUE TITLE
[BUG] [1.16.5]

### ISSUE THREAD

**Issue by Ninjaboi875** [sokratis12GR/ArmorPlus#275]
I am a moron

**Comment by sokratis12GR** [comment]
Hello there, ArmorPlus does NOT contain chain command block armour, or anything that stops time.
It's not a bug for me, have a nice day.

**Comment by Ninjaboi875** [comment]
I wanna kill myself now

**Comment by sokratis12GR** [comment]
Please do not do that, hope you find the mod with the armour.

**Comment by Ninjaboi875** [comment]
I wont, and I did. Thanks
