### ISSUE TITLE
[BUG] [1.20.1]

### ISSUE THREAD

**Issue by Jaymus3** [sokratis12GR/ArmorPlus#276]
**Describe the bug**
Flight doesn't work for any sets of armor that are supposed to give flight.

**To Reproduce**
1.  Load up a fresh copy of Minecraft 1.20.1 with Forge, ArmorPlus, and dependencies installed.
2. Spawn in ender dragon armor.  Tap double space.
3. You do not fly.

**Expected behavior**
I expected the ender dragon armor to give creative style flight

**Affected Side (please complete the following information):**
- Yes, Client 
- Yes, Server 

**Mods (please complete the following information):**
 - Minecraft: [1.20.1]
 - Forge: [4.7.21/4.7.20]
 - ArmorPlus: [1.20.1-20.0.0]
 - TheDragonLib: [1.20.1-1.0.0]
 - GeckoLib: [4.4.4]

**Comment by sokratis12GR** [comment]
Hey there, this has been resolved.
