### ISSUE TITLE
[1.9.4] Dragon Scales fall into the portal

### ISSUE THREAD

**Issue by Carrots4U** [sokratis12GR/ArmorPlus#28]
In 1.9 the dragon always dies on top of the portal, meaning almost 100% of the time the Dragon Hide falls into the portal, going to spawn. My solution/suggestion is either make the hide go directly into the the player's inventory, or have the hide float in the air for a couple seconds like the Dragon Heart from Draconic Evolution.

**Comment by sokratis12GR** [comment]
The Ender Dragon Scales spawn right where you kill the Ender Dragon. so that means if you killed the Ender Dragon over the portal your Scales are gone.
