### ISSUE TITLE
[1.9.4] ArmorPlus 1.9.4 requires 1.10.2

### ISSUE THREAD

**Issue by Tander** [sokratis12GR/ArmorPlus#32]
ArmorPlus 1.9.4-3.1.2.0 requires Minecraft 1.10, but ArmorPlus 1.9.4-3.1.1.0 is working on Minecraft 1.9.4 as it should.

**Comment by sokratis12GR** [comment]
Confirmed.Its my mistake, going to be fixed with the same version
