### ISSUE TITLE
[1.9.4] Armor Forge/guide book ghost dupe bug

### ISSUE THREAD

**Issue by LimeTheOn** [sokratis12GR/ArmorPlus#33]
**ArmorPlus Version**:1.9.4-3.1.4.0

**MinecraftForge Version**:1987

**Client or Server?**:
- [x] Client x
- [x] Server x

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
none
**What happens / happened?**:Every time we craft an ArmorPlus item we get 2 "ghost" guidebooks laying on the ground, cant be picked up but destroy-able with lava/fire. Server or client logs doesnt state a word on whats happening and i might be wrong but i cant disable the guide book tru your configs.

**How can I reproduce it?**: Craft anything tru the forge
![2016-06-26_13 18 09](https://cloud.githubusercontent.com/assets/11951766/16361988/d7d0c612-3ba1-11e6-88ed-8212e933f93d.png)
![2016-06-26_13 27 47](https://cloud.githubusercontent.com/assets/11951766/16361989/d7d28e2a-3ba1-11e6-9861-4ec0bcc76a9f.png)

**Comment by sokratis12GR** [comment]
Confirmed.

**Comment by sokratis12GR** [comment]
Fixed ArmorPlus version 1.9.4-3.1.5.1

**Comment by LimeTheOn** [comment]
That was fast, thank you! :D Any idea when the new version could come to/be visible on curse?

**Comment by sokratis12GR** [comment]
I have pushed 2 updates, but both didn't seem to got accepted, I think that is because its Sunday

**Comment by LimeTheOn** [comment]
Possible but dont scare me like that. I was about to push my modpack as soon as i could get a hold of your mod but if sunday is a problematic time fort curse...then ill wait patiently :D

**Comment by LimeTheOn** [comment]
It got accepted! Thanks again! :D
