### ISSUE TITLE
[1.9.4] [BUG] Book crafting everytime

### ISSUE THREAD

**Issue by drakray** [sokratis12GR/ArmorPlus#34]
**ArmorPlus Version**: 3.1.5.1

**MinecraftForge Version**: 12.17.0.1990

**Client or Server?**: (SP)
- [X ] Client
- [X ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: N/a

**What happens / happened?**: Every time I craft anything, I get an ArmorPlus Book

**How can I reproduce it?**: Craft anything

**Comment by APolarBaer** [comment]
Can Confirm, since update same issue owo

**Comment by sokratis12GR** [comment]
Confirmed again... 1 miss-placed symbol = this xD

**Comment by APolarBaer** [comment]
so you found the issue then? xD

**Comment by sokratis12GR** [comment]
Fixed 1.9.4-3.1.5.2 , yeah

**Comment by APolarBaer** [comment]
sweet, now to throw away 3 stacks of books \o/ loving the mod btw

**Comment by sokratis12GR** [comment]
Now you will get the Guide Book only when you craft the Armor Forge

**Comment by LimeTheOn** [comment]
ohh i see srry for dupe report! yes we are getting them from everything quite funny :D
