### ISSUE TITLE
[1.9.4] Guide book dupe

### ISSUE THREAD

**Issue by LimeTheOn** [sokratis12GR/ArmorPlus#35]
**ArmorPlus Version**:1.9.4-1.5.1

**MinecraftForge Version**:1987

**Client or Server?**:
- [x] Client
- [x] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: 

**What happens / happened?**:Guide books are still being duped but now we get them in our inventories.

**How can I reproduce it?**: Open new world, start crafting armor soon you'll have a full inventory of guide books, maybe turn expert mode on too but i dont think it has any correlation since it was happening in easy in my previous report.

**Comment by sokratis12GR** [comment]
Duplicate of #35
