### ISSUE TITLE
[1.9.4] Support with 1.10.2

### ISSUE THREAD

**Issue by AxolotlAccount** [sokratis12GR/ArmorPlus#36]
**ArmorPlus Version**:
3.1.5.3

**MinecraftForge Version**:
forge-1.10.2-12.18.0.2002

**Client or Server?**:
- [x] Client: Yes
- [ ] Server: Not Tested

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
No crash report

**What happens / happened?**:
It says this mod needs 1.9.4/1.10 to run, not works in forge 1.10.2

**How can I reproduce it?**:
Update the mod :P

**Comment by sokratis12GR** [comment]
It is still not compatible with 1.10.2 it will be very soon

**Comment by sokratis12GR** [comment]
Version 1.9.4-3.1.6.0 supports this now
