### ISSUE TITLE
[1.9.4] Make Ore Gen Configurable

### ISSUE THREAD

**Issue by MrAmericanMike** [sokratis12GR/ArmorPlus#38]
Would it be possible to have control over the Ores World Gen?

It would be nice to be able to tweak how the Lava Crystal spawns (In what dimensions / Y level / Vein size) and all that stuff.

Personally I would like to be able to remove it from the Overworld, and make it nether only and super rare.

But the most configs we can have for this, always better for ModPack makers.

**Comment by sokratis12GR** [comment]
That's true, and this is a nice suggestion. I'll implement that after I finish my vacation

**Comment by sokratis12GR** [comment]
Added in 1.9.4-4.0.2.0
