### ISSUE TITLE
[1.9.4] A hotkey bind to toggle Nightvision

### ISSUE THREAD

**Issue by CaptainPepperjack** [sokratis12GR/ArmorPlus#40]
Hey there! 

Just a small suggestion for the Ultimate armor; the ability to toggle night vision would be really nice. Many people like to see light and dark for building where it can really make the game look better.

**Comment by sokratis12GR** [comment]
Added in version 1.9.4-4.0.3.0

**Comment by sokratis12GR** [comment]
Removed in version 1.9.4-4.0.4.0

**Comment by sokratis12GR** [comment]
**Suggestion Denied**

**Comment by sokratis12GR** [comment]
Added in ArmorPlus 1.10.2-6.0.6.0 Enjoy!
