### ISSUE TITLE
[1.9.4] Server crash (client gui key binding)

### ISSUE THREAD

**Issue by Gamerbolts** [sokratis12GR/ArmorPlus#42]
**ArmorPlus Version**: 4.0.3.0

**MinecraftForge Version**: 1.10.2

**Client or Server?**:
- [ ] Client
- [X] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: http://pastebin.com/Y9nrB6gy

**What happens / happened?**: Server crash. Keybind client gui issue

**How can I reproduce it?**: Start up armor plus on a server

Thank you

**Comment by sokratis12GR** [comment]
Confirmed.

**Comment by sokratis12GR** [comment]
Fixed in Version 1.9.4-4.0.4.0
