### ISSUE TITLE
[1.10.2] Chestplate removed at startup

### ISSUE THREAD

**Issue by kwpugh** [sokratis12GR/ArmorPlus#43]
**ArmorPlus Version**:
ArmorPlus1.9.4-4.0.4.0.jar

**MinecraftForge Version**:
2014

**Client or Server?**:
- [ ] Client
- [X ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
did not crash

**What happens / happened?**:

There are 1 missing blocks and items in this save.
If you continue the missing blocks/items will get removed.
A world backup will be automatically created in your saves directory.

Missing Blocks/Items:
armorplus:manyullyn_lhestplate

Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.

**How can I reproduce it?**:

**Comment by sokratis12GR** [comment]
This is intended, because it was a fix on a typo mistake I've made.
