### ISSUE TITLE
[1.9.4] Crash when opening the control setting menu

### ISSUE THREAD

**Issue by frank89722** [sokratis12GR/ArmorPlus#44]
**ArmorPlus Version**:4.0.5.0 and 4.0.6.0

**MinecraftForge Version**:2014

**Client or Server?**:
- [x] Client

**Crash Report (via. [Pastebin](http://pastebin.com/))**:http://pastebin.com/TpHcKLnb

**What happens / happened?**:Crash when I open the control setting menu.

**How can I reproduce it?**:Open the control setting menu.

**Comment by sokratis12GR** [comment]
Fixed in version 1.9.4-4.0.6.1 (Once Approved by curse)

**Comment by frank89722** [comment]
Thank's for your hard work ! ;)
