### ISSUE TITLE
[1.9.4] crash on startup of dedicated server

### ISSUE THREAD

**Issue by kreezxil** [sokratis12GR/ArmorPlus#45]
**ArmorPlus Version**:
1.9.4-4.1.7.1

**MinecraftForge Version**:
build 2018

**Client or Server?**:
- [x] Client
- [X] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
https://gist.github.com/e676048621890b907cc08ed5de92397e

fml server latest:
https://gist.github.com/eb1ebf961bbd72424974e333e966febf

**What happens / happened?**:
started server with your update

**How can I reproduce it?**:
start server again

**Comment by sokratis12GR** [comment]
Fixed in version 1.9.4-4.1.7.2

**Comment by sokratis12GR** [comment]
Fixed on 1.9.4-4.1.7.2  (Waiting for curse to approve it)
thanks for the reports :D
