### ISSUE TITLE
[1.9.4] Crash during Forge loading

### ISSUE THREAD

**Issue by bignate1011** [sokratis12GR/ArmorPlus#46]
ArmorPlus 1.9.4-4.1.7.1

Forge 12.18.1.2014

**Client or Server?**: SSP World

Crash Report http://pastebin.com/buHTjUkw

What happens / happened?: Game crashing on startup after updating. Disabling ArmorPlus allows me to start up.

How can I reproduce it?: Start game after updating

**Comment by sokratis12GR** [comment]
Duplicate of #45

**Comment by sokratis12GR** [comment]
Fixed in version 1.9.4-4.1.7.2

**Comment by sokratis12GR** [comment]
1.9.4-4.1.7.2
