### ISSUE TITLE
[1.9.4] Minecraft Forge crash

### ISSUE THREAD

**Issue by NoahConstrictor9** [sokratis12GR/ArmorPlus#47]
ArmorPlus Version: armorplus-1.9.4-4.1.7.1

MinecraftForge Version: 1.10-LiteLoader1.10-1.10.2-forge1.10.2-12.18.1.2011

Client or Server?: Client

Crash Report: http://pastebin.com/gDjB52ep

What happened?: Forge begins to load mods, then crashes, presumably once it begins to load Armor Plus.

How can I reproduce it?: By running Minecraft Forge with the Armor Plus (armorplus-1.9.4-4.1.7.1) in the mods folder.

**Comment by NoahConstrictor9** [comment]
Aah, never mind. Someone already reported this.

**Comment by sokratis12GR** [comment]
Duplicate of #45
