### ISSUE TITLE
[1.10.2] Crash on server start

### ISSUE THREAD

**Issue by kwpugh** [sokratis12GR/ArmorPlus#48]
**ArmorPlus Version**:
- armorplus-1.10.2-5.0.0.0.jar
- sokratiscore-1.10.2-1.0.0.jar
- WeaponsPlus1.9.4-3.0.0.0.jar

**MinecraftForge Version**:
2026

**Minecraft Version**:
1.10.2

**Client or Server?**:
- [X ] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
http://pastebin.com/raw/j9wKA4u9

**What happens / happened?**:
Server crashes when started

**How can I reproduce it?**:

**Comment by sokratis12GR** [comment]
Fixed in 1.10.2-1.0.1, thanks for the report
