### ISSUE TITLE
[1.10.2] Nightvision doesn't work on The Ultimate Armor, intended ?

### ISSUE THREAD

**Issue by GreyGardain** [sokratis12GR/ArmorPlus#50]
**ArmorPlus Version**: armorplus-1.10.2-5.0.3.1

**SokratisCore Version**: sokratiscore-1.10.2-1.0.1

**MinecraftForge Version**: 1.10.2-forge1.10.2-12.18.1.2046

**Client or Server?**:
- [ X] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:

**What happens / happened?**:
NIghtvision not working on Ultimate Armor.
**How can I reproduce it?**:
![2016-08-04_20 55 14](https://cloud.githubusercontent.com/assets/20851859/17425750/d18f73e0-5a85-11e6-95bc-be7e5059882c.png)

**Comment by sokratis12GR** [comment]
The Night Vision effect of the Ultimate Armor was removed in one of the newest versions
