### ISSUE TITLE
[1.10.2] Server crash when starting 

### ISSUE THREAD

**Issue by DadYoshi** [sokratis12GR/ArmorPlus#51]
Old config deleted, generating new world.

**ArmorPlus Version**:1.10.2-6.0.2.0

**SokratisCore Version**:1.1

**MinecraftForge Version**:1.10.2-12.18.2066

**Client or Server?**:
- [ ] Client
- [ X] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
http://pastebin.com/yH9CFDMG

**What happens / happened?**:
Server crashes when starting.

**How can I reproduce it?**:

**Comment by sokratis12GR** [comment]
uh, I did a mistake..., Thanks for the resoport! Fixed in 1.10.2-6.0.2.1
