### ISSUE TITLE
[1.10.2] Dragon Armor Recipe not showing

### ISSUE THREAD

**Issue by MrAmericanMike** [sokratis12GR/ArmorPlus#52]
B:enableEnderDragonArmorRecipes=true

**ArmorPlus Version**:
armorplus-1.10.2-6.0.4.0

**TheDragonCore Version**:
thedragoncore-1.1.0

**MinecraftForge Version**:
12.18.1.2068

**Client or Server?**:
- [x] Client
- [X] Server

**What happens / happened?**:
Recipe is gone.

**How can I reproduce it?**:
It's just not there.

**Comment by Moritz30** [comment]
Is it just not shown in JEI?

**Comment by MrAmericanMike** [comment]
Not showing on JEI and not working on the Armor Forge. Also the Forges have missing texture on Inventory

http://imgur.com/a/pUHaI

Also played around with the Advanced Tool Forge, thinking maybe the recipe was to craft there now.

**Comment by Moritz30** [comment]
The ender dragon armor can be crafted only using the Advanced Armor Forge.
I'll create a bug report at our JIRA.

**Comment by Moritz30** [comment]
I just created it. You can view the status at https://thedragonteam.atlassian.net/browse/ARMORPLUS-2 . We will also reply to this thread for updates.

**Comment by MrAmericanMike** [comment]
Do you have screenshots of the recipes?

**Comment by sokratis12GR** [comment]
opps my mistake
https://ftb.gamepedia.com/Ender_Dragon_Helmet

**Comment by sokratis12GR** [comment]
Going to be fixed in 6.0.4.1

**Comment by Moritz30** [comment]
@sokratis12GR Update it at JIRA, too, please ;)

**Comment by MrAmericanMike** [comment]
Thanks boys :D Always amazing both of you!!!

**Comment by Moritz30** [comment]
@MrAmericanMike You're welcome. If you need any other help please send an email to admin@thedragonteam.net or send a message at our support chat at https://thedragonteam.net. You can also send a chat message to the telegram bot @TheDragonTeamBot and I will reply ASAP. Facebook messenger support is comming soon, too.

**Comment by MrAmericanMike** [comment]
Just a note while you fix this. Shift+Cliking items out of the Advanced Forge, doesn't send them to player inventory but to slots on the table ;)

**Comment by Moritz30** [comment]
@sokratis12GR

**Comment by sokratis12GR** [comment]
well its minecraft bug...

**Comment by sokratis12GR** [comment]
@MrAmericanMike Also its intended in case player's inventory is full

**Comment by MrAmericanMike** [comment]
I remember doing a 5x5 crafting table in a mod I'm making and having a similar problem, I can't remember what I had to change, but I know that some number somewhere was the fix. Also, the inventory most the time will have slots availables, as you walked to the table with the ingredients, unless there was some items on the ground that you pick and they fill the inventory, in that case, the items wont do anything as they wont have where to go.
