### ISSUE TITLE
[1.10.2] Attempting to change to Easy recipes...

### ISSUE THREAD

**Issue by therealericbj** [sokratis12GR/ArmorPlus#53]
**ArmorPlus Version**: 1.10.2-6.04.1

**TheDragonCore Version**: 1.1.0

**MinecraftForge Version**: 2075

**Client or Server?**:
- [X] Client SSP
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: http://pastebin.com/26rXR1Zk

**What happens / happened?**: Game crashes on startup

**How can I reproduce it?**: 

gamemodes {
    # Sets the Recipe Difficulty 
    #0 = easy , 1 = expert
    I:recipes=0  (change from 1 to 0, game crashes everytime)

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
Thank you for the report @therealericbj , We will look into fixing having this issue fixed in the next update

**Comment by sokratis12GR** [comment]
Fixed in 1.10.2-6.0.5.0
