### ISSUE TITLE
[1.10.2] Advance Armor Forge Recipes crash client with JEI installed

### ISSUE THREAD

**Issue by psychofad** [sokratis12GR/ArmorPlus#54]
**ArmorPlus Version**:armorplus-1.10.2-6.0.5.0.jar

**TheDragonCore Version**:thedragoncore-1.1.0.jar

**MinecraftForge Version**:forge-1.10.2-12.18.1.2076

**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:[http://pastebin.com/V3k6wUED](http://pastebin.com/V3k6wUED)

**What happens / happened?**:Game crashes upon entering a world (appears to be a JEI crash but it is because of the new AdvArmorForge recipes having a duplicate key.

**How can I reproduce it?**:Load minecraft with ArmorPlus, thedragoncore, and JEI

**(Optional) Mod List**:

**Comment by therealericbj** [comment]
MinecraftForge Version:forge-1.10.2-12.18.1.2075

SSP

http://pastebin.com/eLrPXKbD

All other details, same as above...

**Comment by sokratis12GR** [comment]
Found the issue, its going to be fixed in 1.10.2-6.0.5.1  thanks for the report!
