### ISSUE TITLE
[1.10.2] Server Crash - client code on the server side

### ISSUE THREAD

**Issue by psychofad** [sokratis12GR/ArmorPlus#55]
**ArmorPlus Version**:armorplus-1.10.2-6.0.8.0

**TheDragonCore Version**:thedragoncore-1.1.0

**MinecraftForge Version**:forge-1.10.2-12.18.1.2076

**Client or Server?**:
- [ ] Client
- [x ] Server

**Crash Report (via. Pastebin(http://pastebin.com/)**: [http://pastebin.com/4WXcV7vW](http://pastebin.com/4WXcV7vW)

**What happens / happened?**: Server crashes because the mod is trying to call client side code on the server side, specifically keybindings.

**How can I reproduce it?**:load the mod on a server

**(Optional) ModPack**:

**Comment by DadYoshi** [comment]
Me too...

**Comment by ecksfiftyone** [comment]
Me too... This happens on 6.0.7.0 and 6.0.8.0. Version 6.0.6.0 works ok.

**Comment by sokratis12GR** [comment]
Alright, thanks for the report. going to be fixed asap

**Comment by sokratis12GR** [comment]
Fixed in 1.10.2-6.0.8.1, Wait for curse to approve it ^^
