### ISSUE TITLE
[1.10.2] Lava Crystals ignore Fortune. Intended behaviour?

### ISSUE THREAD

**Issue by isavegas** [sokratis12GR/ArmorPlus#56]
**ArmorPlus Version**: 1.10.2-6.0.9.1

**TheDragonCore Version**: 1.1.0

**MinecraftForge Version**:

**Client or Server?**:
- [✓] Server
- [   ] Client

**Crash Report (via. [Pastebin](http://pastebin.com/))**: N/A

**What happens / happened?**: Mining lava crystal blocks with a Fortune enabled pickaxe does not drop more than a single crystal.

**How can I reproduce it?**: Mine a lava crystal with a pickaxe that has Fortune.

**(Optional) ModPack**: All the Mods v1.22

**Notes**: Due to the gem-like nature of the lava crystals, the fact that they ignore the Fortune enchantment seems somewhat out of place. If it is intended behaviour, could a configuration option to enable similar extra drop chances to diamonds could be added?

**Comment by sokratis12GR** [comment]
intended

**Comment by sokratis12GR** [comment]
no its only supposed to give 1 lava crystal

**Comment by sokratis12GR** [comment]
- Added in 1.10.2-7.0.1.1.6
