### ISSUE TITLE
[1.10.2] JEI update crash

### ISSUE THREAD

**Issue by xbony2** [sokratis12GR/ArmorPlus#58]
**ArmorPlus Version**: 7.0.0.0

**TheDragonCore Version**: 1.0.2.0

**MinecraftForge Version**: 2084

**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/YgUGQmu5))**:

**What happens / happened?**: crashes on joining of single player world. JEI had an update, so I think that's the cause.

**(Optional) ModPack**: WikiPack 2 ofc.

**Comment by sokratis12GR** [comment]
ArmorPlus try using more latest version, it should fix the issue. ArmorPlus uses 3.10.0.262

**Comment by Morpheus1101** [comment]
I am using this mod with JEI *.268 and had no issues about 30min ago using in a SP world

**Comment by xbony2** [comment]
@sokratis12GR 268 works fine. 269 does not.

**Comment by sokratis12GR** [comment]
probably JEI change, please read changelog of it

**Comment by sokratis12GR** [comment]
v3.11.0
Close #282 Allow non-item/fluid ingredients. BIG BIG BIG refactor
Fix recipe lookups for filled fluid containers
Create zh_TW.lang (#447)
Fix Readme badge hyperlink
Make the Build status badge style match the others
Rearrange Readme badges
Add fancy Curse badges to the Readme
Add Iron Backpacks's JEI integration to ReadMe examples (#446)
Fix recipe handlers for recipes that inherit from vanilla recipe classes
Create sv_SE.lang (#440)
Create ja_JP.lang (#441)
Update ru_RU.lang (#442)
Move background texture strings to Constants
Fix #444 Crash from color search tooltip
Update ru_RU.lang (#435)

**Comment by sokratis12GR** [comment]
I'll have to check it out because their "BIG BIG refactor"

**Comment by sokratis12GR** [comment]
I reopen the issue because JEI, changed how they work on their last update

**Comment by sokratis12GR** [comment]
Fixed in a coming soon version
Update wont come until I finish the Tinkers Integration.
- just don't update to 3.11.0.269

**Comment by sokratis12GR** [comment]
I'll leave this issue open just until the version is released on curse

**Comment by sokratis12GR** [comment]
https://github.com/TheDragonTeam/ArmorPlus/blob/1.10.2/github-changelogs.md#armorplus-1102-70101-dev

**Comment by sokratis12GR** [comment]
Fixed in 1.10.2-7.0.1.0.5
