### ISSUE TITLE
[1.10.2] Crash on launch with JEI

### ISSUE THREAD

**Issue by vrork** [sokratis12GR/ArmorPlus#59]
**ArmorPlus Version**: armorplus-1.10.2-7.0.0.0

**TheDragonCore Version**:thedragoncore-1.10.2-1.0.2.0

**MinecraftForge Version**:12.18.1.2094

**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
http://pastebin.com/zp9qG259
**What happens / happened?**:
Crash when trying to load world
**How can I reproduce it?**:
Same mods, create or load world
**(Optional) ModPack**:

**Comment by sokratis12GR** [comment]
Duplicate of #58

**Comment by sokratis12GR** [comment]
Fixed in 1.10.2-7.0.1.0.5
