### ISSUE TITLE
[1.10.2] Crash when using armor forge

### ISSUE THREAD

**Issue by apnelson** [sokratis12GR/ArmorPlus#62]
**ArmorPlus Version**:
7.0.1.05
**TheDragonLib Version**:
1.0.3.0
**MinecraftForge Version**:
12.18.2.2104
**Minecraft Version**:

**Client or Server?**:
- [X] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
http://pastebin.com/gEj5hsNs
**What happens / happened?**:
Attempting to create obsidian boots. Place components in armor forge, click on crafted item to move to inventory. Client crashes immediately. See above paste bin for crash log.

**How can I reproduce it?**:
See above.
**(Optional) Mod List**:
Self-baked mod pack:
- ActuallyAdditions 1.10.2 r66
- AkashicTome 1.0 4
- armorplus 1.10.2 7.0.1.0.5
- Aroma1997Core 1.9.4 1.1.1.0
- Aroma1997s Dimensional World 1.9.4 1.2.0.2
- AromaBackup 1.9.4 1.0.1.1
- AutoRegLib 1.0 2
- Baubles 1.9.4 1.2.1.0
- BBG 1.9.4 5.0.0
- bdlib 1.12.2.14 mc1.10.2
- BetterBuildersWands 0.6.5 1.10r138+8595fc7
- BetterFps 1.3.2
- Bookshelf 1.10.2 1.4.2.327
- Bookshelf API 1.10.2 3.3.0
- Chameleon 1.10 2.1.7
- ChestTransporter 1.10.2 2.5.3
- Chisel MC1.9.4 0.0.6.51
- compactstorage 2.1 1.9.4
- CookingForBlockheads_1.10.2 4.2.16
- CraftingCraft_1.10.2 4.1.6
- CraftingTweaks_1.10.2 6.1.16
- DarkUtilities 1.10.2 1.1.4.86
- EnchantingPlus 1.10.2 4.1.0.114
- EnderCore 1.10.2 0.4.1.56 beta
- EnderIO 1.10.2 3.0.1.120_beta
- endertanks 1.10.0 1.4.2
- enderthing 1.10.2 0.7.1
- environmentaltech 1.10.2 0.10.5e
- extrautils2 1.10.2 alpha 1.1.0c
- ExtremeReactors 1.10.2 0.4.5.17
- FastLeaveDecay MC1.10.2 1.2.2
- flatcoloredblocks mc1.10 v4.2
- forestry_1.10.2 5.2.14.270
- FTBLib 1.10.2 3.0.0.4
- FTBUtilities 1.10.2 3.0.0.3
- generators 0.9.20.15 mc1.10.2
- GraveStone Mod 1.5.7
- hopperducts mc1.9.4 1.4.8
- ImmersiveEngineering 0.10 44
- ImprovedHoes 1.10.2 1.1
- InventoryTweaks 1.61 58
- ironchest 1.10.2 7.0.11.797
- jei_1.10.2 3.12.7.312
- journeymap 1.10.2 5.2.4 unlimited
- JustEnoughCalculation 1.10.2 2.1.2
- JustEnoughResources 1.10.2 0.5.1.56
- LLOverlayReloaded 1.1.0 mc[1.9 1.10.2]
- malisiscore 1.10.2 4.2.5
- malisisdoors 1.10.2 5.1.3
- Mantle 1.10.2 1.0.0
- mcjtylib 1.10 2.1.4
- MCMultiPart 1.2.1 universal
- MekanismAll 1102 921homebaked
- Morph o Tool 1.0 12
- Morpheus 1.10.2 3.1.8
- MouseTweaks 2.6.4 mc1.10.2
- natura 1.10.2 4.0.0.85
- NeoTech 1.10.2 3.3.0
- netherportalfix mc1.9.4 4.0.1
- NoMobSpawningOnTrees 1.1.7 mc[1.9.4 1.10.2]
- notenoughwands 1.10 1.3.7
- PackingTape 1.10.2 0.6.0
- Pam's HarvestCraft 1.9.4 1.10.2f
- ProgressiveAutomation 1.10.2 1.6.51
- Quark r1.0 56
- RandomThings MC1.10.2 3.7.6
- refinedstorage 1.1.3
- Reliquary 1.10.2 1.3.3.571
- rftools 1.10 5.51
- rftoolsdim 1.10 4.42
- RoguelikeDungeons 1.10.2 1.5.4
- RTG 1.10.2 4.1.1.2
- ShadowMC 1.10.2 3.4.8
- shetiphiancore 1.10.0 3.3.1
- simpleretrogen 1.10 4.0.1+8
- SleepingBag 1.10.2 1.3.0
- StorageDrawers 1.10.2 3.2.7
- TConstruct 1.10.2 2.5.5
- thedragonlib 1.10.2 1.0.3.0
- theoneprobe 1.10 1.1.5
- TinkerToolLeveling 1.10.2 0.2.0
- Torcherino 4.2s
- TrashSlot_1.10.2 6.3.6
- valkyrielib 1.10.2 0.10.5c
- VeinMiner 0.34.1 1.9r571+73be663
- Waila 1.7.0 B3_1.9.4
- WailaHarvestability mc1.10.2 1.1.9
- Wawla 1.10.2 2.3.0.206
- zerocore 1.10.2 0.0.8.0

**Comment by sokratis12GR** [comment]
fixed in 1.10.2-7.0.1.1.6
