### ISSUE TITLE
[1.10.2] Steel & Electric Steel recipe output

### ISSUE THREAD

**Issue by Iteries** [sokratis12GR/ArmorPlus#64]
**ArmorPlus Version**:  1.10.2-7.0.1.1.6

**TheDragonLib Version**:  

**MinecraftForge Version**: 1.10.2

**Minecraft Version**: 1.10.2-1.0.3.0

**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:  Non-crashing

**What happens / happened?**:  Tried making ArmorPlus steel as per FtB recipe.  No output, no steel.  Had to use command to get steel ingot & steel blocks.  Same when trying to make Electric version upgrade from plain AP recipe, get no output.
As per FtB on **Changelog 1.10.2-5.0.2.0**
    - Steel Ingot now requires (Iron Ingot + Charcoal + Lava Crystal) to be crafted

**How can I reproduce it?**:  Simple, do not use JEI or other suggested mods for making Steel. Just make Steel as per recipe via FtB.

**(Optional) Mod List**:  None listed that make steel.  Current mod list as follows:
MC:
- x64
- v1.10.2 
  Forge: 12.18.1.2076
  Optfine: 1.10.2-HD-U-C3

Mods:
- [1.10.2]Gender 1.2.7
- Armorplus 1.10.2-7.0.0.0
- AutoRegLib-1.0.2
- Backpack 3.0.1-1.10.2
- BetterArg (1.10) 0.16  -lol this one
- BetterFoliage 1.10-2.1.1
- BiomesOPlenty 1.10.2-5.0.0.2087
- Cyclic-1.10.2-1.7.13
- Dailies 1.10.2-6
- DragonMounts-r46-1.10.2 (which have a bump out on this forum)
- FinderCompass 1.10.2
- InfernalMobs-1.10.2
- IronChest 1.10.2-5.2.4
- JourneyMap - 1.10.2.5.2
- MCA-1.10.2-5.2.3-universal (which have a bump out on this forum)
- MinecraftCapes Forge 1.10.2
- MultiMine-1.10.2
- OptFine-1.10.2 HD U C3
- Pam's HarvestCraft 1.9.4-1.10.2f
- Quark-r1.0-56 (currently looking for this on BDCraft)
- RadixCore 1.10.2-2.1.3
- RikMuldsCore 1.2e-1.10.2
- RoguelikeDungeons 1.10.2-1.5.4
- Ruins 1.10.2
- Ruins 1.10.2-sources
- SoundFilters 0.9 for 1.9.4 t 1.10
- TheCampingMod 2.3d-1.10.2
- TheDragonCore 1.10.2-1.0.2.0

Resources:
- Better Agriculture 1.10 Sphax x64
- Camping Mod BDCraft Patch
- Sphax-Harvestcraft 1.9.4-1.10.2-64xA
- Shpax-IronChest x64
- Sphax64x-BOP-Ver5.0.0.2080
- Sphax_BetterFoliage x64
- PureBDcraft Customisation MC110
- PureBDcraft 64x MC110

**Comment by sokratis12GR** [comment]
Thanks for the report!
were have you tried to make the steel? on the Armor Forge ?
also the recipe is:
Iron Ingot + Charcoal + Charged lava Crystal
Please let me know if that fixes the issue
Also what does ""Tried making ArmorPlus steel as per (FtB recipe)" means ?

**Comment by sokratis12GR** [comment]
hmm, most of the recipes in the FTB Wiki for ArmorPlus are outdated, I plan on updating them after I finish the upcoming update which will change recipes for last time _for 1.10.2 at least_.

**Comment by Iteries** [comment]
Whew, thanks and I did try both with normal lava crystals,.. but charged I feel dumb on in not thinking clearly (too many hours playing)   I can get to making the steel Ingot but no table will make steel blocks as I am on normal survival mode.   As for Electric Steel that not working with redstone & glow-dust on any table.  
Recipes: I been using another site for weapons recipes, the old... weapons plus out there.

**Comment by sokratis12GR** [comment]
well, steel blocks are made on the crafting table, electrical ingots are made using steel ingot & redstone & glowstone on the armor forge
WeaponsPlus the mod is integrated in ArmorPlus so please I highly suggest not using the WeaponsPlus mod it self because its outdated and not supported

**Comment by Iteries** [comment]
I understand that about the integration of WeaponsPlus, just saying _using the old recipes_ since FtB is not updated to reflex them all.  Still, blocks are not being made at all. Steel Ingots are fine but No steel_block recipe on armor forge or crafting tables. The electrics ingots and its blocks are not working, period.  I did use the above mentioned recipe too on the armor forge then crafting table itself = nothing made.

**Comment by sokratis12GR** [comment]
I see you reported "Armorplus 1.10.2-7.0.1.1.6" but you listed "Armorplus 1.10.2-7.0.0.0" in the mod list
Have you tried both versions ? and/or tried deleting the old config,

I think your issue might be that you don't have tesla installed

**Comment by sokratis12GR** [comment]
yeah... my mistake, you need tesla installed in the current versions to make the block's recipes to work... I forgot to remove the `if`` statement

**Comment by sokratis12GR** [comment]
it will be fixed in the upcoming update. sorry for that

**Comment by Iteries** [comment]
Yeah, did delete the old config.  Tesla??  Only thing I see is red info letter on those energy items, guessing another craft table?

**Comment by sokratis12GR** [comment]
no no, you need to have Tesla installed
here is a link to it: https://minecraft.curseforge.com/projects/tesla

**Comment by sokratis12GR** [comment]
there is a "Tesla Rod" that is warning the players about the tesla tools recipes, and because Steel Armor was working on tesla I had forgotten to remove the `if` statement

**Comment by Iteries** [comment]
nah, I can do without that mod.  I prefer more middle-ages rpg styles (D&D), getting into tech is meh.  I don't even use redstone all that much and thought these RF redstone be interest, guess not.

Thank you for being responsive to this.

**Comment by sokratis12GR** [comment]
fixed for the up coming update, just that it can take a while until the update is released, thanks for reporting it.
