### ISSUE TITLE
CraftTwaker/MineTweaker3 support

### ISSUE THREAD

**Issue by sokratis12GR** [sokratis12GR/ArmorPlus#65]
I want people to be able to use MineTweaker to tweak, add, remove recipes from my benches.
The thing is I've tried but yet haven't succeed to make them work
If anyone could help me fix it, please I would really appreciate it!

[Link to how I tried making the support](https://github.com/TheDragonTeam/ArmorPlus/tree/1.10.2/src/main/java/net/thedragonteam/armorplus/compat/tweaker)

[Link to where I register the classes](https://github.com/TheDragonTeam/ArmorPlus/blob/1.10.2/src/main/java/net/thedragonteam/armorplus/proxy/CommonProxy.java#L79L84)

**Comment by Michael-Jouanneau** [comment]
i'm going to take a look at the code and see what's going on with the code.

**Comment by sokratis12GR** [comment]
Not going to happen any time soon, sorry
