### ISSUE TITLE
[1.10.2] Armorplus taking up a large amount of space in the texture atlas

### ISSUE THREAD

**Issue by Maluscat** [sokratis12GR/ArmorPlus#66]
**ArmorPlus Version**: 1.10.2-7.0.1.1.6

**TheDragonLib Version**: 1.10.2-1.0.3.0

**MinecraftForge Version**: 12.18.2.2112

**Minecraft Version**: 1.10.2

**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: /

**What happens / happened?**: Using Mezz's new texturedump mod I've found out that armorplus takes up a very large amount of space in the texture atlas which obviously affects the memory usage. (EDIT: See Mezz's comment below for the texture atlas)

**How can I reproduce it?**: Go to the texturedump github and download the mod. After putting it in your mods folder, start up minecraft and look at the texturedump files in the texturedump folder of the modpack once minecraft has started

**Comment by mezz** [comment]
https://github.com/mezz/TextureDump

![textures_mipmap_1](https://cloud.githubusercontent.com/assets/916092/19671476/d6c793be-9a23-11e6-8301-cccca977813d.png)

**Comment by Maluscat** [comment]
Derp. Thanks :D

**Comment by sokratis12GR** [comment]
![image](https://cloud.githubusercontent.com/assets/12274096/19676164/3a4aa33c-9a9b-11e6-8f35-33e8d1fca03d.png)
thanks for the info! I actually didn't know that they affect memory usage, they are going to be resized and fixed for the next release, thanks ! :)

**Comment by sokratis12GR** [comment]
![textures_mipmap_0](https://cloud.githubusercontent.com/assets/12274096/19742860/891c7762-9bcf-11e6-8697-0fed14eda5fd.png)

**Comment by sokratis12GR** [comment]
the upcoming update will have this fixed in. just that it can take some time until the next update, I have more things to work on :)
the update will be most likely 1.10.2-8.0.0.2

**Comment by sokratis12GR** [comment]
I'll keep it open until I release the version with the fix

**Comment by sokratis12GR** [comment]
Update 8.0.0.6 is being uploaded to curseforge, issue fixed thanks for the report :)

**Comment by sokratis12GR** [comment]
https://minecraft.curseforge.com/projects/armorplus/files/2343391 have fun :)
