### ISSUE TITLE
[1.10.2] issues using jei *.2.349 and later

### ISSUE THREAD

**Issue by SDUBZ** [sokratis12GR/ArmorPlus#69]
**ArmorPlus Version**:
1.10.2-7.0.1.1.6
**TheDragonLib Version**:
-1.10.2-1.0.3.0
**MinecraftForge Version**:
build-2120
**Minecraft Version**:
1.10.2
**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
[fml-client-latest (1).txt](https://github.com/TheDragonTeam/ArmorPlus/files/570939/fml-client-latest.1.txt)

**What happens / happened?**:
loaded up fine but upon entering a world the game froze up and errored out
**How can I reproduce it?**:
load up with  jei_1.10.2-3.13.2.349 and the version shown of armorplus/thedragonlib
**(Optional) Mod List**:
all the other mods i use in my pack https://minecraft.curseforge.com/projects/sdubzskycraft

**Comment by sokratis12GR** [comment]
I'll look into that and have it fix with the upcoming update but honestly jei updates too quickly...

**Comment by SDUBZ** [comment]
yeah :D but i always like the new fixes and tweaks

**Comment by sokratis12GR** [comment]
this version broke mostly my integration to jei...

**Comment by SDUBZ** [comment]
well we all gotta adapt eventually right?

**Comment by sokratis12GR** [comment]
I'm trying to keep-up with jei versions, and I'll fix it but if jei changes entirely, I wont be supporting it for a while

**Comment by sokratis12GR** [comment]
I'll keep it open until I release the version with the fix

**Comment by SDUBZ** [comment]
a bit good/bad news for you world loads fine on jei_1.10.2-3.13.2.357 but some recipes arent showing now

**Comment by sokratis12GR** [comment]
Well I fixed the issue, which was causing all problems with latest jei, but I wont close this until I release the fix

**Comment by SDUBZ** [comment]
oh okay thanks man :D i really appreciate it man, does that fix show all basic armor forge recipes because it already shows the advanced forge armor recipes

**Comment by sokratis12GR** [comment]
well armor forges will be called benches, armorforge -> workbench, adv armor forge -> high-tech bench and an Ulti-Tech Bench, and yes it fixes all recipe issues

**Comment by SDUBZ** [comment]
nice i was just curious

**Comment by DaFuJosh** [comment]
found fix downgrade jei to jei_1.10.2-3.13.1.346

Fixs recipes

**Comment by SDUBZ** [comment]
not a fix if you have refined storage that requires 348+

**Comment by SDUBZ** [comment]
just a question i was wondering when the new version will be available ?

**Comment by sokratis12GR** [comment]
soon, meanwhile the dev not available on curseforge versions can be found here:
https://github.com/TheDragonTeam/ArmorPlus#download
this issue is fixed with version 8.0.0.5 (not released publicly, there are still some things left to be done)

**Comment by szock** [comment]
I installed version 8.0.0.5 with the latest version of jre and can confirm that it works. Minor bug: workbench is placed facing away from you, rather that towards you.

**Comment by sokratis12GR** [comment]
hmm its intended and not an actual bug :)

**Comment by SDUBZ** [comment]
well thats sad to hear because my skyblock pack will just have to wait to update then because curse wont allow me to include the file if its not curseforge sadly :/

**Comment by sokratis12GR** [comment]
luckily I'm nearly done with the update, just a few things here and there left, it would be available before next week

**Comment by SDUBZ** [comment]
oh well thats better to hear sometimes i like curse and then you get those times when you have to wait for official releases and stuff

**Comment by sokratis12GR** [comment]
Update 8.0.0.6 is being uploaded to curseforge, issue fixed thanks for the report :)

**Comment by sokratis12GR** [comment]
https://minecraft.curseforge.com/projects/armorplus/files/2343391 have fun :)
