### ISSUE TITLE
[1.9] Crafting anything gets enchanted with Unbreaking III

### ISSUE THREAD

**Issue by Melakion** [sokratis12GR/ArmorPlus#7]
Something wrong with your crafting event handler. Crafting anything enchants the result with Unbreaking III. 

MC 1.9 - Forge 1849 -  ArmorPlus1.7.13(1.9)

**Comment by TehNut** [comment]
These 2 lines are not in an `if` statement. https://github.com/sokratis12GR/ArmorPlus/blob/master/src/main/java/sokratis12GR/ArmorPlus/resources/GlobalEventsArmorPlus.java#L26-L27

**Comment by sokratis12GR** [comment]
Thanks you for the report.
 I saw it. and I fixed it, give me a second Pushing
