### ISSUE TITLE
[1.10.2] Issue (Need Details)

### ISSUE THREAD

**Issue by DaFuJosh** [sokratis12GR/ArmorPlus#70]
**ArmorPlus Version**:

**TheDragonLib Version**:

**MinecraftForge Version**:

**Minecraft Version**:

**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:

**What happens / happened?**:

**How can I reproduce it?**:

**(Optional) Mod List**:

tinkers construct and lava crystals not showing recipes jei_1.10.2-3.13.1.346
                                                                                                      ^ Fixes armor forge^
 
but still not show smelty recipes for them

**Comment by sokratis12GR** [comment]
You mean the lava crystal material integration to tinkers construct ?

**Comment by sokratis12GR** [comment]
More details please

**Comment by sokratis12GR** [comment]
Closing this issue until more details are provided
