### ISSUE TITLE
[1.10.2] Crash with enchant

### ISSUE THREAD

**Issue by RayzoRayy** [sokratis12GR/ArmorPlus#72]
**ArmorPlus Version**:
1.10.2-7.0.1.1.6
**TheDragonLib Version**:
1.10.2-1.0.3.0
**MinecraftForge Version**:
12.18.2.2122
**Minecraft Version**:
1.10.2
**Client or Server?**:
- [X] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
http://pastebin.com/8gvrFtEh
**What happens / happened?**:
Game crashes to desktop when I try and place an Unbreaking enchantment on the Ender Dragon Battleaxe. I can place it on the Lava Bow, and other items from Armor Plus, but seems to crash with the Ender Dragon Battle axe.
**How can I reproduce it?**:
Do what I did on my modpack I guess?
**(Optional) Mod List**:
https://minecraft.curseforge.com/projects/imaginable-potential-2/files

Latest version of my modpack

**Comment by sokratis12GR** [comment]
Let me look into this

**Comment by sokratis12GR** [comment]
This issue has been fixed in 8.0.0.6 (Latest release of the version)
