### ISSUE TITLE
Crash on Startup: Server Tick Loop

### ISSUE THREAD

**Issue by seanimusprime** [sokratis12GR/ArmorPlus#73]
**ArmorPlus Version**:
armorplus-1.10.2-8.0.0.6

**TheDragonLib Version**:
thedragonlib-1.10.2-1.0.3.0

**MinecraftForge Version**:
1.10.2-12.18.2.2122-universal

**Minecraft Version**:
1.10.2

**Client or Server?**:
- [ ] Client
- [x] Server

**Crash Report (via. [Pastebin](http://pastebin.com/4eDPU4wX))**:
http://pastebin.com/4eDPU4wX

**What happens / happened?**:
Server starts up and crashes after a few seconds.

**How can I reproduce it?**:
Start up server

**(Optional) Mod List**:
AutoRegLib (by Vazkii)
Forge Creeper Heal (by FRA_EyZox)
Backpacks (by Eydamos)
BetterFps (by Guichaguri)
Better Agriculture (by knoxhack)
ArmorPlus (by Moritz30)
Custom Mob Spawner (by DrZhark)
Biomes O' Plenty (by Glitchfiend)
Crafting Tweaks (by BlayTheNinth)
Ender Zoo (by CrazyPants_MC)
Mo' Creatures (by DrZhark)
Graves (by fireball1725)
Forestry (by SirSengir)
Inventory Tweaks (by Kobata)
Just Enough Resources (JER) (by Way2muchnoise)
Levels (by TheXFactor117)
Just Enough Forestry Bees (JEFB) (by MrDimkas_Studio)
LLibrary (by iLexiconn)
Minecraft Comes Alive (MCA) (by WildBamaBoy)
No Mob Spawning on Trees (by oldjunyi)
Ocean Floor - Clay Sand and Dirt (by Lothrazar)
Quark (by Vazkii)
Pam's HarvestCraft (by MatrexsVigil)
RadixCore (by WildBamaBoy)
Terrain Crystals Add-ons (by BaileyHoll)
Terrain Crystals (by BaileyHoll)
Vanilla Magic (by seia6666)
TheDragonLib (by Moritz30)
Waila (by ProfMobius)
ViesCraft - Airships! (by Viesis_Gaming)
Fullscreen Windowed (Borderless) for Minecraft (by hancin)
Neat (by Vazkii)
BetterAchievements (by Way2muchnoise)
WTF's Expedition: CaveBiomes, Ores, Trees, and Tweaks (by WhiskytangoFox)
Chunk Animator (by lumien231)
Better Foliage (by octarine_noise)
HempFarmer (by SeqSee)
VeinMiner (by Portablejim)
JourneyMap (by techbrew)
Cavern (by _kegare)
Railcraft (by CovertJaguar)
Dramatic Skys (by thebaum64)
MalisisCore (by Ordinastie)
MalisisDoors (by Ordinastie)
MalisisBlocks (by Ordinastie)
McJtyLib (by McJty)
RFTools (by McJty)
RFTools Dimensions (by McJty)
Industrial Craft (by Player)
(Chat) Ping! (by TheSatanicSanta)
stimmedcow : NoMoreRecipeConflict (by Oliv1er)
TrashSlot (by BlayTheNinth)
CraftTweaker (by jaredlll08)
MineTweaker RecipeMaker (by DoubleDoorDevelopment)
Just Enough Items (JEI) (by mezz)

**Comment by sokratis12GR** [comment]
Thanks for the report
Fixed in 1.10.2-8.0.1.7
