### ISSUE TITLE
[1.10.2] Superstar Armor Regen Effect not working

### ISSUE THREAD

**Issue by ghost** [sokratis12GR/ArmorPlus#74]
**ArmorPlus Version**: 1.10.2-7.0.1.1.6

**TheDragonLib Version**: 1.10.2-1.0.3.0

**MinecraftForge Version**: 12.18.2.2116

**Minecraft Version**: 1.10.2

**Client or Server?**:
- [ ] Client
- [x] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:

**What happens / happened?**: the Superstar Armor Effect Does not work properly due to instant duration resets (heal ticks missing)

**How can I reproduce it?**: wear the armor and watch the hp

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
This is a known issue, I still haven't figured out how to fix it sorry

**Comment by ghost** [comment]
maybe you could add a wait timer of 5 seconds after each reset?
this could help with that

**Comment by sokratis12GR** [comment]
I'll try somethings out to fix this issue, I'll do my best

**Comment by sokratis12GR** [comment]
Fixed the issue :)
1.10.2-8.0.4.10
