### ISSUE TITLE
[1.11] Crafting Recipes aren't working

### ISSUE THREAD

**Issue by redo6565** [sokratis12GR/ArmorPlus#78]
can not craft items in the MC  1.11 version of the mod

**Comment by sokratis12GR** [comment]
yeah, its in alpha and I mentioned crafting wont work

**Comment by redo6565** [comment]
honestly dont see anywhere that is says that

**Comment by sokratis12GR** [comment]
![image](https://cloud.githubusercontent.com/assets/12274096/20466359/a862ff88-af7a-11e6-9f3a-1fbfa2b19f9c.png)

**Comment by redo6565** [comment]
nevermind curse app is showing the 1.11 update change log.. sorry :)

**Comment by sokratis12GR** [comment]
np :)
