### ISSUE TITLE
[1.10.2] como usar armor plus mod con tinkers

### ISSUE THREAD

**Issue by kingred126** [sokratis12GR/ArmorPlus#83]
ArmorPlus Version: 1.10.2

TheDragonLib Version: 1.10.2

MinecraftForge Version: actual

Minecraft Version: 1.10.2

Client or Server?:

    Client   clkiente
    

Crash Report (via. Pastebin):

What happens / happened?:
hola mira estoy jugando pero al querer usar lava cristal con tinkers no se funde o no se pueden construir cosas no hay receta del tinkers para el lava cristal o como usas el lava cristal con el tinkers  como se hace el molten lava cristal o como se usa armor plus con tinkers

![lava](https://cloud.githubusercontent.com/assets/24559808/21169952/73417adc-c186-11e6-9a42-87dcdbceff97.jpg)

How can I reproduce it?:

(Optional) Mod List:

**Comment by sokratis12GR** [comment]
Hey, I made a small gif that shows you how to make it:
https://sokratis12gr.com/uploads/AWBQ0Zt2.webm

**Comment by kingred126** [comment]
gracias

**Comment by kingred126** [comment]
por respondermr
