### ISSUE TITLE
Need Info!

### ISSUE THREAD

**Issue by dpickett2001** [sokratis12GR/ArmorPlus#85]
The info book dosnt work and i cant find any guide on how to craft anything online. this sucks because i started a survival world with this mod and would really like to utilize some of its features

**Comment by sokratis12GR** [comment]
The info book in 1.11 or 1.10.2 ?
on both versions it just gives information about the difficulty of recipes they are in... I'd recommend using [JEI](https://minecraft.curseforge.com/projects/just-enough-items-jei) so you'd be able to look up some of the recipes (not yet in 1.11) and the items themselves.
Soon I'll update the official wiki page or create an in game documentation. I just don't have the time to do them.

**Comment by dpickett2001** [comment]
1.11 and im using JEI but none of the recipes show up except the ones for the book and what recipies i COULD find online like for coal armor and such wont work.

heres a list of mods i have just incase one one of them isnt compatable.

Dense ores
JEI
More furnaces 
Iron chests
Gravestone
TESLA

**Comment by sokratis12GR** [comment]
My apologizes, I'll do my best to have try and update the [wiki](https://ftb.gamepedia.com/ArmorPlus) with the newest recipes

**Comment by dpickett2001** [comment]
the update posted yesterday fixed most of the issue because now the workbench recipe shows up on JEI but the armor recipes do not, most of them are common sense but some of them like the Knight slime set still wont show up

also no need to apologize im sure theres alot of behind the scenes work that i couldnt ever do myself

**Comment by dpickett2001** [comment]
how to craft hi-tech bench and champion bench those are the only two recipies that still dont work

**Comment by sokratis12GR** [comment]
you can't craft the champion bench. I added JEI integration so you can look up recipes.
Soon I'll implement In-Game Documentation.
For now I'll consider this for resolved
