### ISSUE TITLE
[1.10.2] Ender Dragon Scales don't drop from Ender Dragon

### ISSUE THREAD

**Issue by DoomSquirter** [sokratis12GR/ArmorPlus#87]
armorplus-1.10.2-8.2.3.4

killed dragon, got no ender dragon scales from it.  

I see the config entry:
    enderdragon {
        # Set the amount of dropped Ender Dragon Scales that the Ender Dragon will drop
        I:enderdragonScaleDropAmount=12
    }

bug? or is it rng?

**Comment by DoomSquirter** [comment]
followup.  resurrected dragon, killed it, got 12 dragon scales as I should have.  this is in SSP.   Note that the first dragon that didn't drop scales was the first dragon I killed in this map.

**Comment by sokratis12GR** [comment]
This issue has been happening for some people, this is actually a Minecraft bug somehow but I need more information like:
* Where you killed the Ender Dragon ?
* How you killed the Ender Dragon ?

**Comment by DoomSquirter** [comment]
Sure, will try to help anyway I can.  
* Killed the dragon near the end portal.  when it died, it did screw up the death sequence and while dying and after I heard the roar, it was still flying towards end portal, possibly to dragon breath(?)
* bow and sword.  Killing blow was sword.  iirc, it went to dragon breath when I killed it.
* the first time which did not give scales, killed with same sword as second time.
* second kill which did drop scales, was near end portal but almost on top of it.  I did not get the wierd death sequence that time, which makes me wonder if that was the cause.

I am using quantum flux magnet which is an instant magnet, but after the first death and no scales, I went home and then back to spawn immediately in case something fell through the portal but nothing.

**Comment by sokratis12GR** [comment]
This issue has been there for a long time. And here are the most common situations:
* The Drops got deleted by the End Portal.
* The Ender Dragon knocked the Drops away.
* The drops weren't dropped cause a weird death, which didn't trigger the event (like in your case).

**Comment by sokratis12GR** [comment]
I've got no clue how I can resolve it tho.

**Comment by DoomSquirter** [comment]
it's no big deal really then.  might be a forge issue too that might eventually get resolved on it's own.

I enabled the ender dragon zombies (which by default were disabled) in the end, so just been hunting them to get drops, etc.  as long as it isn't a single unique thing that has a low chance of spawning cause of a bug, I wouldn't worry about it then.  close this if you want.  thanks
