### ISSUE TITLE
Crash report on minecraft start up

### ISSUE THREAD

**Issue by THEAN2403** [sokratis12GR/ArmorPlus#88]
**ArmorPlus Version**:1.11.2-9.4.0.1-beta

**TheDragonLib Version**:1.11-2.0.1

**MinecraftForge Version**:1.11.2-13.20.0.2205

**Minecraft Version**:1.11.2

**Client or Server?**:
- [teamextreme 3.6.1 ] Client
- [asia ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:

**What happens / happened?**:when I update my armorplus mod or download a new one and play it start crashing my game evey start up. I guess it's because of new added things

**How can I reproduce it?**:fix some bugs or fix the mod

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
@THEAN2403 I'll close this issue until you could provide me a little more information such as:
* Crashlog
* Modlist (this time I need it)
* Try to be a little more helpful, so I can fix the bug if there is even any ;)

**Comment by THEAN2403** [comment]
wait I can give you a evidence pls

and I'll make a video so you can see it more clearly

**Comment by THEAN2403** [comment]
sorry you can cancel it. the offline skin mod is the one that's crashing my
game.
but thank you for the support!
