### ISSUE TITLE
[1.10.2] Steel Armor pieces in JEI dont show full durability

### ISSUE THREAD

**Issue by Morpheus1101** [sokratis12GR/ArmorPlus#89]
**ArmorPlus Version**: 1.10.2-8.3.0.1

**TheDragonLib Version**: 1.10.2-1.0.3.0

**MinecraftForge Version**: *.2202
**Minecraft Version**: 1.10.2

**Client or Server?**:
- [x] Client

**Crash Report (via. [Pastebin](http://pastebin.com/))**: N/A

**What happens / happened?**: All Steel armor in JEI shows 1 less durability under full

**How can I reproduce it?**: look up any steel armor piece in JEI

**Comment by sokratis12GR** [comment]
That's not a bug, it is intended
