### ISSUE TITLE
Crafting doesn't work on High-Tech Bench

### ISSUE THREAD

**Issue by jaceiskool11** [sokratis12GR/ArmorPlus#91]
**ArmorPlus Version**: armorplus-1.11.2-9.4.1.2-beta

**TheDragonLib Version**: thedragonlib-1.11.2-2.1.0

**MinecraftForge Version**: 1.11.2-forge1.11.2-13.20.0.2224

**Minecraft Version**: 1.11.2

**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:

**What happens / happened?**: I can try any recipe that uses the High-Tech Bench and none of them will work.

**How can I reproduce it?**:

**(Optional) Mod List**: Optifine, Simple Teleporters, treechopper

**Comment by sokratis12GR** [comment]
Closing until more information is provided.
I can confirm crafting works in the latest version

**Comment by jaceiskool11** [comment]
I can confirm it doesn't.

**Comment by sokratis12GR** [comment]
Well, if you can provide more information.

**Comment by jaceiskool11** [comment]
Theres some more information

**Comment by jaceiskool11** [comment]
Okay it does work I was using wrong recipes I downloaded a mod that shows me the recipes sorry, but my other post about the boss's drops not dropping is true
