### ISSUE TITLE
[1.11.2] Boss's don't drop what their supposed to.

### ISSUE THREAD

**Issue by jaceiskool11** [sokratis12GR/ArmorPlus#92]
**ArmorPlus Version**:

**TheDragonLib Version**:

**MinecraftForge Version**:

**Minecraft Version**: 1.11.2

**Client or Server?**:
- [ ] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:

**What happens / happened?**:

**How can I reproduce it?**:

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
Closing until more information is provided.
I can confirm bosses drop their drops.

**Comment by sokratis12GR** [comment]
@jaceiskool11 still need more information, that if this exists I can fix the issue.

**Comment by jaceiskool11** [comment]
All this information game ise is the same as the other post, but what happens in the ender dragon doesnt drop scales, the guardian boss drops one thing, and the wither boss drops nothing.

**Comment by sokratis12GR** [comment]
have you tried to re-try to kill them ?

**Comment by jaceiskool11** [comment]
I have gone into a different world in creative mode and spawned them in, I have killed over 10 withers and the ender dragon twice now, I know for sure that the drops for them aren't working, The regular gaurdians drop fine and the ender dragon zombie drops 1 scale and the wither skeleton drops 1 bone

**Comment by sokratis12GR** [comment]
which A+ version are you using ?

**Comment by sokratis12GR** [comment]
I'll also need Modlist, TheDragonLib version, Forge Version AND the config file

**Comment by jaceiskool11** [comment]
ArmorPlus Version: armorplus-1.11.2-9.4.1.2-beta

TheDragonLib Version: thedragonlib-1.11.2-2.1.0

MinecraftForge Version: 1.11.2-forge1.11.2-13.20.0.2224

Minecraft Version: 1.11.2

Client or Server?:

 Client
 Server
Crash Report (via. Pastebin):

What happens / happened?: I can try any recipe that uses the High-Tech Bench and none of them will work.

How can I reproduce it?:

(Optional) Mod List: Optifine, Simple Teleporters, treechopper

**Comment by sokratis12GR** [comment]
Fixed the issue. It will be publicly available soon. thanks for the report

**Comment by jaceiskool11** [comment]
ty ty

**Comment by jaceiskool11** [comment]
Any idea when this will be fixed and when it is will the update also fix the bows?

**Comment by jaceiskool11** [comment]
Also I have a suggestion, i don't know where to post those so ima just put it here, But with the ultimate armor, I think it would be a good idea to in addition to needing the enderdragon armor, guardian armor, and superstar armor, you also need the obsidian and lava armor. They could make up the tops and bottom parts of the crafting recipe and would add fire resistance and resistance to the effects. Just a thought
