### ISSUE TITLE
No Way To Repair Tools&Armors ?

### ISSUE THREAD

**Issue by ghost** [sokratis12GR/ArmorPlus#93]
is there already a way, forgive me. But i tried many ways. Is there? using game 1.11.2 forge 2222

**Comment by sokratis12GR** [comment]
have you tried repairing them with their crafting material ?

**Comment by sokratis12GR** [comment]
and which gamemode are you using ?

**Comment by sokratis12GR** [comment]
because 0 - easy; 1 - expert; 2 - hellish (no way to repair items)

**Comment by ghost** [comment]
i tried with crafting material, yes. it didn't work. gamemode? what do you mean? in survival mode i am in? or difficulty? it is normal...

**Comment by sokratis12GR** [comment]
I mean config changes

**Comment by ghost** [comment]
oh, it is 1

**Comment by ghost** [comment]
should i make it 0 ?

**Comment by sokratis12GR** [comment]
you shouldn't need to hmm... thats strange

**Comment by ghost** [comment]
btw, for example i have superstar battleaxe. i tried wither bone to repair it.(in crafting slots) do i do wrong?

**Comment by sokratis12GR** [comment]
yes... you need an anvil

**Comment by ghost** [comment]
oh... sorry... i didn't know that.

**Comment by sokratis12GR** [comment]
no worries, thanks for you time.

**Comment by ghost** [comment]
and ah, forgive me but i just wonder what is the changelog for the new version :D

**Comment by sokratis12GR** [comment]
there will be a hot fix because of a bug and the addition of JEI support for the Infuser

**Comment by ghost** [comment]
okay, thanks a lot.

**Comment by ghost** [comment]
oh, please forgive me but how to repair the item with anvil? i placed the super star battleaxe to the leften slot on anvil, and placed wither bone to the righten slot. but nothing happened. am i wrong again?

**Comment by ghost** [comment]
still waiting for help :D can't we repair items on anvil?

**Comment by sokratis12GR** [comment]
Armors can be repaired with their crafted materials,
except if config is set to gamemode 2 (hellish)

**Comment by ghost** [comment]
weapons?

**Comment by ghost** [comment]
it's 1 as default, if i make it 0 can i repair my wepon or armor on crafting or anvil? thanks.

**Comment by sokratis12GR** [comment]
armors/weapons anything can be repaired from gamemode 0-1

**Comment by ghost** [comment]
then why i can't repair my superstar battleaxe on anvil with wither bone :D

**Comment by sokratis12GR** [comment]
:/ It supposed to be repaired with Wither Bones, but I guess, it doesn't work anymore hmm, gonna be fixed soon, hopefully

**Comment by ghost** [comment]
^^ i'm waiting this be fixed for months :D

**Comment by sokratis12GR** [comment]
sorry, I just never really looked in depth to it... its a problem of how I register them Items... uhm this to be fixed... will require RIPing off all the materials from all worlds

**Comment by sokratis12GR** [comment]
currently you can repair it with Guardian scale or Chainmail

**Comment by ghost** [comment]
no problem ^^ waiting for the new release

**Comment by sokratis12GR** [comment]
The problem is that the new release will be game+world-breaking update... the upcoming versions will be released as ALPHA and won't be stable at all, because after each update you would need a new world, because everything will depend on world generation (abilities, recipes, armors, bosses, etc...)

**Comment by ghost** [comment]
hmmm... can you add more structures such as the classic armorplus tower to the world generation please? i really like structures that spawns on the world generation ^^

**Comment by sokratis12GR** [comment]
that is kind a the plan :) and more: https://www.reddit.com/r/feedthebeast/comments/61ti0c/new_blocks_for_the_upcoming_armorplus_update_more/

**Comment by ghost** [comment]
nice to hear that

**Comment by sokratis12GR** [comment]
Alright, after so many issues occurred for 1.11.2 ... I'm going to release a pre-change update fixing those :)

**Comment by ghost** [comment]
Thanks. And we are waiting for more structures :)

**Comment by sokratis12GR** [comment]
well, the upcoming update will have excluded some of the stuffs that this will be upcoming soon

**Comment by sokratis12GR** [comment]
Its mainly just bug fixes and addition of #120

**Comment by ghost** [comment]
ohh my god i'm so sorry, plz don't take care with my latest comment. i was just confused and thought it's ToroQuest mod xD sorry.
edit: i edited/fixed my comment.

**Comment by sokratis12GR** [comment]
Fixed in [armorplus-1.11.2-10.2.0.1](https://minecraft.curseforge.com/projects/armorplus/files/2415900) :)

**Comment by ghost** [comment]
thanks!
