### ISSUE TITLE
Another Problem with the bows.

### ISSUE THREAD

**Issue by MakroxMiau** [sokratis12GR/ArmorPlus#94]
**ArmorPlus Version**: armorplus-1.11.2-9.5.2.3-beta

**TheDragonLib Version**: thedragonlib-1.11.2-2.1.0

**MinecraftForge Version**: forge-1.11.2-13.20.0.2226

**Minecraft Version**: Minecraft 1.11.2

**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: IDK how to get it out of the new launcher.

**What happens / happened?**: I took a guardian bow from the creative, I fired and the game crashed.

**How can I reproduce it?**:Take any bow and shoot.

**(Optional) Mod List**: only armorplus to prove it

**Comment by sokratis12GR** [comment]
Duplicate of #90
