### ISSUE TITLE
Missing Textures in JEI

### ISSUE THREAD

**Issue by SpeedSlider** [sokratis12GR/ArmorPlus#95]
**ArmorPlus Version**:
9.5.2.3

**TheDragonLib Version**:
N/A

**MinecraftForge Version**:
13.20.0.2226

**Minecraft Version**:
1.11.2

**Client or Server?**:
- [X ] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
N/A

**What happens / happened?**:
The following textures are missing in JEI. Screenshot is included.
-tile.armorplus.test__block.name
-Lava Infuser
-Lava Infuser Infusing

**How can I reproduce it?**:
Use JEI in ATM2 Version 0.41 and search @armor

**(Optional) Mod List**: ATM2 Version 0.41
![2017-02-01_12 26 53](https://cloud.githubusercontent.com/assets/25437944/22518200/c536abfe-e879-11e6-8057-fda1d1d66cfa.png)

**Comment by sokratis12GR** [comment]
That's normal, these blocks don't have a model nor textures

**Comment by SpeedSlider** [comment]
It would seem to me that if they are just place holders then they should be removed from the public files and kept in the w.i.p. working version. I cannot verify that you mod is causing the issue but I know at least two other mods with the same issue prevent me from running Optifine using a modpack with the mods missing textures; more specifically I can using Optifine to play the game I just can't use JEI on the pages with the missing textures. I understand that you are not obligated to change/address the issue just so I can use Optifine.

P.S. in my opinion the missing textures detract from the overall professionalism and appearance of the mod.

**Comment by Moritz30** [comment]
@SpeedSlider Missing textures themselves should not cause any problems. If Optifine can't handle them then you should report the issue to Optifine. If you think our mod is unprofessional feel free to stop using it ;)

**Comment by SpeedSlider** [comment]
No worries... sorry to bother you. Thought I was trying to help and since I don't currently author mod packs your safe, but as an end user I guess I will follow your advice since I am not obligated to use a mod just because it is in a modpack. No need to further waste time by replying to my string.

**Comment by Moritz30** [comment]
I did not say that bug reports don't help us. Just that you are not forced to use the mod.
