### ISSUE TITLE
Armorplus items not craftable in existing Survival world (works fine in existing Creative worlds)

### ISSUE THREAD

**Issue by splundig** [sokratis12GR/ArmorPlus#97]
**ArmorPlus Version**: armorplus-1.11.2-9.5.3.4-beta.jar  (note - problem has persisted since v1.9)

**TheDragonLib Version**:thedragonlib-1.11.2-2.2.3

**MinecraftForge Version**:forge-1.11.2-13.20.0.2226-universal

**Minecraft Version**: 1.11.2

**Client or Server?**:
- [ ] Client
- [ x] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: n/a

**What happens / happened?**: 

We are completely unable to craft any Armorplus items in existing Survival worlds. We are using the correct recipes. The server software is up to date.  The same problem is experienced by all multiplayer clients, all of whom have the same software and mod versions. 

However it runs just fine for both existing and new _Creative_ worlds (all items accessible from inventory and usable) in both single player and LAN multiplayer. 

_Note that we have had this problem since Forge 1.9 onwards -_ Armorplus worked just fine before that. (Rolling back all the mods and dependencies has not helped, and would not be ideal anyway.) We have tried to use every iteration of Armorplus since with no joy. 

Very grateful for help. 

**How can I reproduce it?**: n/a

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
Alright, could you also provide me this info:
1. How did you try to craft them ?
2. Where did you try to craft them ?
3. Have you tried using the JEI integration ?

The recipes should all be working, except the that recipes in the wiki are outdated.

**Comment by splundig** [comment]
Thanks for responding - oddly, installing JEI has fixed it. How strange.

Now, if only I could find block lava crystals ANYWHERE....
thanks,
S
